.TH "moeoScalarFitnessAssignment" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoScalarFitnessAssignment \- \fBmoeoScalarFitnessAssignment\fP is a \fBmoeoFitnessAssignment\fP for scalar strategies.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoScalarFitnessAssignment.h>\fP
.PP
Inherits \fBmoeoFitnessAssignment< MOEOT >< MOEOT >\fP.
.PP
Inherited by \fBmoeoAchievementFitnessAssignment< MOEOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoScalarFitnessAssignment< MOEOT >"
\fBmoeoScalarFitnessAssignment\fP is a \fBmoeoFitnessAssignment\fP for scalar strategies. 
.PP
Definition at line 22 of file moeoScalarFitnessAssignment.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEOMovingObjects from the source code.
