.TH "moeoVectorUnaryMetric" 3 "2 Jul 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoVectorUnaryMetric \- Base class for unary metrics dedicated to the performance evaluation of a Pareto set (a vector of objective vectors).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoMetric.h>\fP
.PP
Inherits \fBmoeoUnaryMetric< const std::vector< ObjectiveVector > &, R >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class ObjectiveVector, class R> class moeoVectorUnaryMetric< ObjectiveVector, R >"
Base class for unary metrics dedicated to the performance evaluation of a Pareto set (a vector of objective vectors). 
.PP
Definition at line 50 of file moeoMetric.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
