.TH "moeoIBEA" 3 "26 Jun 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoIBEA \- IBEA (Indicator-Based Evolutionary Algorithm) as described in: E.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoIBEA.h>\fP
.PP
Inherits \fBmoeoEA< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef MOEOT::ObjectiveVector \fBObjectiveVector\fP"
.br
.RI "\fIThe type of objective vector. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoIBEA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoGenOp\fP< MOEOT > &_op, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > &_metric, const double _kappa=0.05)"
.br
.RI "\fISimple ctor with a \fBeoGenOp\fP. \fP"
.ti -1c
.RI "\fBmoeoIBEA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoTransform\fP< MOEOT > &_op, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > &_metric, const double _kappa=0.05)"
.br
.RI "\fISimple ctor with a \fBeoTransform\fP. \fP"
.ti -1c
.RI "\fBmoeoIBEA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoQuadOp\fP< MOEOT > &_crossover, double _pCross, \fBeoMonOp\fP< MOEOT > &_mutation, double _pMut, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > &_metric, const double _kappa=0.05)"
.br
.RI "\fICtor with a crossover, a mutation and their corresponding rates. \fP"
.ti -1c
.RI "\fBmoeoIBEA\fP (\fBeoContinue\fP< MOEOT > &_continuator, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoGenOp\fP< MOEOT > &_op, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > &_metric, const double _kappa=0.05)"
.br
.RI "\fICtor with a continuator (instead of _maxGen) and a \fBeoGenOp\fP. \fP"
.ti -1c
.RI "\fBmoeoIBEA\fP (\fBeoContinue\fP< MOEOT > &_continuator, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoTransform\fP< MOEOT > &_op, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > &_metric, const double _kappa=0.05)"
.br
.RI "\fICtor with a continuator (instead of _maxGen) and a \fBeoTransform\fP. \fP"
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBeoPop\fP< MOEOT > &_pop)"
.br
.RI "\fIApply a few generation of evolution to the population _pop until the stopping criteria is verified. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBeoGenContinue\fP< MOEOT > \fBdefaultGenContinuator\fP"
.br
.RI "\fIa continuator based on the number of generations (used as default) \fP"
.ti -1c
.RI "\fBeoContinue\fP< MOEOT > & \fBcontinuator\fP"
.br
.RI "\fIstopping criteria \fP"
.ti -1c
.RI "\fBeoPopLoopEval\fP< MOEOT > \fBpopEval\fP"
.br
.RI "\fIevaluation function used to evaluate the whole population \fP"
.ti -1c
.RI "\fBmoeoDetTournamentSelect\fP< MOEOT > \fBselect\fP"
.br
.RI "\fIbinary tournament selection \fP"
.ti -1c
.RI "\fBmoeoIndicatorBasedFitnessAssignment\fP< MOEOT > \fBfitnessAssignment\fP"
.br
.RI "\fIfitness assignment used in IBEA \fP"
.ti -1c
.RI "\fBmoeoDummyDiversityAssignment\fP< MOEOT > \fBdummyDiversityAssignment\fP"
.br
.RI "\fIdummy diversity assignment \fP"
.ti -1c
.RI "\fBmoeoEnvironmentalReplacement\fP< MOEOT > \fBreplace\fP"
.br
.RI "\fIelitist replacement \fP"
.ti -1c
.RI "\fBeoSGAGenOp\fP< MOEOT > \fBdefaultSGAGenOp\fP"
.br
.RI "\fIan object for genetic operators (used as default) \fP"
.ti -1c
.RI "\fBeoGeneralBreeder\fP< MOEOT > \fBgenBreed\fP"
.br
.RI "\fIgeneral breeder \fP"
.ti -1c
.RI "\fBeoBreed\fP< MOEOT > & \fBbreed\fP"
.br
.RI "\fIbreeder \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoIBEA< MOEOT >"
IBEA (Indicator-Based Evolutionary Algorithm) as described in: E. 

Zitzler, S. Künzli, 'Indicator-Based Selection in Multiobjective Search', Proc. 8th International Conference on Parallel Problem Solving from Nature (PPSN VIII), pp. 832-842, Birmingham, UK (2004). This class builds the IBEA algorithm only by using the fine-grained components of the ParadisEO-MOEO framework. 
.PP
Definition at line 38 of file moeoIBEA.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class MOEOT> \fBmoeoIBEA\fP< MOEOT >::\fBmoeoIBEA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoGenOp\fP< MOEOT > & _op, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > & _metric, const double _kappa = \fC0.05\fP)\fC [inline]\fP"
.PP
Simple ctor with a \fBeoGenOp\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_maxGen\fP number of generations before stopping 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.br
\fI_metric\fP metric 
.br
\fI_kappa\fP scaling factor kappa 
.RE
.PP

.PP
Definition at line 54 of file moeoIBEA.h.
.SS "template<class MOEOT> \fBmoeoIBEA\fP< MOEOT >::\fBmoeoIBEA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoTransform\fP< MOEOT > & _op, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > & _metric, const double _kappa = \fC0.05\fP)\fC [inline]\fP"
.PP
Simple ctor with a \fBeoTransform\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_maxGen\fP number of generations before stopping 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.br
\fI_metric\fP metric 
.br
\fI_kappa\fP scaling factor kappa 
.RE
.PP

.PP
Definition at line 68 of file moeoIBEA.h.
.SS "template<class MOEOT> \fBmoeoIBEA\fP< MOEOT >::\fBmoeoIBEA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoQuadOp\fP< MOEOT > & _crossover, double _pCross, \fBeoMonOp\fP< MOEOT > & _mutation, double _pMut, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > & _metric, const double _kappa = \fC0.05\fP)\fC [inline]\fP"
.PP
Ctor with a crossover, a mutation and their corresponding rates. 
.PP
\fBParameters:\fP
.RS 4
\fI_maxGen\fP number of generations before stopping 
.br
\fI_eval\fP evaluation function 
.br
\fI_crossover\fP crossover 
.br
\fI_pCross\fP crossover probability 
.br
\fI_mutation\fP mutation 
.br
\fI_pMut\fP mutation probability 
.br
\fI_metric\fP metric 
.br
\fI_kappa\fP scaling factor kappa 
.RE
.PP

.PP
Definition at line 85 of file moeoIBEA.h.
.SS "template<class MOEOT> \fBmoeoIBEA\fP< MOEOT >::\fBmoeoIBEA\fP (\fBeoContinue\fP< MOEOT > & _continuator, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoGenOp\fP< MOEOT > & _op, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > & _metric, const double _kappa = \fC0.05\fP)\fC [inline]\fP"
.PP
Ctor with a continuator (instead of _maxGen) and a \fBeoGenOp\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_continuator\fP stopping criteria 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.br
\fI_metric\fP metric 
.br
\fI_kappa\fP scaling factor kappa 
.RE
.PP

.PP
Definition at line 100 of file moeoIBEA.h.
.SS "template<class MOEOT> \fBmoeoIBEA\fP< MOEOT >::\fBmoeoIBEA\fP (\fBeoContinue\fP< MOEOT > & _continuator, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoTransform\fP< MOEOT > & _op, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > & _metric, const double _kappa = \fC0.05\fP)\fC [inline]\fP"
.PP
Ctor with a continuator (instead of _maxGen) and a \fBeoTransform\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_continuator\fP stopping criteria 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.br
\fI_metric\fP metric 
.br
\fI_kappa\fP scaling factor kappa 
.RE
.PP

.PP
Definition at line 114 of file moeoIBEA.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> virtual void \fBmoeoIBEA\fP< MOEOT >::operator() (\fBeoPop\fP< MOEOT > & _pop)\fC [inline, virtual]\fP"
.PP
Apply a few generation of evolution to the population _pop until the stopping criteria is verified. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.RE
.PP

.PP
Definition at line 124 of file moeoIBEA.h.
.PP
References moeoIBEA< MOEOT >::breed, moeoIBEA< MOEOT >::continuator, moeoIBEA< MOEOT >::dummyDiversityAssignment, moeoIBEA< MOEOT >::fitnessAssignment, moeoIBEA< MOEOT >::popEval, and moeoIBEA< MOEOT >::replace.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
