.TH "moeoFrontByFrontCrowdingDistanceDiversityAssignment" 3 "26 Jun 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoFrontByFrontCrowdingDistanceDiversityAssignment \- Diversity assignment sheme based on crowding distance proposed in: K.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoFrontByFrontCrowdingDistanceDiversityAssignment.h>\fP
.PP
Inherits \fBmoeoCrowdingDistanceDiversityAssignment< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef MOEOT::ObjectiveVector \fBObjectiveVector\fP"
.br
.RI "\fIthe objective vector type of the solutions \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdateByDeleting\fP (\fBeoPop\fP< MOEOT > &_pop, \fBObjectiveVector\fP &_objVec)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetDistances\fP (\fBeoPop\fP< MOEOT > &_pop)"
.br
.RI "\fISets the distance values. \fP"
.ti -1c
.RI "unsigned int \fBlastIndex\fP (\fBeoPop\fP< MOEOT > &_pop, unsigned int _start)"
.br
.RI "\fIReturns the index of the last individual having the same fitness value than _pop[_start]. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoFrontByFrontCrowdingDistanceDiversityAssignment< MOEOT >"
Diversity assignment sheme based on crowding distance proposed in: K. 

Deb, A. Pratap, S. Agarwal, T. Meyarivan, 'A Fast and Elitist Multi-Objective Genetic Algorithm: NSGA-II', IEEE Transactions on Evolutionary Computation, vol. 6, no. 2 (2002). Tis strategy assigns diversity values FRONT BY FRONT. It is, for instance, used in NSGA-II. 
.PP
Definition at line 25 of file moeoFrontByFrontCrowdingDistanceDiversityAssignment.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> void \fBmoeoFrontByFrontCrowdingDistanceDiversityAssignment\fP< MOEOT >::updateByDeleting (\fBeoPop\fP< MOEOT > & _pop, \fBObjectiveVector\fP & _objVec)\fC [inline, virtual]\fP"
.PP
\fBWarning:\fP
.RS 4
NOT IMPLEMENTED, DO NOTHING ! Updates the diversity values of the whole population _pop by taking the deletion of the objective vector _objVec into account. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.br
\fI_objVec\fP the objective vector 
.RE
.PP
\fBWarning:\fP
.RS 4
NOT IMPLEMENTED, DO NOTHING ! 
.RE
.PP

.PP
Reimplemented from \fBmoeoCrowdingDistanceDiversityAssignment< MOEOT >\fP.
.PP
Definition at line 40 of file moeoFrontByFrontCrowdingDistanceDiversityAssignment.h.
.SS "template<class MOEOT> void \fBmoeoFrontByFrontCrowdingDistanceDiversityAssignment\fP< MOEOT >::setDistances (\fBeoPop\fP< MOEOT > & _pop)\fC [inline, private, virtual]\fP"
.PP
Sets the distance values. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.RE
.PP

.PP
Reimplemented from \fBmoeoCrowdingDistanceDiversityAssignment< MOEOT >\fP.
.PP
Definition at line 55 of file moeoFrontByFrontCrowdingDistanceDiversityAssignment.h.
.PP
References moeoCrowdingDistanceDiversityAssignment< MOEOT >::inf(), moeoFrontByFrontCrowdingDistanceDiversityAssignment< MOEOT >::lastIndex(), and moeoCrowdingDistanceDiversityAssignment< MOEOT >::tiny().
.SS "template<class MOEOT> unsigned int \fBmoeoFrontByFrontCrowdingDistanceDiversityAssignment\fP< MOEOT >::lastIndex (\fBeoPop\fP< MOEOT > & _pop, unsigned int _start)\fC [inline, private]\fP"
.PP
Returns the index of the last individual having the same fitness value than _pop[_start]. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.br
\fI_start\fP the index to start from 
.RE
.PP

.PP
Definition at line 121 of file moeoFrontByFrontCrowdingDistanceDiversityAssignment.h.
.PP
Referenced by moeoFrontByFrontCrowdingDistanceDiversityAssignment< MOEOT >::setDistances().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
