.TH "moeoObjectiveObjectiveVectorComparator" 3 "26 Jun 2007" "Version 1.0" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoObjectiveObjectiveVectorComparator \- Functor allowing to compare two objective vectors according to their first objective value, then their second, and so on.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoObjectiveObjectiveVectorComparator.h>\fP
.PP
Inherits \fBmoeoObjectiveVectorComparator< ObjectiveVector >< ObjectiveVector >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const bool \fBoperator()\fP (const ObjectiveVector &_objectiveVector1, const ObjectiveVector &_objectiveVector2)"
.br
.RI "\fIReturns true if _objectiveVector1 < _objectiveVector2 on the first objective, then on the second, and so on. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ObjectiveVector> class moeoObjectiveObjectiveVectorComparator< ObjectiveVector >"
Functor allowing to compare two objective vectors according to their first objective value, then their second, and so on. 
.PP
Definition at line 22 of file moeoObjectiveObjectiveVectorComparator.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class ObjectiveVector> const bool \fBmoeoObjectiveObjectiveVectorComparator\fP< ObjectiveVector >::operator() (const ObjectiveVector & _objectiveVector1, const ObjectiveVector & _objectiveVector2)\fC [inline]\fP"
.PP
Returns true if _objectiveVector1 < _objectiveVector2 on the first objective, then on the second, and so on. 
.PP
\fBParameters:\fP
.RS 4
\fI_objectiveVector1\fP the first objective vector 
.br
\fI_objectiveVector2\fP the second objective vector 
.RE
.PP

.PP
Definition at line 31 of file moeoObjectiveObjectiveVectorComparator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
