.TH "moeoSelectOne" 3 "26 Jun 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoSelectOne \- Selection strategy for multi-objective optimization that selects only one element from a whole population.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoSelectOne.h>\fP
.PP
Inherits \fBeoSelectOne< MOEOT >\fP.
.PP
Inherited by \fBmoeoDetTournamentSelect< MOEOT >\fP, \fBmoeoRandomSelect< MOEOT >\fP, \fBmoeoRouletteSelect< MOEOT >\fP, \fBmoeoSelectFromPopAndArch< MOEOT >\fP, and \fBmoeoStochTournamentSelect< MOEOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoSelectOne< MOEOT >"
Selection strategy for multi-objective optimization that selects only one element from a whole population. 
.PP
Definition at line 22 of file moeoSelectOne.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
