.TH "moeoLS" 3 "2 Jul 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoLS \- Abstract class for local searches applied to multi-objective optimization.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoLS.h>\fP
.PP
Inherits \fBmoeoAlgo\fP, and \fBeoBF< Type, moeoArchive< MOEOT > &, void >\fP.
.PP
Inherited by \fBmoeoCombinedLS< MOEOT, Type >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT, class Type> class moeoLS< MOEOT, Type >"
Abstract class for local searches applied to multi-objective optimization. 

Starting from a Type (i.e.: an individual, a pop, an archive...), it produces a set of new non-dominated solutions. 
.PP
Definition at line 25 of file moeoLS.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
