.TH "moeoUM" 3 "6 Dec 2006" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoUM \- Base class for unary metrics.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoMetric.h>\fP
.PP
Inherits \fBmoeoMetric\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class A, class R> class moeoUM< A, R >"
Base class for unary metrics. 
.PP
Definition at line 29 of file moeoMetric.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
