.TH "moeoContributionMetric" 3 "5 Jul 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoContributionMetric \- The contribution metric evaluates the proportion of non-dominated solutions given by a Pareto set relatively to another Pareto set (Meunier, Talbi, Reininger: 'A multiobjective genetic algorithm for radio network optimization', in Proc.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoContributionMetric.h>\fP
.PP
Inherits \fBmoeoVectorVsVectorBinaryMetric< ObjectiveVector, double >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBoperator()\fP (const std::vector< ObjectiveVector > &_set1, const std::vector< ObjectiveVector > &_set2)"
.br
.RI "\fIReturns the contribution of the Pareto set '_set1' relatively to the Pareto set '_set2'. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "unsigned int \fBcard_C\fP (const std::vector< ObjectiveVector > &_set1, const std::vector< ObjectiveVector > &_set2)"
.br
.RI "\fIReturns the number of solutions both in '_set1' and '_set2'. \fP"
.ti -1c
.RI "unsigned int \fBcard_W\fP (const std::vector< ObjectiveVector > &_set1, const std::vector< ObjectiveVector > &_set2)"
.br
.RI "\fIReturns the number of solutions in '_set1' dominating at least one solution of '_set2'. \fP"
.ti -1c
.RI "unsigned int \fBcard_N\fP (const std::vector< ObjectiveVector > &_set1, const std::vector< ObjectiveVector > &_set2)"
.br
.RI "\fIReturns the number of solutions in '_set1' having no relation of dominance with those from '_set2'. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBmoeoParetoObjectiveVectorComparator\fP< ObjectiveVector > \fBparetoComparator\fP"
.br
.RI "\fIFunctor to compare two objective vectors according to Pareto dominance relation. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ObjectiveVector> class moeoContributionMetric< ObjectiveVector >"
The contribution metric evaluates the proportion of non-dominated solutions given by a Pareto set relatively to another Pareto set (Meunier, Talbi, Reininger: 'A multiobjective genetic algorithm for radio network optimization', in Proc. 

of the 2000 Congress on Evolutionary Computation, IEEE Press, pp. 317-324) 
.PP
Definition at line 24 of file moeoContributionMetric.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class ObjectiveVector> double \fBmoeoContributionMetric\fP< ObjectiveVector >::operator() (const std::vector< ObjectiveVector > & _set1, const std::vector< ObjectiveVector > & _set2)\fC [inline]\fP"
.PP
Returns the contribution of the Pareto set '_set1' relatively to the Pareto set '_set2'. 
.PP
\fBParameters:\fP
.RS 4
\fI_set1\fP the first Pareto set 
.br
\fI_set2\fP the second Pareto set 
.RE
.PP

.PP
Definition at line 33 of file moeoContributionMetric.h.
.PP
References moeoContributionMetric< ObjectiveVector >::card_C(), moeoContributionMetric< ObjectiveVector >::card_N(), and moeoContributionMetric< ObjectiveVector >::card_W().
.SS "template<class ObjectiveVector> unsigned int \fBmoeoContributionMetric\fP< ObjectiveVector >::card_C (const std::vector< ObjectiveVector > & _set1, const std::vector< ObjectiveVector > & _set2)\fC [inline, private]\fP"
.PP
Returns the number of solutions both in '_set1' and '_set2'. 
.PP
\fBParameters:\fP
.RS 4
\fI_set1\fP the first Pareto set 
.br
\fI_set2\fP the second Pareto set 
.RE
.PP

.PP
Definition at line 54 of file moeoContributionMetric.h.
.PP
Referenced by moeoContributionMetric< ObjectiveVector >::operator()().
.SS "template<class ObjectiveVector> unsigned int \fBmoeoContributionMetric\fP< ObjectiveVector >::card_W (const std::vector< ObjectiveVector > & _set1, const std::vector< ObjectiveVector > & _set2)\fC [inline, private]\fP"
.PP
Returns the number of solutions in '_set1' dominating at least one solution of '_set2'. 
.PP
\fBParameters:\fP
.RS 4
\fI_set1\fP the first Pareto set 
.br
\fI_set2\fP the second Pareto set 
.RE
.PP

.PP
Definition at line 71 of file moeoContributionMetric.h.
.PP
References moeoContributionMetric< ObjectiveVector >::paretoComparator.
.PP
Referenced by moeoContributionMetric< ObjectiveVector >::operator()().
.SS "template<class ObjectiveVector> unsigned int \fBmoeoContributionMetric\fP< ObjectiveVector >::card_N (const std::vector< ObjectiveVector > & _set1, const std::vector< ObjectiveVector > & _set2)\fC [inline, private]\fP"
.PP
Returns the number of solutions in '_set1' having no relation of dominance with those from '_set2'. 
.PP
\fBParameters:\fP
.RS 4
\fI_set1\fP the first Pareto set 
.br
\fI_set2\fP the second Pareto set 
.RE
.PP

.PP
Definition at line 89 of file moeoContributionMetric.h.
.PP
References moeoContributionMetric< ObjectiveVector >::paretoComparator.
.PP
Referenced by moeoContributionMetric< ObjectiveVector >::operator()().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
