.TH "moeoFitnessThenDiversityComparator" 3 "2 Jul 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoFitnessThenDiversityComparator \- Functor allowing to compare two solutions according to their fitness values, then according to their diversity values.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoFitnessThenDiversityComparator.h>\fP
.PP
Inherits \fBmoeoComparator< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const bool \fBoperator()\fP (const MOEOT &_moeo1, const MOEOT &_moeo2)"
.br
.RI "\fIReturns true if _moeo1 < _moeo2 according to their fitness values, then according to their diversity values. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoFitnessThenDiversityComparator< MOEOT >"
Functor allowing to compare two solutions according to their fitness values, then according to their diversity values. 
.PP
Definition at line 22 of file moeoFitnessThenDiversityComparator.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> const bool \fBmoeoFitnessThenDiversityComparator\fP< MOEOT >::operator() (const MOEOT & _moeo1, const MOEOT & _moeo2)\fC [inline]\fP"
.PP
Returns true if _moeo1 < _moeo2 according to their fitness values, then according to their diversity values. 
.PP
\fBParameters:\fP
.RS 4
\fI_moeo1\fP the first solution 
.br
\fI_moeo2\fP the second solution 
.RE
.PP

.PP
Definition at line 31 of file moeoFitnessThenDiversityComparator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
