.TH "moeoEnvironmentalReplacement" 3 "5 Jul 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoEnvironmentalReplacement \- Environmental replacement strategy that consists in keeping the N best individuals by deleting individuals 1 by 1 and by updating the fitness and diversity values after each deletion.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoEnvironmentalReplacement.h>\fP
.PP
Inherits \fBmoeoReplacement< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef MOEOT::ObjectiveVector \fBObjectiveVector\fP"
.br
.RI "\fIThe type for objective vector. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoEnvironmentalReplacement\fP (\fBmoeoFitnessAssignment\fP< MOEOT > &_fitnessAssignment, \fBmoeoDiversityAssignment\fP< MOEOT > &_diversityAssignment, \fBmoeoComparator\fP< MOEOT > &_comparator)"
.br
.RI "\fIFull constructor. \fP"
.ti -1c
.RI "\fBmoeoEnvironmentalReplacement\fP (\fBmoeoFitnessAssignment\fP< MOEOT > &_fitnessAssignment, \fBmoeoDiversityAssignment\fP< MOEOT > &_diversityAssignment)"
.br
.RI "\fIConstructor without comparator. \fP"
.ti -1c
.RI "\fBmoeoEnvironmentalReplacement\fP (\fBmoeoFitnessAssignment\fP< MOEOT > &_fitnessAssignment, \fBmoeoComparator\fP< MOEOT > &_comparator)"
.br
.RI "\fIConstructor without moeoDiversityAssignement. \fP"
.ti -1c
.RI "\fBmoeoEnvironmentalReplacement\fP (\fBmoeoFitnessAssignment\fP< MOEOT > &_fitnessAssignment)"
.br
.RI "\fIConstructor without moeoDiversityAssignement nor \fBmoeoComparator\fP. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< MOEOT > &_parents, \fBeoPop\fP< MOEOT > &_offspring)"
.br
.RI "\fIReplaces the first population by adding the individuals of the second one, sorting with a \fBmoeoComparator\fP and resizing the whole population obtained. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBmoeoFitnessAssignment\fP< MOEOT > & \fBfitnessAssignment\fP"
.br
.RI "\fIthe fitness assignment strategy \fP"
.ti -1c
.RI "\fBmoeoDiversityAssignment\fP< MOEOT > & \fBdiversityAssignment\fP"
.br
.RI "\fIthe diversity assignment strategy \fP"
.ti -1c
.RI "\fBmoeoDummyDiversityAssignment\fP< MOEOT > \fBdefaultDiversity\fP"
.br
.RI "\fIa dummy diversity assignment can be used as default \fP"
.ti -1c
.RI "\fBmoeoFitnessThenDiversityComparator\fP< MOEOT > \fBdefaultComparator\fP"
.br
.RI "\fIa fitness then diversity comparator can be used as default \fP"
.ti -1c
.RI "\fBmoeoEnvironmentalReplacement::Cmp\fP \fBcomparator\fP"
.br
.RI "\fIthis object is used to compare solutions in order to sort the population \fP"
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCmp\fP"
.br
.RI "\fIthis object is used to compare solutions in order to sort the population \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoEnvironmentalReplacement< MOEOT >"
Environmental replacement strategy that consists in keeping the N best individuals by deleting individuals 1 by 1 and by updating the fitness and diversity values after each deletion. 
.PP
Definition at line 26 of file moeoEnvironmentalReplacement.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class MOEOT> \fBmoeoEnvironmentalReplacement\fP< MOEOT >::\fBmoeoEnvironmentalReplacement\fP (\fBmoeoFitnessAssignment\fP< MOEOT > & _fitnessAssignment, \fBmoeoDiversityAssignment\fP< MOEOT > & _diversityAssignment, \fBmoeoComparator\fP< MOEOT > & _comparator)\fC [inline]\fP"
.PP
Full constructor. 
.PP
\fBParameters:\fP
.RS 4
\fI_fitnessAssignment\fP the fitness assignment strategy 
.br
\fI_diversityAssignment\fP the diversity assignment strategy 
.br
\fI_comparator\fP the comparator (used to compare 2 individuals) 
.RE
.PP

.PP
Definition at line 40 of file moeoEnvironmentalReplacement.h.
.SS "template<class MOEOT> \fBmoeoEnvironmentalReplacement\fP< MOEOT >::\fBmoeoEnvironmentalReplacement\fP (\fBmoeoFitnessAssignment\fP< MOEOT > & _fitnessAssignment, \fBmoeoDiversityAssignment\fP< MOEOT > & _diversityAssignment)\fC [inline]\fP"
.PP
Constructor without comparator. 
.PP
A moeoFitThenDivComparator is used as default. 
.PP
\fBParameters:\fP
.RS 4
\fI_fitnessAssignment\fP the fitness assignment strategy 
.br
\fI_diversityAssignment\fP the diversity assignment strategy 
.RE
.PP

.PP
Definition at line 50 of file moeoEnvironmentalReplacement.h.
.SS "template<class MOEOT> \fBmoeoEnvironmentalReplacement\fP< MOEOT >::\fBmoeoEnvironmentalReplacement\fP (\fBmoeoFitnessAssignment\fP< MOEOT > & _fitnessAssignment, \fBmoeoComparator\fP< MOEOT > & _comparator)\fC [inline]\fP"
.PP
Constructor without moeoDiversityAssignement. 
.PP
A dummy diversity is used as default. 
.PP
\fBParameters:\fP
.RS 4
\fI_fitnessAssignment\fP the fitness assignment strategy 
.br
\fI_comparator\fP the comparator (used to compare 2 individuals) 
.RE
.PP

.PP
Definition at line 60 of file moeoEnvironmentalReplacement.h.
.SS "template<class MOEOT> \fBmoeoEnvironmentalReplacement\fP< MOEOT >::\fBmoeoEnvironmentalReplacement\fP (\fBmoeoFitnessAssignment\fP< MOEOT > & _fitnessAssignment)\fC [inline]\fP"
.PP
Constructor without moeoDiversityAssignement nor \fBmoeoComparator\fP. 
.PP
A moeoFitThenDivComparator and a dummy diversity are used as default. 
.PP
\fBParameters:\fP
.RS 4
\fI_fitnessAssignment\fP the fitness assignment strategy 
.RE
.PP

.PP
Definition at line 70 of file moeoEnvironmentalReplacement.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> void \fBmoeoEnvironmentalReplacement\fP< MOEOT >::operator() (\fBeoPop\fP< MOEOT > & _parents, \fBeoPop\fP< MOEOT > & _offspring)\fC [inline]\fP"
.PP
Replaces the first population by adding the individuals of the second one, sorting with a \fBmoeoComparator\fP and resizing the whole population obtained. 
.PP
\fBParameters:\fP
.RS 4
\fI_parents\fP the population composed of the parents (the population you want to replace) 
.br
\fI_offspring\fP the offspring population 
.RE
.PP

.PP
Definition at line 80 of file moeoEnvironmentalReplacement.h.
.PP
References moeoEnvironmentalReplacement< MOEOT >::comparator, moeoEnvironmentalReplacement< MOEOT >::diversityAssignment, and moeoEnvironmentalReplacement< MOEOT >::fitnessAssignment.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
