.TH "FlowShopOpMutationExchange" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlowShopOpMutationExchange \- Exchange mutation operator for the flow-shop.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <FlowShopOpMutationExchange.h>\fP
.PP
Inherits \fBeoMonOp< FlowShop >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBclassName\fP () const "
.br
.RI "\fIthe class name (used to display statistics) \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBFlowShop\fP &_flowshop)"
.br
.RI "\fImodifies the parent with an exchange mutation \fP"
.in -1c
.SH "Detailed Description"
.PP 
Exchange mutation operator for the flow-shop. 
.PP
Definition at line 47 of file FlowShopOpMutationExchange.h.
.SH "Member Function Documentation"
.PP 
.SS "bool FlowShopOpMutationExchange::operator() (\fBFlowShop\fP & _flowshop)\fC [virtual]\fP"
.PP
modifies the parent with an exchange mutation 
.PP
\fBParameters:\fP
.RS 4
\fI_flowshop\fP the parent genotype (will be modified) 
.RE
.PP

.PP
Implements \fBeoUF< FlowShop &, bool >\fP.
.PP
Definition at line 47 of file FlowShopOpMutationExchange.cpp.
.PP
References eoRng::random(), and moeoVector< MOEOObjectiveVector, MOEOFitness, MOEODiversity, GeneType >::value().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEOMovingObjects from the source code.
