.TH "moeoDiversityAssignment" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoDiversityAssignment \- Functor that sets the diversity values of a whole population.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoDiversityAssignment.h>\fP
.PP
Inherits \fBeoUF< eoPop< MOEOT > &, void >\fP.
.PP
Inherited by \fBmoeoCrowdingDiversityAssignment< MOEOT >\fP, \fBmoeoDummyDiversityAssignment< MOEOT >\fP, and \fBmoeoSharingDiversityAssignment< MOEOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef MOEOT::ObjectiveVector \fBObjectiveVector\fP"
.br
.RI "\fIThe type for objective vector. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBupdateByDeleting\fP (\fBeoPop\fP< MOEOT > &_pop, \fBObjectiveVector\fP &_objVec)=0"
.br
.RI "\fIUpdates the diversity values of the whole population _pop by taking the deletion of the objective vector _objVec into account. \fP"
.ti -1c
.RI "void \fBupdateByDeleting\fP (\fBeoPop\fP< MOEOT > &_pop, MOEOT &_moeo)"
.br
.RI "\fIUpdates the diversity values of the whole population _pop by taking the deletion of the individual _moeo into account. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoDiversityAssignment< MOEOT >"
Functor that sets the diversity values of a whole population. 
.PP
Definition at line 48 of file moeoDiversityAssignment.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> virtual void \fBmoeoDiversityAssignment\fP< MOEOT >::updateByDeleting (\fBeoPop\fP< MOEOT > & _pop, \fBObjectiveVector\fP & _objVec)\fC [pure virtual]\fP"
.PP
Updates the diversity values of the whole population _pop by taking the deletion of the objective vector _objVec into account. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.br
\fI_objVec\fP the objective vector 
.RE
.PP

.PP
Implemented in \fBmoeoCrowdingDiversityAssignment< MOEOT >\fP, \fBmoeoDummyDiversityAssignment< MOEOT >\fP, \fBmoeoFrontByFrontCrowdingDiversityAssignment< MOEOT >\fP, \fBmoeoFrontByFrontSharingDiversityAssignment< MOEOT >\fP, and \fBmoeoSharingDiversityAssignment< MOEOT >\fP.
.PP
Referenced by moeoDiversityAssignment< MOEOT >::updateByDeleting().
.SS "template<class MOEOT> void \fBmoeoDiversityAssignment\fP< MOEOT >::updateByDeleting (\fBeoPop\fP< MOEOT > & _pop, MOEOT & _moeo)\fC [inline]\fP"
.PP
Updates the diversity values of the whole population _pop by taking the deletion of the individual _moeo into account. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.br
\fI_moeo\fP the individual 
.RE
.PP

.PP
Definition at line 69 of file moeoDiversityAssignment.h.
.PP
References moeoDiversityAssignment< MOEOT >::updateByDeleting().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEOMovingObjects from the source code.
