.TH "moeoRealVector" 3 "2 Oct 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoRealVector \- This class is an implementation of a simple double-valued \fBmoeoVector\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoRealVector.h>\fP
.PP
Inherits \fBmoeoVector< MOEOObjectiveVector, MOEOFitness, MOEODiversity, double >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoRealVector\fP (unsigned int _size=0, double _value=0.0)"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIReturns the class name as a std::string. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOObjectiveVector, class MOEOFitness, class MOEODiversity> class moeoRealVector< MOEOObjectiveVector, MOEOFitness, MOEODiversity >"
This class is an implementation of a simple double-valued \fBmoeoVector\fP. 
.PP
Definition at line 45 of file moeoRealVector.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class MOEOObjectiveVector, class MOEOFitness, class MOEODiversity> \fBmoeoRealVector\fP< MOEOObjectiveVector, MOEOFitness, MOEODiversity >::\fBmoeoRealVector\fP (unsigned int _size = \fC0\fP, double _value = \fC0.0\fP)\fC [inline]\fP"
.PP
Ctor. 
.PP
\fBParameters:\fP
.RS 4
\fI_size\fP Length of vector (default is 0) 
.br
\fI_value\fP Initial value of all elements (default is default value of type GeneType) 
.RE
.PP

.PP
Definition at line 54 of file moeoRealVector.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
