.TH "moeoNSGAII" 3 "2 Oct 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoNSGAII \- NSGA-II (Non-dominated Sorting Genetic Algorithm II) as described in: Deb, K., S.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoNSGAII.h>\fP
.PP
Inherits \fBmoeoEA< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoNSGAII\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoGenOp\fP< MOEOT > &_op)"
.br
.RI "\fISimple ctor with a \fBeoGenOp\fP. \fP"
.ti -1c
.RI "\fBmoeoNSGAII\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoTransform\fP< MOEOT > &_op)"
.br
.RI "\fISimple ctor with a \fBeoTransform\fP. \fP"
.ti -1c
.RI "\fBmoeoNSGAII\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoQuadOp\fP< MOEOT > &_crossover, double _pCross, \fBeoMonOp\fP< MOEOT > &_mutation, double _pMut)"
.br
.RI "\fICtor with a crossover, a mutation and their corresponding rates. \fP"
.ti -1c
.RI "\fBmoeoNSGAII\fP (\fBeoContinue\fP< MOEOT > &_continuator, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoGenOp\fP< MOEOT > &_op)"
.br
.RI "\fICtor with a continuator (instead of _maxGen) and a \fBeoGenOp\fP. \fP"
.ti -1c
.RI "\fBmoeoNSGAII\fP (\fBeoContinue\fP< MOEOT > &_continuator, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoTransform\fP< MOEOT > &_op)"
.br
.RI "\fICtor with a continuator (instead of _maxGen) and a \fBeoTransform\fP. \fP"
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBeoPop\fP< MOEOT > &_pop)"
.br
.RI "\fIApply a few generation of evolution to the population _pop until the stopping criteria is verified. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBeoGenContinue\fP< MOEOT > \fBdefaultGenContinuator\fP"
.br
.RI "\fIa continuator based on the number of generations (used as default) \fP"
.ti -1c
.RI "\fBeoContinue\fP< MOEOT > & \fBcontinuator\fP"
.br
.RI "\fIstopping criteria \fP"
.ti -1c
.RI "\fBeoPopLoopEval\fP< MOEOT > \fBpopEval\fP"
.br
.RI "\fIevaluation function used to evaluate the whole population \fP"
.ti -1c
.RI "\fBmoeoDetTournamentSelect\fP< MOEOT > \fBselect\fP"
.br
.RI "\fIbinary tournament selection \fP"
.ti -1c
.RI "\fBmoeoFastNonDominatedSortingFitnessAssignment\fP< MOEOT > \fBfitnessAssignment\fP"
.br
.RI "\fIfitness assignment used in NSGA-II \fP"
.ti -1c
.RI "\fBmoeoFrontByFrontCrowdingDiversityAssignment\fP< MOEOT > \fBdiversityAssignment\fP"
.br
.RI "\fIdiversity assignment used in NSGA-II \fP"
.ti -1c
.RI "\fBmoeoElitistReplacement\fP< MOEOT > \fBreplace\fP"
.br
.RI "\fIelitist replacement \fP"
.ti -1c
.RI "\fBeoSGAGenOp\fP< MOEOT > \fBdefaultSGAGenOp\fP"
.br
.RI "\fIan object for genetic operators (used as default) \fP"
.ti -1c
.RI "\fBeoGeneralBreeder\fP< MOEOT > \fBgenBreed\fP"
.br
.RI "\fIgeneral breeder \fP"
.ti -1c
.RI "\fBeoBreed\fP< MOEOT > & \fBbreed\fP"
.br
.RI "\fIbreeder \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoNSGAII< MOEOT >"
NSGA-II (Non-dominated Sorting Genetic Algorithm II) as described in: Deb, K., S. 

Agrawal, A. Pratap, and T. Meyarivan : 'A fast elitist non-dominated sorting genetic algorithm for multi-objective optimization: NSGA-II'. In IEEE Transactions on Evolutionary Computation, Vol. 6, No 2, pp 182-197 (April 2002). This class builds the NSGA-II algorithm only by using the fine-grained components of the ParadisEO-MOEO framework. 
.PP
Definition at line 60 of file moeoNSGAII.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class MOEOT> \fBmoeoNSGAII\fP< MOEOT >::\fBmoeoNSGAII\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoGenOp\fP< MOEOT > & _op)\fC [inline]\fP"
.PP
Simple ctor with a \fBeoGenOp\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_maxGen\fP number of generations before stopping 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.RE
.PP

.PP
Definition at line 70 of file moeoNSGAII.h.
.SS "template<class MOEOT> \fBmoeoNSGAII\fP< MOEOT >::\fBmoeoNSGAII\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoTransform\fP< MOEOT > & _op)\fC [inline]\fP"
.PP
Simple ctor with a \fBeoTransform\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_maxGen\fP number of generations before stopping 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.RE
.PP

.PP
Definition at line 82 of file moeoNSGAII.h.
.SS "template<class MOEOT> \fBmoeoNSGAII\fP< MOEOT >::\fBmoeoNSGAII\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoQuadOp\fP< MOEOT > & _crossover, double _pCross, \fBeoMonOp\fP< MOEOT > & _mutation, double _pMut)\fC [inline]\fP"
.PP
Ctor with a crossover, a mutation and their corresponding rates. 
.PP
\fBParameters:\fP
.RS 4
\fI_maxGen\fP number of generations before stopping 
.br
\fI_eval\fP evaluation function 
.br
\fI_crossover\fP crossover 
.br
\fI_pCross\fP crossover probability 
.br
\fI_mutation\fP mutation 
.br
\fI_pMut\fP mutation probability 
.RE
.PP

.PP
Definition at line 97 of file moeoNSGAII.h.
.SS "template<class MOEOT> \fBmoeoNSGAII\fP< MOEOT >::\fBmoeoNSGAII\fP (\fBeoContinue\fP< MOEOT > & _continuator, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoGenOp\fP< MOEOT > & _op)\fC [inline]\fP"
.PP
Ctor with a continuator (instead of _maxGen) and a \fBeoGenOp\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_continuator\fP stopping criteria 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.RE
.PP

.PP
Definition at line 110 of file moeoNSGAII.h.
.SS "template<class MOEOT> \fBmoeoNSGAII\fP< MOEOT >::\fBmoeoNSGAII\fP (\fBeoContinue\fP< MOEOT > & _continuator, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoTransform\fP< MOEOT > & _op)\fC [inline]\fP"
.PP
Ctor with a continuator (instead of _maxGen) and a \fBeoTransform\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_continuator\fP stopping criteria 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.RE
.PP

.PP
Definition at line 122 of file moeoNSGAII.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> virtual void \fBmoeoNSGAII\fP< MOEOT >::operator() (\fBeoPop\fP< MOEOT > & _pop)\fC [inline, virtual]\fP"
.PP
Apply a few generation of evolution to the population _pop until the stopping criteria is verified. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.RE
.PP

.PP
Definition at line 132 of file moeoNSGAII.h.
.PP
References moeoNSGAII< MOEOT >::breed, moeoNSGAII< MOEOT >::continuator, moeoNSGAII< MOEOT >::diversityAssignment, moeoNSGAII< MOEOT >::fitnessAssignment, moeoNSGAII< MOEOT >::popEval, and moeoNSGAII< MOEOT >::replace.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
