.TH "moeoRouletteSelect" 3 "11 Oct 2007" "Version 1.0" "ParadisEO-MOEO:MultiObjectiveEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoRouletteSelect \- Selection strategy that selects ONE individual by using roulette wheel process.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoRouletteSelect.h>\fP
.PP
Inherits \fBmoeoSelectOne< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoRouletteSelect\fP (unsigned int _tSize=2)"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "const MOEOT & \fBoperator()\fP (const \fBeoPop\fP< MOEOT > &_pop)"
.br
.RI "\fIApply the tournament to the given population. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double & \fBtSize\fP"
.br
.RI "\fIsize \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoRouletteSelect< MOEOT >"
Selection strategy that selects ONE individual by using roulette wheel process. 

\fBWarning:\fP
.RS 4
This selection only uses fitness values (and not diversity values). 
.RE
.PP

.PP
Definition at line 49 of file moeoRouletteSelect.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class MOEOT> \fBmoeoRouletteSelect\fP< MOEOT >::\fBmoeoRouletteSelect\fP (unsigned int _tSize = \fC2\fP)\fC [inline]\fP"
.PP
Ctor. 
.PP
\fBParameters:\fP
.RS 4
\fI_tSize\fP the number of individuals in the tournament (default: 2) 
.RE
.PP

.PP
Definition at line 57 of file moeoRouletteSelect.h.
.PP
References moeoRouletteSelect< MOEOT >::tSize.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> const MOEOT& \fBmoeoRouletteSelect\fP< MOEOT >::operator() (const \fBeoPop\fP< MOEOT > & _pop)\fC [inline]\fP"
.PP
Apply the tournament to the given population. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.RE
.PP

.PP
Definition at line 73 of file moeoRouletteSelect.h.
.PP
References moeoRouletteSelect< MOEOT >::tSize.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO:MultiObjectiveEvolvingObjects from the source code.
