.TH "moeoVectorVsVectorBinaryMetric" 3 "9 Oct 2007" "Version 1.0" "ParadisEO-MOEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoVectorVsVectorBinaryMetric \- Base class for binary metrics dedicated to the performance comparison between two Pareto sets (two vectors of objective vectors).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoMetric.h>\fP
.PP
Inherits \fBmoeoBinaryMetric< A1, A2, R >< const const std::vector< ObjectiveVector > &, std::vector< ObjectiveVector > &, R >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class ObjectiveVector, class R> class moeoVectorVsVectorBinaryMetric< ObjectiveVector, R >"
Base class for binary metrics dedicated to the performance comparison between two Pareto sets (two vectors of objective vectors). 
.PP
Definition at line 89 of file moeoMetric.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEOMovingObjects from the source code.
