.TH "moeoMetric" 3 "2 Oct 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoMetric \- Base class for performance metrics (also known as quality indicators).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoMetric.h>\fP
.PP
Inherits \fBeoFunctorBase\fP.
.PP
Inherited by \fBmoeoBinaryMetric< A1, A2, R >\fP, \fBmoeoBinaryMetric< const const ObjectiveVector &, ObjectiveVector &, double >\fP, \fBmoeoBinaryMetric< const const ObjectiveVector &, ObjectiveVector &, R >\fP, \fBmoeoBinaryMetric< const const std::vector< ObjectiveVector > &, std::vector< ObjectiveVector > &, double >\fP, \fBmoeoBinaryMetric< const const std::vector< ObjectiveVector > &, std::vector< ObjectiveVector > &, R >\fP, \fBmoeoUnaryMetric< A, R >\fP, \fBmoeoUnaryMetric< const ObjectiveVector &, R >\fP, and \fBmoeoUnaryMetric< const std::vector< ObjectiveVector > &, R >\fP.
.PP
.SH "Detailed Description"
.PP 
Base class for performance metrics (also known as quality indicators). 
.PP
Definition at line 45 of file moeoMetric.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
