.TH "moeoEasyEA::eoDummyTransform" 3 "2 Oct 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoEasyEA::eoDummyTransform \- a dummy transform  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoEasyEA.h>\fP
.PP
Inherits \fBeoTransform< MOEOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< MOEOT > &)"
.br
.RI "\fIthe dummy functor \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoEasyEA< MOEOT >::eoDummyTransform"
a dummy transform 
.PP
Definition at line 231 of file moeoEasyEA.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
