.TH "moeoAlgo" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoAlgo \- Abstract class for multi-objective algorithms.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoAlgo.h>\fP
.PP
Inherited by \fBmoeoEA< MOEOT >\fP, \fBmoeoLS< MOEOT, Type >\fP, \fBmoeoLS< MOEOT, eoPop< MOEOT > & >\fP, and \fBmoeoLS< MOEOT, MOEOT >\fP.
.PP
.SH "Detailed Description"
.PP 
Abstract class for multi-objective algorithms. 
.PP
Definition at line 19 of file moeoAlgo.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEOMovingObjects from the source code.
