.TH "moeoAlgo" 3 "2 Oct 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoAlgo \- Abstract class for multi-objective algorithms.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoAlgo.h>\fP
.PP
Inherited by \fBmoeoEA< MOEOT >\fP, \fBmoeoLS< MOEOT, Type >\fP, and \fBmoeoLS< MOEOT, MOEOT >\fP.
.PP
.SH "Detailed Description"
.PP 
Abstract class for multi-objective algorithms. 
.PP
Definition at line 42 of file moeoAlgo.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
