.TH "moeoUnaryIndicatorBasedFitnessAssignment" 3 "6 Jul 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoUnaryIndicatorBasedFitnessAssignment \- \fBmoeoIndicatorBasedFitnessAssignment\fP for unary indicators.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoUnaryIndicatorBasedFitnessAssignment.h>\fP
.PP
Inherits \fBmoeoIndicatorBasedFitnessAssignment< MOEOT >< MOEOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoUnaryIndicatorBasedFitnessAssignment< MOEOT >"
\fBmoeoIndicatorBasedFitnessAssignment\fP for unary indicators. 
.PP
Definition at line 22 of file moeoUnaryIndicatorBasedFitnessAssignment.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
