.TH "moeoDistance" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoDistance \- The base class for distance computation.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoDistance.h>\fP
.PP
Inherits \fBeoBF< A1, A2, R >< const const MOEOT &, MOEOT &, Type >\fP.
.PP
Inherited by \fBmoeoNormalizedDistance< MOEOT, Type >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBsetup\fP (const \fBeoPop\fP< MOEOT > &_pop)"
.br
.RI "\fINothing to do. \fP"
.ti -1c
.RI "virtual void \fBsetup\fP (double _min, double _max, unsigned int _obj)"
.br
.RI "\fINothing to do. \fP"
.ti -1c
.RI "virtual void \fBsetup\fP (\fBeoRealInterval\fP _realInterval, unsigned int _obj)"
.br
.RI "\fINothing to do. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT, class Type> class moeoDistance< MOEOT, Type >"
The base class for distance computation. 
.PP
Definition at line 47 of file moeoDistance.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT, class Type> virtual void \fBmoeoDistance\fP< MOEOT, Type >::setup (const \fBeoPop\fP< MOEOT > & _pop)\fC [inline, virtual]\fP"
.PP
Nothing to do. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.RE
.PP

.PP
Reimplemented in \fBmoeoNormalizedDistance< MOEOT, Type >\fP, and \fBmoeoNormalizedDistance< MOEOT >\fP.
.PP
Definition at line 55 of file moeoDistance.h.
.SS "template<class MOEOT, class Type> virtual void \fBmoeoDistance\fP< MOEOT, Type >::setup (double _min, double _max, unsigned int _obj)\fC [inline, virtual]\fP"
.PP
Nothing to do. 
.PP
\fBParameters:\fP
.RS 4
\fI_min\fP lower bound 
.br
\fI_max\fP upper bound 
.br
\fI_obj\fP the objective index 
.RE
.PP

.PP
Reimplemented in \fBmoeoNormalizedDistance< MOEOT, Type >\fP, and \fBmoeoNormalizedDistance< MOEOT >\fP.
.PP
Definition at line 65 of file moeoDistance.h.
.SS "template<class MOEOT, class Type> virtual void \fBmoeoDistance\fP< MOEOT, Type >::setup (\fBeoRealInterval\fP _realInterval, unsigned int _obj)\fC [inline, virtual]\fP"
.PP
Nothing to do. 
.PP
\fBParameters:\fP
.RS 4
\fI_realInterval\fP the \fBeoRealInterval\fP object 
.br
\fI_obj\fP the objective index 
.RE
.PP

.PP
Reimplemented in \fBmoeoNormalizedDistance< MOEOT, Type >\fP, and \fBmoeoNormalizedDistance< MOEOT >\fP.
.PP
Definition at line 74 of file moeoDistance.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEOMovingObjects from the source code.
