.TH "moeoAdditiveEpsilonBinaryMetric" 3 "2 Oct 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoAdditiveEpsilonBinaryMetric \- Additive epsilon binary metric allowing to compare two objective vectors as proposed in Zitzler E., Thiele L., Laumanns M., Fonseca C.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoAdditiveEpsilonBinaryMetric.h>\fP
.PP
Inherits \fBmoeoNormalizedSolutionVsSolutionBinaryMetric< ObjectiveVector, double >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBoperator()\fP (const ObjectiveVector &_o1, const ObjectiveVector &_o2)"
.br
.RI "\fIReturns the minimal distance by which the objective vector _o1 must be translated in all objectives so that it weakly dominates the objective vector _o2. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "double \fBepsilon\fP (const ObjectiveVector &_o1, const ObjectiveVector &_o2, const unsigned int _obj)"
.br
.RI "\fIReturns the epsilon value by which the objective vector _o1 must be translated in the objective _obj so that it dominates the objective vector _o2. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ObjectiveVector> class moeoAdditiveEpsilonBinaryMetric< ObjectiveVector >"
Additive epsilon binary metric allowing to compare two objective vectors as proposed in Zitzler E., Thiele L., Laumanns M., Fonseca C. 

M., Grunert da Fonseca V.: Performance Assessment of Multiobjective Optimizers: An Analysis and Review. IEEE Transactions on Evolutionary Computation 7(2), pp.117–132 (2003). 
.PP
Definition at line 47 of file moeoAdditiveEpsilonBinaryMetric.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class ObjectiveVector> double \fBmoeoAdditiveEpsilonBinaryMetric\fP< ObjectiveVector >::operator() (const ObjectiveVector & _o1, const ObjectiveVector & _o2)\fC [inline]\fP"
.PP
Returns the minimal distance by which the objective vector _o1 must be translated in all objectives so that it weakly dominates the objective vector _o2. 
.PP
\fBWarning:\fP
.RS 4
don't forget to set the bounds for every objective before the call of this function 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI_o1\fP the first objective vector 
.br
\fI_o2\fP the second objective vector 
.RE
.PP

.PP
Definition at line 58 of file moeoAdditiveEpsilonBinaryMetric.h.
.PP
References moeoAdditiveEpsilonBinaryMetric< ObjectiveVector >::epsilon().
.SS "template<class ObjectiveVector> double \fBmoeoAdditiveEpsilonBinaryMetric\fP< ObjectiveVector >::epsilon (const ObjectiveVector & _o1, const ObjectiveVector & _o2, const unsigned int _obj)\fC [inline, private]\fP"
.PP
Returns the epsilon value by which the objective vector _o1 must be translated in the objective _obj so that it dominates the objective vector _o2. 
.PP
\fBParameters:\fP
.RS 4
\fI_o1\fP the first objective vector 
.br
\fI_o2\fP the second objective vector 
.br
\fI_obj\fP the index of the objective 
.RE
.PP

.PP
Definition at line 87 of file moeoAdditiveEpsilonBinaryMetric.h.
.PP
References moeoNormalizedSolutionVsSolutionBinaryMetric< ObjectiveVector, double >::bounds.
.PP
Referenced by moeoAdditiveEpsilonBinaryMetric< ObjectiveVector >::operator()().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
