.TH "moeoFrontByFrontSharingDiversityAssignment" 3 "2 Oct 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoFrontByFrontSharingDiversityAssignment \- Sharing assignment scheme on the way it is used in NSGA.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoFrontByFrontSharingDiversityAssignment.h>\fP
.PP
Inherits \fBmoeoSharingDiversityAssignment< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef MOEOT::ObjectiveVector \fBObjectiveVector\fP"
.br
.RI "\fIthe objective vector type of the solutions \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoFrontByFrontSharingDiversityAssignment\fP (\fBmoeoDistance\fP< MOEOT, double > &_distance, double _nicheSize=0.5, double _alpha=2.0)"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "\fBmoeoFrontByFrontSharingDiversityAssignment\fP (double _nicheSize=0.5, double _alpha=2.0)"
.br
.RI "\fICtor with an euclidean distance (with normalized objective values) in the objective space is used as default. \fP"
.ti -1c
.RI "void \fBupdateByDeleting\fP (\fBeoPop\fP< MOEOT > &_pop, \fBObjectiveVector\fP &_objVec)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetSimilarities\fP (\fBeoPop\fP< MOEOT > &_pop)"
.br
.RI "\fISets similarities FRONT BY FRONT for every solution contained in the population _pop. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoFrontByFrontSharingDiversityAssignment< MOEOT >"
Sharing assignment scheme on the way it is used in NSGA. 
.PP
Definition at line 45 of file moeoFrontByFrontSharingDiversityAssignment.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class MOEOT> \fBmoeoFrontByFrontSharingDiversityAssignment\fP< MOEOT >::\fBmoeoFrontByFrontSharingDiversityAssignment\fP (\fBmoeoDistance\fP< MOEOT, double > & _distance, double _nicheSize = \fC0.5\fP, double _alpha = \fC2.0\fP)\fC [inline]\fP"
.PP
Ctor. 
.PP
\fBParameters:\fP
.RS 4
\fI_distance\fP the distance used to compute the neighborhood of solutions (can be related to the decision space or the objective space) 
.br
\fI_nicheSize\fP neighborhood size in terms of radius distance (closely related to the way the distances are computed) 
.br
\fI_alpha\fP parameter used to regulate the shape of the sharing function 
.RE
.PP

.PP
Definition at line 59 of file moeoFrontByFrontSharingDiversityAssignment.h.
.SS "template<class MOEOT> \fBmoeoFrontByFrontSharingDiversityAssignment\fP< MOEOT >::\fBmoeoFrontByFrontSharingDiversityAssignment\fP (double _nicheSize = \fC0.5\fP, double _alpha = \fC2.0\fP)\fC [inline]\fP"
.PP
Ctor with an euclidean distance (with normalized objective values) in the objective space is used as default. 
.PP
\fBParameters:\fP
.RS 4
\fI_nicheSize\fP neighborhood size in terms of radius distance (closely related to the way the distances are computed) 
.br
\fI_alpha\fP parameter used to regulate the shape of the sharing function 
.RE
.PP

.PP
Definition at line 68 of file moeoFrontByFrontSharingDiversityAssignment.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> void \fBmoeoFrontByFrontSharingDiversityAssignment\fP< MOEOT >::updateByDeleting (\fBeoPop\fP< MOEOT > & _pop, \fBObjectiveVector\fP & _objVec)\fC [inline, virtual]\fP"
.PP
\fBWarning:\fP
.RS 4
NOT IMPLEMENTED, DO NOTHING ! Updates the diversity values of the whole population _pop by taking the deletion of the objective vector _objVec into account. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.br
\fI_objVec\fP the objective vector 
.RE
.PP
\fBWarning:\fP
.RS 4
NOT IMPLEMENTED, DO NOTHING ! 
.RE
.PP

.PP
Reimplemented from \fBmoeoSharingDiversityAssignment< MOEOT >\fP.
.PP
Definition at line 79 of file moeoFrontByFrontSharingDiversityAssignment.h.
.SS "template<class MOEOT> void \fBmoeoFrontByFrontSharingDiversityAssignment\fP< MOEOT >::setSimilarities (\fBeoPop\fP< MOEOT > & _pop)\fC [inline, private, virtual]\fP"
.PP
Sets similarities FRONT BY FRONT for every solution contained in the population _pop. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.RE
.PP

.PP
Reimplemented from \fBmoeoSharingDiversityAssignment< MOEOT >\fP.
.PP
Definition at line 97 of file moeoFrontByFrontSharingDiversityAssignment.h.
.PP
References moeoSharingDiversityAssignment< MOEOT >::distance, moeoSharingDiversityAssignment< MOEOT >::nicheSize, and moeoSharingDiversityAssignment< MOEOT >::sh().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
