.TH "moeoEasyEA::eoDummyEval" 3 "11 Oct 2007" "Version 1.0" "ParadisEO-MOEO:MultiObjectiveEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoEasyEA::eoDummyEval \- a dummy eval  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoEasyEA.h>\fP
.PP
Inherits \fBeoEvalFunc< MOEOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (MOEOT &)"
.br
.RI "\fIthe dummy functor \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoEasyEA< MOEOT >::eoDummyEval"
a dummy eval 
.PP
Definition at line 225 of file moeoEasyEA.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO:MultiObjectiveEvolvingObjects from the source code.
