.TH "moeoDiversityThenFitnessComparator" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoDiversityThenFitnessComparator \- Functor allowing to compare two solutions according to their diversity values, then according to their fitness values.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoDiversityThenFitnessComparator.h>\fP
.PP
Inherits \fBmoeoComparator< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const bool \fBoperator()\fP (const MOEOT &_moeo1, const MOEOT &_moeo2)"
.br
.RI "\fIReturns true if _moeo1 < _moeo2 according to their diversity values, then according to their fitness values. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoDiversityThenFitnessComparator< MOEOT >"
Functor allowing to compare two solutions according to their diversity values, then according to their fitness values. 
.PP
Definition at line 22 of file moeoDiversityThenFitnessComparator.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> const bool \fBmoeoDiversityThenFitnessComparator\fP< MOEOT >::operator() (const MOEOT & _moeo1, const MOEOT & _moeo2)\fC [inline]\fP"
.PP
Returns true if _moeo1 < _moeo2 according to their diversity values, then according to their fitness values. 
.PP
\fBParameters:\fP
.RS 4
\fI_moeo1\fP the first solution 
.br
\fI_moeo2\fP the second solution 
.RE
.PP

.PP
Definition at line 31 of file moeoDiversityThenFitnessComparator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEOMovingObjects from the source code.
