.TH "moeoObjectiveVectorComparator" 3 "9 Oct 2007" "Version 1.0" "ParadisEO-MOEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoObjectiveVectorComparator \- Abstract class allowing to compare 2 objective vectors.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoObjectiveVectorComparator.h>\fP
.PP
Inherits \fBeoBF< A1, A2, R >< const const ObjectiveVector &, ObjectiveVector &, bool >\fP.
.PP
Inherited by \fBmoeoGDominanceObjectiveVectorComparator< ObjectiveVector >\fP, \fBmoeoObjectiveObjectiveVectorComparator< ObjectiveVector >\fP, and \fBmoeoParetoObjectiveVectorComparator< ObjectiveVector >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class ObjectiveVector> class moeoObjectiveVectorComparator< ObjectiveVector >"
Abstract class allowing to compare 2 objective vectors. 

The template argument ObjectiveVector have to be a \fBmoeoObjectiveVector\fP. 
.PP
Definition at line 49 of file moeoObjectiveVectorComparator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEOMovingObjects from the source code.
