.TH "moeoBinaryMetric" 3 "6 Jul 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoBinaryMetric \- Base class for binary metrics.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoMetric.h>\fP
.PP
Inherits \fBeoBF< A1, A2, R >< A1, A2, R >\fP, and \fBmoeoMetric\fP.
.PP
Inherited by \fBmoeoSolutionVsSolutionBinaryMetric< ObjectiveVector, R >\fP, \fBmoeoSolutionVsSolutionBinaryMetric< ObjectiveVector, double >\fP, \fBmoeoVectorVsVectorBinaryMetric< ObjectiveVector, R >\fP, and \fBmoeoVectorVsVectorBinaryMetric< ObjectiveVector, double >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class A1, class A2, class R> class moeoBinaryMetric< A1, A2, R >"
Base class for binary metrics. 
.PP
Definition at line 36 of file moeoMetric.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
