.TH "Sch1ObjectiveVectorTraits" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sch1ObjectiveVectorTraits \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBmoeoObjectiveVectorTraits\fP.
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBminimizing\fP (int i)"
.br
.ti -1c
.RI "static bool \fBmaximizing\fP (int i)"
.br
.ti -1c
.RI "static unsigned int \fBnObjectives\fP ()"
.br
.RI "\fIReturns the number of objectives. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Sch1.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEOMovingObjects from the source code.
