.TH "PartialMappedXover" 3 "22 Dec 2006" "ParadisEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartialMappedXover \- Partial Mapped Crossover.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <partial_mapped_xover.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (Route &__route1, Route &__route2)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBrepair\fP (Route &__route, unsigned __cut1, unsigned __cut2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Partial Mapped Crossover. 
.PP
Definition at line 32 of file partial_mapped_xover.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO from the source code.
