.TH "peoNoAggEvalFunc" 3 "22 Dec 2006" "ParadisEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoNoAggEvalFunc \- The \fBpeoNoAggEvalFunc\fP class does nothing more than an association between a fitness value and a specified individual.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <peoNoAggEvalFunc.h>\fP
.PP
Inherits \fBpeoAggEvalFunc< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (EOT &__sol, const typename EOT::Fitness &__fit)"
.br
.RI "\fIOperator which sets as fitness the \fB__fit\fP value for the \fB__sol\fP individual. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class peoNoAggEvalFunc< EOT >"
The \fBpeoNoAggEvalFunc\fP class does nothing more than an association between a fitness value and a specified individual. 

The class is provided as a mean of declaring that no aggregation is required for the evaluation function - the fitness value is explicitly specified. 
.PP
Definition at line 34 of file peoNoAggEvalFunc.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO from the source code.
