.TH "peoPopEval" 3 "22 Dec 2006" "ParadisEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoPopEval \- The \fB\fBpeoPopEval\fP\fP class provides the interface for constructing ParadisEO specific evaluation functors.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <peoPopEval.h>\fP
.PP
Inherits \fBService\fP.
.PP
Inherited by \fBpeoParaPopEval< EOT >\fP, and \fBpeoSeqPopEval< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBoperator()\fP (eoPop< EOT > &__pop)=0"
.br
.RI "\fIInterface function providing the signature for constructing an evaluation functor. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class peoPopEval< EOT >"
The \fB\fBpeoPopEval\fP\fP class provides the interface for constructing ParadisEO specific evaluation functors. 

The derived classes may be used as wrappers for \fBEO\fP-derived evaluation functors. In order to have an example, please refer to the implementation of the \fB\fBpeoSeqPopEval\fP\fP and \fB\fBpeoParaPopEval\fP\fP classes. 
.PP
Definition at line 34 of file peoPopEval.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO from the source code.
