.TH "peoTransform" 3 "22 Dec 2006" "ParadisEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoTransform \- The \fBpeoTransform\fP class acts only as an interface for creating transform operators - for an example please refer to the \fB\fBpeoSeqTransform\fP\fP and the \fB\fBpeoParaSGATransform\fP\fP classes.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <peoTransform.h>\fP
.PP
Inherits \fBService\fP.
.PP
Inherited by \fBpeoParaSGATransform< EOT >\fP, and \fBpeoSeqTransform< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class peoTransform< EOT >"
The \fBpeoTransform\fP class acts only as an interface for creating transform operators - for an example please refer to the \fB\fBpeoSeqTransform\fP\fP and the \fB\fBpeoParaSGATransform\fP\fP classes. 
.PP
Definition at line 35 of file peoTransform.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO from the source code.
