.TH "TwoOptIncrEval" 3 "22 Dec 2006" "ParadisEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TwoOptIncrEval \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBoperator()\fP (const \fBTwoOpt\fP &__move, const Route &__route)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file two_opt_incr_eval.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO from the source code.
