.TH "moMoveLoopExpl" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-MO-MovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moMoveLoopExpl \- Class which describes an iterative explorer.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moMoveLoopExpl.h>\fP
.PP
Inherits \fBmoMoveExpl< M >< M >\fP.
.PP
Inherited by \fBmoHCMoveLoopExpl< M >\fP, and \fBmoTSMoveLoopExpl< M >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class M> class moMoveLoopExpl< M >"
Class which describes an iterative explorer. 

Only a description... \fBmoHCMoveLoopExpl\fP and \fBmoTSMoveLoopExpl\fP are exemples of class that are a \fBmoMoveLoopExpl\fP. 
.PP
Definition at line 47 of file moMoveLoopExpl.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MO-MovingObjects from the source code.
