.TH "EdgeXover" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EdgeXover \- Edge Crossover.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <edge_xover.h>\fP
.PP
Inherits \fBeoQuadOp< EOType >< eoVector< float, unsigned int > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (\fBRoute\fP &__route1, \fBRoute\fP &__route2)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcross\fP (const \fBRoute\fP &__par1, const \fBRoute\fP &__par2, \fBRoute\fP &__child)"
.br
.ti -1c
.RI "void \fBbuild_map\fP (const \fBRoute\fP &__par1, const \fBRoute\fP &__par2)"
.br
.ti -1c
.RI "void \fBadd_vertex\fP (unsigned int __vertex, \fBRoute\fP &__child)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< std::set< unsigned int > > \fB_map\fP"
.br
.ti -1c
.RI "std::vector< bool > \fBvisited\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Edge Crossover. 
.PP
Definition at line 48 of file edge_xover.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
