.TH "moMove" 3 "11 Oct 2007" "Version 1.0" "ParadisEO-MO:MovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moMove \- Definition of a move.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moMove.h>\fP
.PP
Inherits \fBeoUF< EOT &, void >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT \fBEOType\fP"
.br
.RI "\fIAlias for the type. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class moMove< EOT >"
Definition of a move. 

A move transforms a solution to another close solution. It describes how a solution can be modified to another one. 
.PP
Definition at line 48 of file moMove.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MO:MovingObjects from the source code.
