.TH "OrderXover" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OrderXover \- Order Crossover.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <order_xover.h>\fP
.PP
Inherits \fBeoQuadOp< EOType >< eoVector< float, unsigned int > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (\fBRoute\fP &__route1, \fBRoute\fP &__route2)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcross\fP (const \fBRoute\fP &__par1, const \fBRoute\fP &__par2, \fBRoute\fP &__child)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Order Crossover. 
.PP
Definition at line 45 of file order_xover.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
