.TH "PartTwoOptNext" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartTwoOptNext \- It updates a couple of edges.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <part_two_opt_next.h>\fP
.PP
Inherits \fBmoNextMove< TwoOpt >\fP.
.PP
.SH "Detailed Description"
.PP 
It updates a couple of edges. 
.PP
Definition at line 44 of file part_two_opt_next.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
