.TH "PartialMappedXover" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PartialMappedXover \- Partial Mapped Crossover.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <partial_mapped_xover.h>\fP
.PP
Inherits \fBeoQuadOp< EOType >< eoVector< float, unsigned int > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (\fBRoute\fP &__route1, \fBRoute\fP &__route2)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBrepair\fP (\fBRoute\fP &__route, unsigned __cut1, unsigned __cut2)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Partial Mapped Crossover. 
.PP
Definition at line 45 of file partial_mapped_xover.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
