.TH "RouteInit" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RouteInit \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBeoInit< EOT >< eoVector< float, unsigned int > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (\fBRoute\fP &__route)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file route_init.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
