.TH "TwoOptInit" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TwoOptInit \- It sets the first couple of edges.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <two_opt_init.h>\fP
.PP
Inherits \fBmoMoveInit< TwoOpt >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (\fBTwoOpt\fP &__move, const \fBRoute\fP &__route)"
.br
.in -1c
.SH "Detailed Description"
.PP 
It sets the first couple of edges. 
.PP
Definition at line 45 of file two_opt_init.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
