.TH "TwoOptRand" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TwoOptRand \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBmoRandMove< TwoOpt >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (\fBTwoOpt\fP &__move)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file two_opt_rand.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
