.TH "TwoOpt" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TwoOpt \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBmoMove< EOT >< eoVector< float, unsigned int > >\fP, and \fBeoPersistent\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTwoOpt\fP \fBoperator!\fP () const "
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBRoute\fP &__route)"
.br
.ti -1c
.RI "void \fBreadFrom\fP (std::istream &__is)"
.br
.ti -1c
.RI "void \fBprintOn\fP (std::ostream &__os) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file two_opt.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
