.TH "Algorithm" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Algorithm \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (double &_d)"
.br
.ti -1c
.RI "\fBAlgorithm\fP (\fBpeoPopEval\fP< \fBIndi\fP > &_eval)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBIndi\fP > &_pop)"
.br
.ti -1c
.RI "\fBAlgorithm\fP (\fBeoEvalFunc\fP< \fBIndi\fP > &_eval, \fBeoSelect\fP< \fBIndi\fP > &_select, \fBpeoTransform\fP< \fBIndi\fP > &_transform)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBIndi\fP > &_pop)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBpeoPopEval\fP< \fBIndi\fP > & \fBeval\fP"
.br
.ti -1c
.RI "\fBeoPopLoopEval\fP< \fBIndi\fP > \fBloopEval\fP"
.br
.ti -1c
.RI "\fBeoPopEvalFunc\fP< \fBIndi\fP > & \fBeval\fP"
.br
.ti -1c
.RI "\fBeoSelectTransform\fP< \fBIndi\fP > \fBselectTransform\fP"
.br
.ti -1c
.RI "\fBeoBreed\fP< \fBIndi\fP > & \fBbreed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file t-MultiStart.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
