.TH "continuator" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
continuator \- Abstract class for a continuator within the exchange of data by migration.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <peoData.h>\fP
.PP
Inherited by \fBeoContinuator< EOT >\fP, and \fBeoSyncContinue\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBcheck\fP ()=0"
.br
.RI "\fIVirtual function of check. \fP"
.ti -1c
.RI "virtual \fB~continuator\fP ()"
.br
.RI "\fIVirtual destructor. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Abstract class for a continuator within the exchange of data by migration. 

\fBVersion:\fP
.RS 4
1.0 
.RE
.PP
\fBDate:\fP
.RS 4
january 2008 
.RE
.PP

.PP
Definition at line 51 of file peoData.h.
.SH "Member Function Documentation"
.PP 
.SS "virtual bool continuator::check ()\fC [pure virtual]\fP"
.PP
Virtual function of check. 
.PP
\fBReturns:\fP
.RS 4
true if the algorithm must continue 
.RE
.PP

.PP
Implemented in \fBeoContinuator< EOT >\fP, and \fBeoSyncContinue\fP.
.PP
Referenced by peoAsyncIslandMig< TYPESELECT, TYPEREPLACE >::operator()().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
