.TH "peoMultiStart::FunctionAlgorithm" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoMultiStart::FunctionAlgorithm \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBpeoMultiStart< EntityType >::AbstractAlgorithm\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionAlgorithm\fP (AlgorithmReturnType(*externalAlgorithm)(AlgorithmDataType &))"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBAbstractDataType\fP &dataTypeInstance)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename EntityType>template<typename AlgorithmReturnType, typename AlgorithmDataType> struct peoMultiStart< EntityType >::FunctionAlgorithm< AlgorithmReturnType, AlgorithmDataType >"

.PP
Definition at line 194 of file peoMultiStart.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
