.TH "peoParallelAlgorithmWrapper" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-PEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoParallelAlgorithmWrapper \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBRunner\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename AlgorithmType> \fBpeoParallelAlgorithmWrapper\fP (AlgorithmType &externalAlgorithm)"
.br
.ti -1c
.RI "template<typename AlgorithmType, typename AlgorithmDataType> \fBpeoParallelAlgorithmWrapper\fP (AlgorithmType &externalAlgorithm, AlgorithmDataType &externalData)"
.br
.ti -1c
.RI "\fB~peoParallelAlgorithmWrapper\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBAbstractAlgorithm\fP * \fBalgorithm\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAbstractAlgorithm\fP"
.br
.ti -1c
.RI "struct \fBAlgorithm\fP"
.br
.ti -1c
.RI "struct \fBAlgorithm< AlgorithmType, void >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file peoParallelAlgorithmWrapper.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEOMovingObjects from the source code.
