.TH "peoSynchronousMultiStart::AggregationAlgorithm" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-PEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoSynchronousMultiStart::AggregationAlgorithm \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBpeoSynchronousMultiStart< EntityType >::AbstractAggregationAlgorithm\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAggregationAlgorithm\fP (AggregationAlgorithmType &externalAggregationAlgorithm)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBAbstractDataType\fP &dataTypeInstanceA, \fBAbstractDataType\fP &dataTypeInstanceB)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AggregationAlgorithmType & \fBaggregationAlgorithm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename EntityType>template<typename AggregationAlgorithmType> struct peoSynchronousMultiStart< EntityType >::AggregationAlgorithm< AggregationAlgorithmType >"

.PP
Definition at line 164 of file peoSynchronousMultiStart.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEOMovingObjects from the source code.
