.TH "peoWrapper::FunctionAlgorithm< AlgorithmReturnType, void >" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoWrapper::FunctionAlgorithm< AlgorithmReturnType, void > \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBpeoWrapper::AbstractAlgorithm\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionAlgorithm\fP (AlgorithmReturnType(*externalAlgorithm)())"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename AlgorithmReturnType> struct peoWrapper::FunctionAlgorithm< AlgorithmReturnType, void >"

.PP
Definition at line 153 of file peoWrapper.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
