.TH "peoWrapper::Algorithm" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoWrapper::Algorithm \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBpeoWrapper::AbstractAlgorithm\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlgorithm\fP (AlgorithmType &externalAlgorithm, AlgorithmDataType &externalData)"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AlgorithmType & \fBalgorithm\fP"
.br
.ti -1c
.RI "AlgorithmDataType & \fBalgorithmData\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename AlgorithmType, typename AlgorithmDataType> struct peoWrapper::Algorithm< AlgorithmType, AlgorithmDataType >"

.PP
Definition at line 107 of file peoWrapper.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
