.TH "selector" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
selector \- Abstract class for a selector within the exchange of data by migration.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <peoData.h>\fP
.PP
Inherited by \fBeoSelector< EOT, TYPE >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBoperator()\fP (TYPE &)=0"
.br
.RI "\fIVirtual operator on the template type. \fP"
.ti -1c
.RI "virtual \fB~selector\fP ()"
.br
.RI "\fIVirtual destructor. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class TYPE> class selector< TYPE >"
Abstract class for a selector within the exchange of data by migration. 

\fBVersion:\fP
.RS 4
1.0 
.RE
.PP
\fBDate:\fP
.RS 4
january 2008 
.RE
.PP

.PP
Definition at line 101 of file peoData.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class TYPE> virtual void \fBselector\fP< TYPE >::operator() (TYPE &)\fC [pure virtual]\fP"
.PP
Virtual operator on the template type. 
.PP
\fBParameters:\fP
.RS 4
\fITYPE\fP & 
.RE
.PP

.PP
Implemented in \fBeoSelector< EOT, TYPE >\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
