.TH "SyncCompare" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyncCompare \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const std::pair< std::vector< \fBSyncEntry\fP >, unsigned > &A, const std::pair< std::vector< \fBSyncEntry\fP >, unsigned > &B)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file synchron.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
