.TH "SyncEntry" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyncEntry \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "RUNNER_ID \fBrunner\fP"
.br
.ti -1c
.RI "COOP_ID \fBcoop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file synchron.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
