.TH "Topology" 3 "12 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Topology \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBCompleteTopology\fP, \fBRandomTopology\fP, \fBRingTopology\fP, and \fBStarTopology\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Topology\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (\fBCooperative\fP &__mig)"
.br
.ti -1c
.RI "\fBoperator std::vector\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCooperative\fP * > \fBmig\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file topology.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
