.TH "peoMultiStart::AggregationAlgorithm" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoMultiStart::AggregationAlgorithm \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBpeoMultiStart< EntityType >::AbstractAggregationAlgorithm\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAggregationAlgorithm\fP (AggregationAlgorithmType &externalAggregationAlgorithm)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBAbstractDataType\fP &dataTypeInstanceA, \fBAbstractDataType\fP &dataTypeInstanceB)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AggregationAlgorithmType & \fBaggregationAlgorithm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename EntityType>template<typename AggregationAlgorithmType> struct peoMultiStart< EntityType >::AggregationAlgorithm< AggregationAlgorithmType >"

.PP
Definition at line 213 of file peoMultiStart.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
