.TH "peoWrapper" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoWrapper \- Specific class for wrapping.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <peoWrapper.h>\fP
.PP
Inherits \fBRunner\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename AlgorithmType> \fBpeoWrapper\fP (AlgorithmType &externalAlgorithm)"
.br
.RI "\fIconstructor \fP"
.ti -1c
.RI "template<typename AlgorithmType, typename AlgorithmDataType> \fBpeoWrapper\fP (AlgorithmType &externalAlgorithm, AlgorithmDataType &externalData)"
.br
.RI "\fIconstructor \fP"
.ti -1c
.RI "template<typename AlgorithmReturnType> \fBpeoWrapper\fP (AlgorithmReturnType &(*externalAlgorithm)())"
.br
.RI "\fIconstructor \fP"
.ti -1c
.RI "template<typename AlgorithmReturnType, typename AlgorithmDataType> \fBpeoWrapper\fP (AlgorithmReturnType &(*externalAlgorithm)(AlgorithmDataType &), AlgorithmDataType &externalData)"
.br
.RI "\fIconstructor \fP"
.ti -1c
.RI "\fB~peoWrapper\fP ()"
.br
.RI "\fIdestructor \fP"
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "\fIfunction run \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBAbstractAlgorithm\fP * \fBalgorithm\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBAbstractAlgorithm\fP"
.br
.ti -1c
.RI "struct \fBAlgorithm\fP"
.br
.ti -1c
.RI "struct \fBAlgorithm< AlgorithmType, void >\fP"
.br
.ti -1c
.RI "struct \fBFunctionAlgorithm\fP"
.br
.ti -1c
.RI "struct \fBFunctionAlgorithm< AlgorithmReturnType, void >\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Specific class for wrapping. 

\fBSee also:\fP
.RS 4
\fBRunner\fP 
.RE
.PP
\fBVersion:\fP
.RS 4
1.1 
.RE
.PP
\fBDate:\fP
.RS 4
december 2007 
.RE
.PP

.PP
Definition at line 49 of file peoWrapper.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename AlgorithmType> peoWrapper::peoWrapper (AlgorithmType & externalAlgorithm)\fC [inline]\fP"
.PP
constructor 
.PP
\fBParameters:\fP
.RS 4
\fIAlgorithmType&\fP externalAlgorithm 
.RE
.PP

.PP
Definition at line 56 of file peoWrapper.h.
.SS "template<typename AlgorithmType, typename AlgorithmDataType> peoWrapper::peoWrapper (AlgorithmType & externalAlgorithm, AlgorithmDataType & externalData)\fC [inline]\fP"
.PP
constructor 
.PP
\fBParameters:\fP
.RS 4
\fIAlgorithmType&\fP externalAlgorithm 
.br
\fIAlgorithmDataType&\fP externalData 
.RE
.PP

.PP
Definition at line 63 of file peoWrapper.h.
.SS "template<typename AlgorithmReturnType> peoWrapper::peoWrapper (AlgorithmReturnType &(*)() externalAlgorithm)\fC [inline]\fP"
.PP
constructor 
.PP
\fBParameters:\fP
.RS 4
\fIAlgorithmReturnType&\fP (*externalAlgorithm)() 
.RE
.PP

.PP
Definition at line 69 of file peoWrapper.h.
.SS "template<typename AlgorithmReturnType, typename AlgorithmDataType> peoWrapper::peoWrapper (AlgorithmReturnType &(*)(AlgorithmDataType &) externalAlgorithm, AlgorithmDataType & externalData)\fC [inline]\fP"
.PP
constructor 
.PP
\fBParameters:\fP
.RS 4
\fIAlgorithmReturnType&\fP (*externalAlgorithm)( AlgorithmDataType& ) 
.br
\fIAlgorithmDataType&\fP externalData 
.RE
.PP

.PP
Definition at line 76 of file peoWrapper.h.
.SH "Member Data Documentation"
.PP 
.SS "\fBAbstractAlgorithm\fP* \fBpeoWrapper::algorithm\fP\fC [private]\fP"
.PP
\fBParameters:\fP
.RS 4
\fIAbstractAlgorithm*\fP algorithm 
.RE
.PP

.PP
Definition at line 170 of file peoWrapper.h.
.PP
Referenced by run(), and ~peoWrapper().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
