.TH "peoWrapper::AbstractAlgorithm" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoWrapper::AbstractAlgorithm \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBpeoWrapper::Algorithm< AlgorithmType, AlgorithmDataType >\fP, \fBpeoWrapper::Algorithm< AlgorithmType, void >\fP, \fBpeoWrapper::FunctionAlgorithm< AlgorithmReturnType, AlgorithmDataType >\fP, and \fBpeoWrapper::FunctionAlgorithm< AlgorithmReturnType, void >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~AbstractAlgorithm\fP ()"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 95 of file peoWrapper.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
