.TH "peoWorstPositionReplacement" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoWorstPositionReplacement \- Specific class for a replacement of a population of a PSO.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <peoPSO.h>\fP
.PP
Inherits \fBeoReplacement< POT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpeoWorstPositionReplacement\fP ()"
.br
.RI "\fIconstructor \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< POT > &_dest, \fBeoPop\fP< POT > &_source)"
.br
.RI "\fIoperator \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class POT> class peoWorstPositionReplacement< POT >"
Specific class for a replacement of a population of a PSO. 

\fBSee also:\fP
.RS 4
\fBeoReplacement\fP 
.RE
.PP
\fBVersion:\fP
.RS 4
1.1 
.RE
.PP
\fBDate:\fP
.RS 4
october 2007 
.RE
.PP

.PP
Definition at line 127 of file peoPSO.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class POT> void \fBpeoWorstPositionReplacement\fP< POT >::operator() (\fBeoPop\fP< POT > & _dest, \fBeoPop\fP< POT > & _source)\fC [inline]\fP"
.PP
operator 
.PP
\fBParameters:\fP
.RS 4
\fIeoPop<POT>&\fP _dest 
.br
\fIeoPop<POT>&\fP _source 
.RE
.PP

.PP
Definition at line 137 of file peoPSO.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
