.TH "moCoolSched" 3 "18 Dec 2006" "Version 0.1" "PARADISEO-MO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moCoolSched \- This class gives the description of a cooling schedule.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moCoolSched.h>\fP
.PP
Inherited by \fBmoEasyCoolSched\fP.
.PP
.SH "Detailed Description"
.PP 
This class gives the description of a cooling schedule. 

It is only a description... An object that herits from this class is needed to be used in a \fBmoSA\fP. See \fBmoEasyCoolSched\fP for example. 
.PP
Definition at line 22 of file moCoolSched.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for PARADISEO-MO from the source code.
