.TH "moeoGenerationalReplacement" 3 "17 Apr 2007" "Version 1.0.alpha" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoGenerationalReplacement \- Generational replacement: only the new individuals are preserved.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoGenerationalReplacement.h>\fP
.PP
Inherits \fBmoeoReplacement< MOEOT >< MOEOT >\fP, and \fBeoGenerationalReplacement< MOEOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< MOEOT > &_parents, \fBeoPop\fP< MOEOT > &_offspring)"
.br
.RI "\fISwaps _parents and _offspring. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoGenerationalReplacement< MOEOT >"
Generational replacement: only the new individuals are preserved. 
.PP
Definition at line 23 of file moeoGenerationalReplacement.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> void \fBmoeoGenerationalReplacement\fP< MOEOT >::operator() (\fBeoPop\fP< MOEOT > & _parents, \fBeoPop\fP< MOEOT > & _offspring)\fC [inline]\fP"
.PP
Swaps _parents and _offspring. 
.PP
\fBParameters:\fP
.RS 4
\fI_parents\fP the parents population 
.br
\fI_offspring\fP the offspring population 
.RE
.PP

.PP
Reimplemented from \fBeoGenerationalReplacement< MOEOT >\fP.
.PP
Definition at line 32 of file moeoGenerationalReplacement.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
