.TH "moeoObjectiveVectorTraits" 3 "17 Apr 2007" "Version 1.0.alpha" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoObjectiveVectorTraits \- A traits class for \fBmoeoObjectiveVector\fP to specify the number of objectives and which ones have to be minimized or maximized.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoObjectiveVectorTraits.h>\fP
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetup\fP (unsigned _nObjectives, std::vector< bool > &_bObjectives)"
.br
.RI "\fIParameters setting. \fP"
.ti -1c
.RI "static unsigned \fBnObjectives\fP ()"
.br
.RI "\fIReturns the number of objectives. \fP"
.ti -1c
.RI "static bool \fBminimizing\fP (unsigned _i)"
.br
.RI "\fIReturns true if the _ith objective have to be minimized. \fP"
.ti -1c
.RI "static bool \fBmaximizing\fP (unsigned _i)"
.br
.RI "\fIReturns true if the _ith objective have to be maximized. \fP"
.ti -1c
.RI "static double \fBtolerance\fP ()"
.br
.RI "\fIReturns the tolerance value (to compare solutions). \fP"
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static unsigned \fBnObj\fP"
.br
.RI "\fIThe number of objectives. \fP"
.ti -1c
.RI "static std::vector< bool > \fBbObj\fP"
.br
.RI "\fIThe min/max vector. \fP"
.in -1c
.SH "Detailed Description"
.PP 
A traits class for \fBmoeoObjectiveVector\fP to specify the number of objectives and which ones have to be minimized or maximized. 
.PP
Definition at line 23 of file moeoObjectiveVectorTraits.h.
.SH "Member Function Documentation"
.PP 
.SS "static void moeoObjectiveVectorTraits::setup (unsigned _nObjectives, std::vector< bool > & _bObjectives)\fC [inline, static]\fP"
.PP
Parameters setting. 
.PP
\fBParameters:\fP
.RS 4
\fI_nObjectives\fP the number of objectives 
.br
\fI_bObjectives\fP the min/max vector (true = min / false = max) 
.RE
.PP

.PP
Definition at line 32 of file moeoObjectiveVectorTraits.h.
.PP
References bObj, and nObj.
.SS "static bool moeoObjectiveVectorTraits::minimizing (unsigned _i)\fC [inline, static]\fP"
.PP
Returns true if the _ith objective have to be minimized. 
.PP
\fBParameters:\fP
.RS 4
\fI_i\fP the index 
.RE
.PP

.PP
Definition at line 65 of file moeoObjectiveVectorTraits.h.
.PP
References bObj.
.PP
Referenced by maximizing().
.SS "static bool moeoObjectiveVectorTraits::maximizing (unsigned _i)\fC [inline, static]\fP"
.PP
Returns true if the _ith objective have to be maximized. 
.PP
\fBParameters:\fP
.RS 4
\fI_i\fP the index 
.RE
.PP

.PP
Definition at line 77 of file moeoObjectiveVectorTraits.h.
.PP
References minimizing().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
