moeoGDominanceObjectiveVectorComparator< ObjectiveVector > Class Template Reference
This functor class allows to compare 2 objective vectors according to g-dominance.
#include <moeoGDominanceObjectiveVectorComparator.h>
Public Member Functions
moeoGDominanceObjectiveVectorComparator (ObjectiveVector &_ref)
Ctor.
const bool operator() (const ObjectiveVector &_objectiveVector1, const ObjectiveVector &_objectiveVector2)
Returns true if _objectiveVector1 is g-dominated by _objectiveVector2.
Private Member Functions
unsigned int flag (const ObjectiveVector &_objectiveVector)
Returns the flag of _objectiveVector according to the reference point.
Private Attributes
ObjectiveVector & ref
the reference point
moeoParetoObjectiveVectorComparator< ObjectiveVector > paretoComparator
Pareto comparator.
Detailed Description
template<class ObjectiveVector> class moeoGDominanceObjectiveVectorComparator< ObjectiveVector >
This functor class allows to compare 2 objective vectors according to g-dominance.
The concept of g-dominance as been introduced in: J. Molina, L. V. Santana, A. G. Hernandez-Diaz, C. A. Coello Coello, R. Caballero, `g-dominance: Reference point based dominance` (2007)
Definition at line 48 of file moeoGDominanceObjectiveVectorComparator.h.
Constructor & Destructor Documentation
template<class ObjectiveVector> moeoGDominanceObjectiveVectorComparator< ObjectiveVector >::moeoGDominanceObjectiveVectorComparator (ObjectiveVector & _ref) [inline]
Ctor.
Parameters:
_ref the reference point
Definition at line 56 of file moeoGDominanceObjectiveVectorComparator.h.
Member Function Documentation
template<class ObjectiveVector> const bool moeoGDominanceObjectiveVectorComparator< ObjectiveVector >::operator() (const ObjectiveVector & _objectiveVector1, const ObjectiveVector & _objectiveVector2) [inline]
Returns true if _objectiveVector1 is g-dominated by _objectiveVector2.
Parameters:
_objectiveVector1 the first objective vector
_objectiveVector2 the second objective vector
Definition at line 65 of file moeoGDominanceObjectiveVectorComparator.h.
References moeoGDominanceObjectiveVectorComparator< ObjectiveVector >::flag(), and moeoGDominanceObjectiveVectorComparator< ObjectiveVector >::paretoComparator.
template<class ObjectiveVector> unsigned int moeoGDominanceObjectiveVectorComparator< ObjectiveVector >::flag (const ObjectiveVector & _objectiveVector) [inline, private]
Returns the flag of _objectiveVector according to the reference point.
Parameters:
_objectiveVector the first objective vector
Definition at line 99 of file moeoGDominanceObjectiveVectorComparator.h.
References moeoGDominanceObjectiveVectorComparator< ObjectiveVector >::ref.
Referenced by moeoGDominanceObjectiveVectorComparator< ObjectiveVector >::operator()().
The documentation for this class was generated from the following file:
moeoGDominanceObjectiveVectorComparator.h