.TH "moLSCheckPoint" 3 "29 Feb 2008" "Version 1.1" "ParadisEO-MO-MovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moLSCheckPoint \- Class which allows a checkpointing system.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moLSCheckPoint.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (const M &_move, const typename M::EOType &_solution)"
.br
.RI "\fIFunction which launches the checkpointing. \fP"
.ti -1c
.RI "void \fBadd\fP (eoBF< const M &, const typename M::EOType &, void > &_function)"
.br
.RI "\fIProcedure which add a new function to the function vector. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< eoBF< const M &, const typename M::EOType &, void > * > \fBfunctions\fP"
.br
.RI "\fIVector of functions. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class M> class moLSCheckPoint< M >"
Class which allows a checkpointing system. 

Thanks to this class, at each iteration, additionnal function can be used (and not only one). 
.PP
Definition at line 46 of file moLSCheckPoint.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class M> void \fBmoLSCheckPoint\fP< M >::operator() (const M & _move, const typename M::EOType & _solution)\fC [inline]\fP"
.PP
Function which launches the checkpointing. 
.PP
Each saved function is used on the current move and the current solution.
.PP
\fBParameters:\fP
.RS 4
\fI_move\fP a move. 
.br
\fI_solution\fP a solution. 
.RE
.PP

.PP
Definition at line 57 of file moLSCheckPoint.h.
.PP
References moLSCheckPoint< M >::functions.
.SS "template<class M> void \fBmoLSCheckPoint\fP< M >::add (eoBF< const M &, const typename M::EOType &, void > & _function)\fC [inline]\fP"
.PP
Procedure which add a new function to the function vector. 
.PP
The new function is added at the end of the vector. 
.PP
\fBParameters:\fP
.RS 4
\fI_function\fP a new function to add. 
.RE
.PP

.PP
Definition at line 72 of file moLSCheckPoint.h.
.PP
References moLSCheckPoint< M >::functions.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MO-MovingObjects from the source code.
