.TH "moSolContinue" 3 "3 Mar 2008" "Version 1.1" "ParadisEO-MO-MovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moSolContinue \- Class that describes a stop criterion for a solution-based heuristic.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moSolContinue.h>\fP
.PP
Inherits \fBeoUF< const EOT &, bool >\fP.
.PP
Inherited by \fBmoFitSolContinue< EOT >\fP, \fBmoGenSolContinue< EOT >\fP, \fBmoNoFitImprSolContinue< EOT >\fP, and \fBmoSteadyFitSolContinue< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinit\fP ()=0"
.br
.RI "\fIProcedure which initialises all that the stop criterion needs. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class moSolContinue< EOT >"
Class that describes a stop criterion for a solution-based heuristic. 

It allows to add an initialisation procedure to an object that is a unary function (\fBeoUF\fP). 
.PP
Definition at line 48 of file moSolContinue.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT> virtual void \fBmoSolContinue\fP< EOT >::init ()\fC [pure virtual]\fP"
.PP
Procedure which initialises all that the stop criterion needs. 
.PP
Generally, it allocates some data structures or initialises some counters. 
.PP
Implemented in \fBmoFitSolContinue< EOT >\fP, \fBmoGenSolContinue< EOT >\fP, \fBmoNoFitImprSolContinue< EOT >\fP, and \fBmoSteadyFitSolContinue< EOT >\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MO-MovingObjects from the source code.
