.TH "moeoEntropyMetric" 3 "16 Jan 2007" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoEntropyMetric \- The entropy gives an idea of the diversity of a Pareto set relatively to another Pareto set.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoEntropyMetric.h>\fP
.PP
Inherits \fBmoeoVectorVsVectorBM< EOT, double >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::Fitness \fBEOFitness\fP"
.br
.RI "\fIThe fitness type of a solution. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBoperator()\fP (const std::vector< \fBEOFitness\fP > &_set1, const std::vector< \fBEOFitness\fP > &_set2)"
.br
.RI "\fIReturns the entropy of the Pareto set '_set1' relatively to the Pareto set '_set2'. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBremoveDominated\fP (std::vector< \fBEOFitness\fP > &_f)"
.br
.ti -1c
.RI "void \fBprenormalize\fP (const std::vector< \fBEOFitness\fP > &_f)"
.br
.ti -1c
.RI "void \fBnormalize\fP (std::vector< \fBEOFitness\fP > &_f)"
.br
.ti -1c
.RI "void \fBcomputeUnion\fP (const std::vector< \fBEOFitness\fP > &_f1, const std::vector< \fBEOFitness\fP > &_f2, std::vector< \fBEOFitness\fP > &_f)"
.br
.ti -1c
.RI "unsigned \fBhowManyInNicheOf\fP (const std::vector< \fBEOFitness\fP > &_f, const \fBEOFitness\fP &_s, unsigned _size)"
.br
.ti -1c
.RI "double \fBeuclidianDistance\fP (const \fBEOFitness\fP &_set1, const \fBEOFitness\fP &_to, unsigned _deg=2)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< double > \fBvect_min_val\fP"
.br
.ti -1c
.RI "std::vector< double > \fBvect_max_val\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class moeoEntropyMetric< EOT >"
The entropy gives an idea of the diversity of a Pareto set relatively to another Pareto set. 

(Basseur, Seynhaeve, Talbi: 'Design of Multi-objective Evolutionary Algorithms: Application to the Flow-shop Scheduling Problem', in Proc. of the 2002 Congress on Evolutionary Computation, IEEE Press, pp. 1155-1156) 
.PP
Definition at line 23 of file moeoEntropyMetric.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT> double \fBmoeoEntropyMetric\fP< EOT >::operator() (const std::vector< \fBEOFitness\fP > & _set1, const std::vector< \fBEOFitness\fP > & _set2)\fC [inline]\fP"
.PP
Returns the entropy of the Pareto set '_set1' relatively to the Pareto set '_set2'. 
.PP
\fBParameters:\fP
.RS 4
\fI_set1\fP the first Pareto set 
.br
\fI_set2\fP the second Pareto set 
.RE
.PP

.PP
Definition at line 38 of file moeoEntropyMetric.h.
.PP
References moeoEntropyMetric< EOT >::computeUnion(), moeoEntropyMetric< EOT >::howManyInNicheOf(), moeoEntropyMetric< EOT >::normalize(), moeoEntropyMetric< EOT >::prenormalize(), and moeoEntropyMetric< EOT >::removeDominated().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
