.TH "moeoNSGA" 3 "26 Jun 2007" "Version 1.0" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoNSGA \- NSGA (Non-dominated Sorting Genetic Algorithm) as described in: N.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoNSGA.h>\fP
.PP
Inherits \fBmoeoEA< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoNSGA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoGenOp\fP< MOEOT > &_op, double _nicheSize=0.5)"
.br
.RI "\fISimple ctor with a \fBeoGenOp\fP. \fP"
.ti -1c
.RI "\fBmoeoNSGA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoTransform\fP< MOEOT > &_op, double _nicheSize=0.5)"
.br
.RI "\fISimple ctor with a \fBeoTransform\fP. \fP"
.ti -1c
.RI "\fBmoeoNSGA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoQuadOp\fP< MOEOT > &_crossover, double _pCross, \fBeoMonOp\fP< MOEOT > &_mutation, double _pMut, double _nicheSize=0.5)"
.br
.RI "\fICtor with a crossover, a mutation and their corresponding rates. \fP"
.ti -1c
.RI "\fBmoeoNSGA\fP (\fBeoContinue\fP< MOEOT > &_continuator, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoGenOp\fP< MOEOT > &_op, double _nicheSize=0.5)"
.br
.RI "\fICtor with a continuator (instead of _maxGen) and a \fBeoGenOp\fP. \fP"
.ti -1c
.RI "\fBmoeoNSGA\fP (\fBeoContinue\fP< MOEOT > &_continuator, \fBeoEvalFunc\fP< MOEOT > &_eval, \fBeoTransform\fP< MOEOT > &_op, double _nicheSize=0.5)"
.br
.RI "\fICtor with a continuator (instead of _maxGen) and a \fBeoTransform\fP. \fP"
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBeoPop\fP< MOEOT > &_pop)"
.br
.RI "\fIApply a few generation of evolution to the population _pop until the stopping criteria is verified. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBeoGenContinue\fP< MOEOT > \fBdefaultGenContinuator\fP"
.br
.RI "\fIa continuator based on the number of generations (used as default) \fP"
.ti -1c
.RI "\fBeoContinue\fP< MOEOT > & \fBcontinuator\fP"
.br
.RI "\fIstopping criteria \fP"
.ti -1c
.RI "\fBeoPopLoopEval\fP< MOEOT > \fBpopEval\fP"
.br
.RI "\fIevaluation function used to evaluate the whole population \fP"
.ti -1c
.RI "\fBmoeoDetTournamentSelect\fP< MOEOT > \fBselect\fP"
.br
.RI "\fIbinary tournament selection \fP"
.ti -1c
.RI "\fBmoeoFastNonDominatedSortingFitnessAssignment\fP< MOEOT > \fBfitnessAssignment\fP"
.br
.RI "\fIfitness assignment used in NSGA-II \fP"
.ti -1c
.RI "\fBmoeoFrontByFrontSharingDiversityAssignment\fP< MOEOT > \fBdiversityAssignment\fP"
.br
.RI "\fIdiversity assignment used in NSGA-II \fP"
.ti -1c
.RI "\fBmoeoElitistReplacement\fP< MOEOT > \fBreplace\fP"
.br
.RI "\fIelitist replacement \fP"
.ti -1c
.RI "\fBeoSGAGenOp\fP< MOEOT > \fBdefaultSGAGenOp\fP"
.br
.RI "\fIan object for genetic operators (used as default) \fP"
.ti -1c
.RI "\fBeoGeneralBreeder\fP< MOEOT > \fBgenBreed\fP"
.br
.RI "\fIgeneral breeder \fP"
.ti -1c
.RI "\fBeoBreed\fP< MOEOT > & \fBbreed\fP"
.br
.RI "\fIbreeder \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoNSGA< MOEOT >"
NSGA (Non-dominated Sorting Genetic Algorithm) as described in: N. 

Srinivas, K. Deb, 'Multiobjective Optimization Using Nondominated Sorting in Genetic Algorithms'. Evolutionary Computation, Vol. 2(3), No 2, pp. 221-248 (1994). This class builds the NSGA algorithm only by using the fine-grained components of the ParadisEO-MOEO framework. 
.PP
Definition at line 37 of file moeoNSGA.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class MOEOT> \fBmoeoNSGA\fP< MOEOT >::\fBmoeoNSGA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoGenOp\fP< MOEOT > & _op, double _nicheSize = \fC0.5\fP)\fC [inline]\fP"
.PP
Simple ctor with a \fBeoGenOp\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_maxGen\fP number of generations before stopping 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.br
\fI_nicheSize\fP niche size 
.RE
.PP

.PP
Definition at line 48 of file moeoNSGA.h.
.SS "template<class MOEOT> \fBmoeoNSGA\fP< MOEOT >::\fBmoeoNSGA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoTransform\fP< MOEOT > & _op, double _nicheSize = \fC0.5\fP)\fC [inline]\fP"
.PP
Simple ctor with a \fBeoTransform\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_maxGen\fP number of generations before stopping 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.br
\fI_nicheSize\fP niche size 
.RE
.PP

.PP
Definition at line 61 of file moeoNSGA.h.
.SS "template<class MOEOT> \fBmoeoNSGA\fP< MOEOT >::\fBmoeoNSGA\fP (unsigned int _maxGen, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoQuadOp\fP< MOEOT > & _crossover, double _pCross, \fBeoMonOp\fP< MOEOT > & _mutation, double _pMut, double _nicheSize = \fC0.5\fP)\fC [inline]\fP"
.PP
Ctor with a crossover, a mutation and their corresponding rates. 
.PP
\fBParameters:\fP
.RS 4
\fI_maxGen\fP number of generations before stopping 
.br
\fI_eval\fP evaluation function 
.br
\fI_crossover\fP crossover 
.br
\fI_pCross\fP crossover probability 
.br
\fI_mutation\fP mutation 
.br
\fI_pMut\fP mutation probability 
.br
\fI_nicheSize\fP niche size 
.RE
.PP

.PP
Definition at line 77 of file moeoNSGA.h.
.SS "template<class MOEOT> \fBmoeoNSGA\fP< MOEOT >::\fBmoeoNSGA\fP (\fBeoContinue\fP< MOEOT > & _continuator, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoGenOp\fP< MOEOT > & _op, double _nicheSize = \fC0.5\fP)\fC [inline]\fP"
.PP
Ctor with a continuator (instead of _maxGen) and a \fBeoGenOp\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_continuator\fP stopping criteria 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.br
\fI_nicheSize\fP niche size 
.RE
.PP

.PP
Definition at line 91 of file moeoNSGA.h.
.SS "template<class MOEOT> \fBmoeoNSGA\fP< MOEOT >::\fBmoeoNSGA\fP (\fBeoContinue\fP< MOEOT > & _continuator, \fBeoEvalFunc\fP< MOEOT > & _eval, \fBeoTransform\fP< MOEOT > & _op, double _nicheSize = \fC0.5\fP)\fC [inline]\fP"
.PP
Ctor with a continuator (instead of _maxGen) and a \fBeoTransform\fP. 
.PP
\fBParameters:\fP
.RS 4
\fI_continuator\fP stopping criteria 
.br
\fI_eval\fP evaluation function 
.br
\fI_op\fP variation operator 
.br
\fI_nicheSize\fP niche size 
.RE
.PP

.PP
Definition at line 104 of file moeoNSGA.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> virtual void \fBmoeoNSGA\fP< MOEOT >::operator() (\fBeoPop\fP< MOEOT > & _pop)\fC [inline, virtual]\fP"
.PP
Apply a few generation of evolution to the population _pop until the stopping criteria is verified. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.RE
.PP

.PP
Definition at line 114 of file moeoNSGA.h.
.PP
References moeoNSGA< MOEOT >::breed, moeoNSGA< MOEOT >::continuator, moeoNSGA< MOEOT >::diversityAssignment, moeoNSGA< MOEOT >::fitnessAssignment, moeoNSGA< MOEOT >::popEval, and moeoNSGA< MOEOT >::replace.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
