.TH "moeoSolutionUnaryMetric" 3 "26 Jun 2007" "Version 1.0" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoSolutionUnaryMetric \- Base class for unary metrics dedicated to the performance evaluation of a single solution's objective vector.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoMetric.h>\fP
.PP
Inherits \fBmoeoUnaryMetric< const ObjectiveVector &, R >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class ObjectiveVector, class R> class moeoSolutionUnaryMetric< ObjectiveVector, R >"
Base class for unary metrics dedicated to the performance evaluation of a single solution's objective vector. 
.PP
Definition at line 43 of file moeoMetric.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
