.TH "moeoElitistReplacement" 3 "16 Jan 2007" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoElitistReplacement \- Keep all the best individuals (almost cut-and-pasted from \fBeoNDPlusReplacement\fP, (c) Maarten Keijzer, Marc Schoenauer and GeNeura Team, 2002).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoReplacement.h>\fP
.PP
Inherits \fBmoeoReplacement< EOT, WorthT >< EOT, WorthT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoElitistReplacement\fP (\fBeoPerf2Worth\fP< EOT, WorthT > &_perf2worth)"
.br
.RI "\fIconstructor \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< EOT > &_parents, \fBeoPop\fP< EOT > &_offspring)"
.br
.RI "\fIreplacement - result in _parents \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoPerf2Worth\fP< EOT, WorthT > & \fBperf2worth\fP"
.br
.RI "\fIthe functor object to transform raw fitnesses into fitness for selection \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class WorthT = double> class moeoElitistReplacement< EOT, WorthT >"
Keep all the best individuals (almost cut-and-pasted from \fBeoNDPlusReplacement\fP, (c) Maarten Keijzer, Marc Schoenauer and GeNeura Team, 2002). 
.PP
Definition at line 35 of file moeoReplacement.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class EOT, class WorthT = double> \fBmoeoElitistReplacement\fP< EOT, WorthT >::\fBmoeoElitistReplacement\fP (\fBeoPerf2Worth\fP< EOT, WorthT > & _perf2worth)\fC [inline]\fP"
.PP
constructor 
.PP
\fBParameters:\fP
.RS 4
\fI_perf2worth\fP the functor class to transform raw fitnesses into fitness for selection 
.RE
.PP

.PP
Definition at line 43 of file moeoReplacement.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT, class WorthT = double> void \fBmoeoElitistReplacement\fP< EOT, WorthT >::operator() (\fBeoPop\fP< EOT > & _parents, \fBeoPop\fP< EOT > & _offspring)\fC [inline, virtual]\fP"
.PP
replacement - result in _parents 
.PP
\fBParameters:\fP
.RS 4
\fI_parents\fP parents population 
.br
\fI_offspring\fP offspring population 
.RE
.PP

.PP
Implements \fBeoBF< eoPop< EOT > &, eoPop< EOT > &, void >\fP.
.PP
Definition at line 54 of file moeoReplacement.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
