.TH "moeoIBEA" 3 "16 Jan 2007" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoIBEA \- Functor The sorting phase of IBEA (Indicator-Based Evolutionary Algorithm).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoIBEA.h>\fP
.PP
Inherits \fBeoPerf2WorthCached< EOT, double >\fP.
.PP
Inherited by \fBmoeoIBEASorting< EOT, Fitness >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoIBEA\fP (\fBmoeoBinaryQualityIndicator\fP< Fitness > *_I)"
.br
.ti -1c
.RI "void \fBcalculate_worths\fP (const \fBeoPop\fP< EOT > &_pop)"
.br
.RI "\fImapping \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBmoeoBinaryQualityIndicator\fP< Fitness > * \fBI\fP"
.br
.RI "\fIbinary quality indicator to use in the selection process \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class Fitness> class moeoIBEA< EOT, Fitness >"
Functor The sorting phase of IBEA (Indicator-Based Evolutionary Algorithm). 
.PP
Definition at line 28 of file moeoIBEA.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT, class Fitness> void \fBmoeoIBEA\fP< EOT, Fitness >::calculate_worths (const \fBeoPop\fP< EOT > & _pop)\fC [inline, virtual]\fP"
.PP
mapping 
.PP
\fBParameters:\fP
.RS 4
\fIconst\fP eoPop<EOT>& _pop the population 
.RE
.PP

.PP
Implements \fBeoPerf2WorthCached< EOT, double >\fP.
.PP
Definition at line 46 of file moeoIBEA.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
