.TH "moeoDisctinctElitistReplacement" 3 "16 Jan 2007" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoDisctinctElitistReplacement \- Same than \fBmoeoElitistReplacement\fP except that distinct individuals are privilegied.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoReplacement.h>\fP
.PP
Inherits \fBmoeoReplacement< EOT, WorthT >< EOT, WorthT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoDisctinctElitistReplacement\fP (\fBeoPerf2Worth\fP< EOT, WorthT > &_perf2worth)"
.br
.RI "\fIconstructor \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< EOT > &_parents, \fBeoPop\fP< EOT > &_offspring)"
.br
.RI "\fIreplacement - result in _parents \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcreateNewPop\fP (\fBeoPop\fP< EOT > &_pop, unsigned _size)"
.br
.RI "\fIcreation of the new population of size _size \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoPerf2Worth\fP< EOT, WorthT > & \fBperf2worth\fP"
.br
.RI "\fIthe functor object to transform raw fitnesses into fitness for selection \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class WorthT = double> class moeoDisctinctElitistReplacement< EOT, WorthT >"
Same than \fBmoeoElitistReplacement\fP except that distinct individuals are privilegied. 
.PP
Definition at line 78 of file moeoReplacement.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class EOT, class WorthT = double> \fBmoeoDisctinctElitistReplacement\fP< EOT, WorthT >::\fBmoeoDisctinctElitistReplacement\fP (\fBeoPerf2Worth\fP< EOT, WorthT > & _perf2worth)\fC [inline]\fP"
.PP
constructor 
.PP
\fBParameters:\fP
.RS 4
\fI_perf2worth\fP the functor class to transform raw fitnesses into fitness for selection 
.RE
.PP

.PP
Definition at line 87 of file moeoReplacement.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT, class WorthT = double> void \fBmoeoDisctinctElitistReplacement\fP< EOT, WorthT >::operator() (\fBeoPop\fP< EOT > & _parents, \fBeoPop\fP< EOT > & _offspring)\fC [inline, virtual]\fP"
.PP
replacement - result in _parents 
.PP
\fBParameters:\fP
.RS 4
\fI_parents\fP parents population 
.br
\fI_offspring\fP offspring population 
.RE
.PP

.PP
Implements \fBeoBF< eoPop< EOT > &, eoPop< EOT > &, void >\fP.
.PP
Definition at line 99 of file moeoReplacement.h.
.PP
References moeoDisctinctElitistReplacement< EOT, WorthT >::createNewPop().
.SS "template<class EOT, class WorthT = double> void \fBmoeoDisctinctElitistReplacement\fP< EOT, WorthT >::createNewPop (\fBeoPop\fP< EOT > & _pop, unsigned _size)\fC [inline, private]\fP"
.PP
creation of the new population of size _size 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the initial population (will be modified) 
.br
\fI_size\fP the size of the population to create 
.RE
.PP

.PP
Definition at line 123 of file moeoReplacement.h.
.PP
References moeoDisctinctElitistReplacement< EOT, WorthT >::perf2worth, and eoPop< EOT >::swap().
.PP
Referenced by moeoDisctinctElitistReplacement< EOT, WorthT >::operator()().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
