.TH "moeoSolutionVsSolutionBM" 3 "16 Jan 2007" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoSolutionVsSolutionBM \- Base class for binary metrics dedicated to the performance comparison between two solutions's Pareto fitnesses.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoMetric.h>\fP
.PP
Inherits \fBmoeoBM< A1, A2, R >< const const EOFitness &, EOFitness &, R >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class R, class EOFitness = typename EOT::Fitness> class moeoSolutionVsSolutionBM< EOT, R, EOFitness >"
Base class for binary metrics dedicated to the performance comparison between two solutions's Pareto fitnesses. 
.PP
Definition at line 70 of file moeoMetric.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
