.TH "BiasedNodeSelector" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BiasedNodeSelector \- A node selector that does a specified number of rounds ignoring terminals.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <NodeSelector.h>\fP
.PP
Inherits \fBNodeSelector\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBiasedNodeSelector\fP (unsigned n)"
.br
.ti -1c
.RI "NodeSelection \fBselect_node\fP (Sym sym) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnRounds\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A node selector that does a specified number of rounds ignoring terminals. 
.PP
Definition at line 55 of file NodeSelector.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
