.TH "boolean_generator" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boolean_generator \- The class boolean_generator can be used in the STL generate function to easily generate random booleans with a specified bias.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <rnd_generators.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBboolean_generator\fP (float _bias=0.5, \fBeoRng\fP &_rng=rng)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBbias\fP"
.br
.ti -1c
.RI "\fBeoRng\fP & \fBgen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The class boolean_generator can be used in the STL generate function to easily generate random booleans with a specified bias. 
.PP
Definition at line 70 of file rnd_generators.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
