.TH "Cov" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cov \- Single covariance between two variates.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <stats.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdate\fP (double a, double b)"
.br
.ti -1c
.RI "double \fBget_meana\fP () const "
.br
.ti -1c
.RI "double \fBget_meanb\fP () const "
.br
.ti -1c
.RI "double \fBget_cov\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBn\fP"
.br
.ti -1c
.RI "double \fBmeana\fP"
.br
.ti -1c
.RI "double \fBmeanb\fP"
.br
.ti -1c
.RI "double \fBsumcov\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Single covariance between two variates. 
.PP
Definition at line 58 of file stats.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
