.TH "dMatrix" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dMatrix \- A helper class for Sharing - to hold distances.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSharing.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdMatrix\fP (unsigned _s)"
.br
.ti -1c
.RI "double \fBoperator()\fP (unsigned _i, unsigned _j) const "
.br
.RI "\fIsimple accessor \fP"
.ti -1c
.RI "double & \fBoperator()\fP (unsigned _i, unsigned _j)"
.br
.RI "\fIreference - to set values \fP"
.ti -1c
.RI "void \fBprintOn\fP (std::ostream &_os)"
.br
.RI "\fIjust in case \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBrSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A helper class for Sharing - to hold distances. 
.PP
Definition at line 37 of file eoSharing.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
