.TH "Dummy" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dummy \- test program for the general operator - millenium version! uses dummy individuals  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBEO< double >\fP, \fBEO< double >\fP, \fBEO< double >\fP, \fBEO< double >\fP, \fBEO< double >\fP, and \fBEO< double >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef double \fBType\fP"
.br
.ti -1c
.RI "typedef double \fBType\fP"
.br
.ti -1c
.RI "typedef double \fBType\fP"
.br
.ti -1c
.RI "typedef double \fBType\fP"
.br
.ti -1c
.RI "typedef double \fBType\fP"
.br
.ti -1c
.RI "typedef double \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDummy\fP (std::string _s='')"
.br
.ti -1c
.RI "void \fBprintOn\fP (std::ostream &_os) const "
.br
.RI "\fIWrite object. \fP"
.ti -1c
.RI "void \fBprintOn\fP (std::ostream &_os) const "
.br
.RI "\fIWrite object. \fP"
.ti -1c
.RI "void \fBprintOn\fP (std::ostream &_os) const "
.br
.RI "\fIWrite object. \fP"
.ti -1c
.RI "void \fBprintOn\fP (std::ostream &_os) const "
.br
.RI "\fIWrite object. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBs\fP"
.br
.ti -1c
.RI "double \fBxdist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
test program for the general operator - millenium version! uses dummy individuals 
.PP
Definition at line 27 of file t-eoCheckpointing.cpp.
.SH "Member Function Documentation"
.PP 
.SS "void Dummy::printOn (std::ostream & _os) const\fC [inline, virtual]\fP"
.PP
Write object. 
.PP
Called printOn since it prints the object _on_ a stream. 
.PP
\fBParameters:\fP
.RS 4
\fI_os\fP A std::ostream. 
.RE
.PP

.PP
Reimplemented from \fBEO< double >\fP.
.PP
Definition at line 41 of file t-eoGenOp.cpp.
.PP
References EO< F >::printOn().
.SS "void Dummy::printOn (std::ostream & _os) const\fC [inline, virtual]\fP"
.PP
Write object. 
.PP
Called printOn since it prints the object _on_ a stream. 
.PP
\fBParameters:\fP
.RS 4
\fI_os\fP A std::ostream. 
.RE
.PP

.PP
Reimplemented from \fBEO< double >\fP.
.PP
Definition at line 23 of file t-eoReplacement.cpp.
.PP
References EO< F >::printOn().
.SS "void Dummy::printOn (std::ostream & _os) const\fC [inline, virtual]\fP"
.PP
Write object. 
.PP
Called printOn since it prints the object _on_ a stream. 
.PP
\fBParameters:\fP
.RS 4
\fI_os\fP A std::ostream. 
.RE
.PP

.PP
Reimplemented from \fBEO< double >\fP.
.PP
Definition at line 18 of file t-eoSelect.cpp.
.PP
References EO< F >::printOn().
.SS "void Dummy::printOn (std::ostream & _os) const\fC [inline, virtual]\fP"
.PP
Write object. 
.PP
Called printOn since it prints the object _on_ a stream. 
.PP
\fBParameters:\fP
.RS 4
\fI_os\fP A std::ostream. 
.RE
.PP

.PP
Reimplemented from \fBEO< double >\fP.
.PP
Definition at line 24 of file t-eoSharing.cpp.
.PP
References EO< F >::printOn().

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
