.PP
.TH "eo1PtBitCrossover" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eo1PtBitCrossover \- eo1PtBitXover --> classic 1-point crossover  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ga/eoBitOp.h>\fP
.PP
.SH "Detailed Description"
.PP 
eo1PtBitXover --> classic 1-point crossover 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
