.TH "eoAtomExchange" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoAtomExchange \- A helper class for choosing which genes to exchange.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoVariableLengthCrossover.h>\fP
.PP
Inherits \fBeoBF< unsigned, Atom &, bool >\fP.
.PP
Inherited by \fBeoUniformAtomExchange< Atom >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBrandomize\fP (unsigned int, unsigned int)"
.br
.RI "\fIa function to initlialize - to be called before every crossover \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const =0"
.br
.RI "\fIthe inherited \fBclassName()\fP \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Atom> class eoAtomExchange< Atom >"
A helper class for choosing which genes to exchange. 
.PP
Definition at line 41 of file eoVariableLengthCrossover.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
