.TH "eoBestSelect" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoBestSelect \- eoBestSelect: a selection method that always return the best (mainly for testing purposes)  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoRandomSelect.h>\fP
.PP
Inherits \fBeoSelectOne< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const \fBEOT\fP & \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fInot a big deal!!! \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoBestSelect< EOT >"
eoBestSelect: a selection method that always return the best (mainly for testing purposes) 
.PP
Definition at line 60 of file eoRandomSelect.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
