.TH "eoBitPrev" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoBitPrev \- eoBitPrev --> previous value when bitstring treated as binary value  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ga/eoBitOp.h>\fP
.PP
Inherits \fBeoMonOp< Chrom >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIThe class name. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (Chrom &chrom)"
.br
.RI "\fIChange the bit std::string x to be x-1. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Chrom> class eoBitPrev< Chrom >"
eoBitPrev --> previous value when bitstring treated as binary value 
.PP
Definition at line 208 of file eoBitOp.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class Chrom> bool \fBeoBitPrev\fP< Chrom >::operator() (Chrom & chrom)\fC [inline, virtual]\fP"
.PP
Change the bit std::string x to be x-1. 
.PP
\fBParameters:\fP
.RS 4
\fIchrom\fP The chromosome to be substracted one. 
.RE
.PP

.PP
Implements \fBeoUF< Chrom &, bool >\fP.
.PP
Definition at line 218 of file eoBitOp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
