.TH "eoBinCloneOp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoBinCloneOp \- Binary clone: two operands, only the first could be modified.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoCloneOps.h>\fP
.PP
Inherits \fBeoBinOp< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoBinCloneOp\fP ()"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.ti -1c
.RI "virtual bool \fBoperator()\fP (\fBEOT\fP &, const \fBEOT\fP &)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoBinCloneOp< EOT >"
Binary clone: two operands, only the first could be modified. 
.PP
Definition at line 57 of file eoCloneOps.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
