.TH "eoBooleanGenerator" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoBooleanGenerator \- The class eoBooleanGenerator can be used in the STL generate function to easily generate random booleans with a specified bias.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoRndGenerators.h>\fP
.PP
Inherits \fBeoRndGenerator< bool >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoBooleanGenerator\fP (float _bias=0.5, \fBeoRng\fP &_rng=rng)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (void)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBbias\fP"
.br
.ti -1c
.RI "\fBeoRng\fP & \fBgen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The class eoBooleanGenerator can be used in the STL generate function to easily generate random booleans with a specified bias. 
.PP
Definition at line 104 of file eoRndGenerators.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
