.TH "eoBoolFlip" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoBoolFlip \- a simple boolean mutation - to be used in generic eoOp's  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoBoolFlip.h>\fP
.PP
Inherits \fBeoMonOp< bool >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (bool &_b)"
.br
.RI "\fIsimply flips the boolean argument \fP"
.ti -1c
.RI "virtual string \fBclassName\fP () const "
.br
.RI "\fIinherited \fBclassName()\fP \fP"
.in -1c
.SH "Detailed Description"
.PP 
a simple boolean mutation - to be used in generic eoOp's 
.PP
Definition at line 32 of file eoBoolFlip.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
