.TH "eoBreed" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoBreed \- Breeding: combination of selecting and transforming a population.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoBreed.h>\fP
.PP
Inherits \fBeoBF< const eoPop< EOT > &, eoPop< EOT > &, void >\fP.
.PP
Inherited by eoBreedOne< EOT >, \fBeoGeneralBreeder< EOT >\fP, eoOneToOneBreeder< EOT >, and \fBeoSelectTransform< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoBreed< EOT >"
Breeding: combination of selecting and transforming a population. 

Breeding is thought of a combination of selecting and transforming a population. For efficiency reasons you might want to build your own eoBreed derived class rather than relying on a seperate select and transform function.
.PP
\fBSee also:\fP
.RS 4
\fBeoSelect\fP, \fBeoTransform\fP, \fBeoSelectTransform\fP 
.RE
.PP

.PP
Definition at line 46 of file eoBreed.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
