.TH "eoCMAInit" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoCMAInit \- TODO, handle bounds.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoCMAInit.h>\fP
.PP
Inherits \fBeoInit< eoVector< FitT, double > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoCMAInit\fP (const eo::CMAState &state_)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBEOT\fP &v)"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef \fBeoVector\fP< \fBFitT\fP, double > \fBEOT\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const eo::CMAState & \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class FitT> class eoCMAInit< FitT >"
TODO, handle bounds. 
.PP
Definition at line 37 of file eoCMAInit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
