.TH "eoCMABreed" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoCMABreed \- TODO, handle bounds.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoCMABreed.h>\fP
.PP
Inherits \fBeoBreed< eoVector< FitT, double > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoCMABreed\fP (eo::CMAState &state_, unsigned lambda_)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &parents, \fBeoPop\fP< \fBEOT\fP > &offspring)"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef \fBeoVector\fP< \fBFitT\fP, double > \fBEOT\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "eo::CMAState & \fBstate\fP"
.br
.ti -1c
.RI "unsigned \fBlambda\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class FitT> class eoCMABreed< FitT >"
TODO, handle bounds. 
.PP
Definition at line 36 of file eoCMABreed.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
