.TH "eoCollapseSubtreeMutation" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoCollapseSubtreeMutation \- eoCollapseSubtree --> replace a subtree with a randomly chosen terminal  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <gp/eoParseTreeOp.h>\fP
.PP
Inherits \fBeoMonOp< eoParseTree< FType, Node > >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBeoParseTree\fP< FType, Node > \fBEoType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoCollapseSubtreeMutation\fP (\fBeoInit\fP< \fBEoType\fP > &_init, unsigned _max_length)"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIThe class name. \fP"
.ti -1c
.RI "virtual \fB~eoCollapseSubtreeMutation\fP ()"
.br
.RI "\fIDtor. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBEoType\fP &_eo1)"
.br
.RI "\fIMutate an individual. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBmax_length\fP"
.br
.ti -1c
.RI "\fBeoInit\fP< \fBEoType\fP > & \fBinitializer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class FType, class Node> class eoCollapseSubtreeMutation< FType, Node >"
eoCollapseSubtree --> replace a subtree with a randomly chosen terminal 
.PP
Definition at line 272 of file eoParseTreeOp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class FType, class Node> \fBeoCollapseSubtreeMutation\fP< FType, Node >::\fBeoCollapseSubtreeMutation\fP (\fBeoInit\fP< \fBEoType\fP > & _init, unsigned _max_length)\fC [inline]\fP"
.PP
Constructor. 
.PP
\fBParameters:\fP
.RS 4
\fI_init\fP An instantiation of eoGpDepthInitializer 
.br
\fI_max_length\fP the maximum size of an individual 
.RE
.PP

.PP
Definition at line 282 of file eoParseTreeOp.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class FType, class Node> bool \fBeoCollapseSubtreeMutation\fP< FType, Node >::operator() (\fBEoType\fP & _eo1)\fC [inline]\fP"
.PP
Mutate an individual. 
.PP
\fBParameters:\fP
.RS 4
\fI_eo1\fP The individual that is to be changed 
.RE
.PP

.PP
Definition at line 295 of file eoParseTreeOp.h.
.PP
References eoParseTree< FType, Node >::pruneTree(), and eoRng::random().

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
