.TH "eoDetTournamentWorthSelect" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoDetTournamentWorthSelect \- An instance of eoSelectPerf2Worth that does selection from the Worthes using a ...  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSelectFromWorth.h>\fP
.PP
Inherits \fBeoSelectFromWorth< EOT, WorthT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::vector< WorthT >::iterator \fBworthIterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoDetTournamentWorthSelect\fP (\fBeoPerf2Worth\fP< \fBEOT\fP, WorthT > &perf2Worth, unsigned _tSize)"
.br
.ti -1c
.RI "virtual const \fBEOT\fP & \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &pop)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBtSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class WorthT = double> class eoDetTournamentWorthSelect< EOT, WorthT >"
An instance of eoSelectPerf2Worth that does selection from the Worthes using a ... 

determinisitic tournament, yes! 
.PP
Definition at line 91 of file eoSelectFromWorth.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
