.TH "eoDeterministicSurviveAndDie" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoDeterministicSurviveAndDie \- An instance (theonly one as of today, Dec.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSurviveAndDie.h>\fP
.PP
Inherits \fBeoSurviveAndDie< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoDeterministicSurviveAndDie\fP (double _survive, double _die, bool _interpret_as_rate=true)"
.br
.RI "\fIconstructor \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_pop, \fBeoPop\fP< \fBEOT\fP > &_luckyGuys)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoDeterministicSurviveAndDie< EOT >"
An instance (theonly one as of today, Dec. 

20, 2000) of an \fBeoSurviveAndDie\fP, that does everything deterministically
.PP
Used in \fBeoDeterministicSaDReplacement\fP. 
.PP
Definition at line 73 of file eoSurviveAndDie.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
