.TH "eoDeterministicSaDReplacement" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoDeterministicSaDReplacement \- eoDeterministicSaDReplacement: replacement strategy that is just, in sequence saves best and kill worse from parents + saves best and kill worse from offspring + merge remaining (neither save nor killed) parents and offspring + reduce that merged population = returns reduced pop + best parents + best offspring  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSurviveAndDie.h>\fP
.PP
Inherits \fBeoReplacement< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoDeterministicSaDReplacement\fP (\fBeoReduce\fP< \fBEOT\fP > &_reduceGlobal, double _surviveParents, double _dieParents=0, double _surviveOffspring=0, double _dieOffspring=0, bool _interpret_as_rate=true)"
.br
.RI "\fIConstructor with reduce. \fP"
.ti -1c
.RI "\fBeoDeterministicSaDReplacement\fP (double _surviveParents, double _dieParents=0, double _surviveOffspring=0, double _dieOffspring=0, bool _interpret_as_rate=true)"
.br
.RI "\fIConstructor with default truncate used as reduce. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_parents, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoReduce\fP< \fBEOT\fP > & \fBreduceGlobal\fP"
.br
.ti -1c
.RI "\fBeoDeterministicSurviveAndDie\fP< \fBEOT\fP > \fBsAdParents\fP"
.br
.ti -1c
.RI "\fBeoDeterministicSurviveAndDie\fP< \fBEOT\fP > \fBsAdOffspring\fP"
.br
.ti -1c
.RI "\fBeoPlus\fP< \fBEOT\fP > \fBplus\fP"
.br
.ti -1c
.RI "\fBeoTruncate\fP< \fBEOT\fP > \fBtruncate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoDeterministicSaDReplacement< EOT >"
eoDeterministicSaDReplacement: replacement strategy that is just, in sequence saves best and kill worse from parents + saves best and kill worse from offspring + merge remaining (neither save nor killed) parents and offspring + reduce that merged population = returns reduced pop + best parents + best offspring 

An obvious use is as strong elitist strategy, i.e. preserving best parents, and reducing (either offspring or parents+offspring) 
.PP
Definition at line 132 of file eoSurviveAndDie.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
