.TH "eoDetTournamentSelect" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoDetTournamentSelect \- eoDetTournamentSelect: a selection method that selects ONE individual by deterministic tournament -MS- 24/10/99  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoDetTournamentSelect.h>\fP
.PP
Inherits \fBeoSelectOne< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoDetTournamentSelect\fP (unsigned _tSize=2)"
.br
.ti -1c
.RI "virtual const \fBEOT\fP & \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBtSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoDetTournamentSelect< EOT >"
eoDetTournamentSelect: a selection method that selects ONE individual by deterministic tournament -MS- 24/10/99 
.PP
Definition at line 44 of file eoDetTournamentSelect.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
