.TH "eoDistribution" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoDistribution \- Abstract class for Distribution Evolution Algorithms within \fBEO\fP: the distribution itself.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoDistribution.h>\fP
.PP
Inherits \fBeoInit< EOT >< EOT >\fP, \fBeoPersistent\fP, and \fBeoObject\fP.
.PP
Inherited by \fBeoPBILDistrib< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBEOT\fP &)=0"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoDistribution< EOT >"
Abstract class for Distribution Evolution Algorithms within \fBEO\fP: the distribution itself. 

It basically IS AN \fBeoInit\fP - \fBoperator()(EOT &)\fP generates new indis
.PP
The instances will probably be \fBeoValueParam\fP of some kind see \fBeoPBILDistrib.h\fP 
.PP
Definition at line 45 of file eoDistribution.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
