.TH "eoDistribUpdater" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoDistribUpdater \- Base class for Distribution Evolution Algorithms within \fBEO\fP: the update rule of distribution.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoDistribUpdater.h>\fP
.PP
Inherits \fBeoBF< eoDistribution< EOT > &, eoPop< EOT > &, void >\fP.
.PP
Inherited by \fBeoPBILAdditive< EOT >\fP, and \fBeoPBILOrg< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBeoDistribution\fP< \fBEOT\fP > &, \fBeoPop\fP< \fBEOT\fP > &)=0"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoDistribUpdater< EOT >"
Base class for Distribution Evolution Algorithms within \fBEO\fP: the update rule of distribution. 

It takes one distribution and updates it according to one population 
.PP
Definition at line 43 of file eoDistribUpdater.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
