.TH "eoDoubleExchange" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoDoubleExchange \- Discrete crossover == exchange of values.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoRealAtomXover.h>\fP
.PP
Inherits \fBeoBinOp< double >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoDoubleExchange\fP ()"
.br
.RI "\fI(Default) Constructor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIThe class name. Used to display statistics. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (double &r1, const double &r2)"
.br
.RI "\fIExchanges or not the values. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Discrete crossover == exchange of values. 
.PP
Definition at line 41 of file eoRealAtomXover.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
