.TH "eoEDA" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoEDA \- eoEDA: Estimation of Distribution Algorithm within \fBEO\fP  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoEDA.h>\fP
.PP
Inherits \fBeoUF< eoDistribution< EOT > &, void >\fP.
.PP
Inherited by \fBeoSimpleEDA< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoEDA< EOT >"
eoEDA: Estimation of Distribution Algorithm within \fBEO\fP 

The abstract class for algorithms that evolve a probability distribution on the spaces of populations rather than a population
.PP
It IS NOT an \fBeoAlgo\fP, as it evolves a distribution, not a population 
.PP
Definition at line 41 of file eoEDA.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
