.TH "eoElitism" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoElitism \- Straightforward elitism class, specify the number of individuals to copy into new geneneration or the rate w.r.t.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoMerge.h>\fP
.PP
Inherits \fBeoMerge< EOT >\fP.
.PP
Inherited by \fBeoNoElitism< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoElitism\fP (double _rate, bool _interpret_as_rate=true)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBrate\fP"
.br
.ti -1c
.RI "unsigned \fBcombien\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoElitism< EOT >"
Straightforward elitism class, specify the number of individuals to copy into new geneneration or the rate w.r.t. 

pop size 
.PP
Definition at line 55 of file eoMerge.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
