.TH "eoEPReplacement" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoEPReplacement \- EP type of replacement strategy: first add parents to population, then truncate using EP tournament.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoMergeReduce.h>\fP
.PP
Inherits \fBeoMergeReduce< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoEPReplacement\fP (int _tSize)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoPlus\fP< \fBEOT\fP > \fBplus\fP"
.br
.ti -1c
.RI "\fBeoEPReduce\fP< \fBEOT\fP > \fBtruncate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoEPReplacement< EOT >"
EP type of replacement strategy: first add parents to population, then truncate using EP tournament. 
.PP
Definition at line 102 of file eoMergeReduce.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
