.TH "eoEsFull" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoEsFull \- The most complex evolutionary strategy representation.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoEsFull.h>\fP
.PP
Inherits \fBeoVector< Fit, double >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef double \fBType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBclassName\fP (void) const "
.br
.RI "\fIReturn the class id. \fP"
.ti -1c
.RI "void \fBprintOn\fP (std::ostream &os) const "
.br
.RI "\fIprinting... \fP"
.ti -1c
.RI "void \fBreadFrom\fP (std::istream &is)"
.br
.RI "\fIreading... \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< double > \fBstdevs\fP"
.br
.ti -1c
.RI "std::vector< double > \fBcorrelations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Fit> class eoEsFull< Fit >"
The most complex evolutionary strategy representation. 

Co-evolving mutation rates and correlated mutations. 
.PP
Definition at line 40 of file eoEsFull.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class Fit> virtual std::string \fBeoEsFull\fP< Fit >::className (void) const\fC [inline, virtual]\fP"
.PP
Return the class id. 
.PP
\fBReturns:\fP
.RS 4
the class name as a std::string 
.RE
.PP

.PP
Reimplemented from \fBEO< Fit >\fP.
.PP
Definition at line 51 of file eoEsFull.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
