.TH "eoEvalContinue" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoEvalContinue \- Continues until a number of evaluations has been made.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoEvalContinue.h>\fP
.PP
Inherits \fBeoContinue< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoEvalContinue\fP (\fBeoEvalFuncCounter\fP< \fBEOT\fP > &_eval, unsigned long _totalEval)"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "virtual bool \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_vEO)"
.br
.RI "\fIReturns false when a certain number of evaluations has been done. \fP"
.ti -1c
.RI "virtual unsigned long \fBtotalEvaluations\fP ()"
.br
.RI "\fIReturns the number of generations to reach. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP (void) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoEvalFuncCounter\fP< \fBEOT\fP > & \fBeval\fP"
.br
.ti -1c
.RI "unsigned long \fBrepTotalEvaluations\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoEvalContinue< EOT >"
Continues until a number of evaluations has been made. 
.PP
Definition at line 36 of file eoEvalContinue.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
