.TH "eoEvalFuncCounter" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoEvalFuncCounter \- Counts the number of evaluations actually performed, thus checks first if it has to evaluate..  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoEvalFuncCounter.h>\fP
.PP
Inherits \fBeoEvalFunc< EOT >< EOT >\fP, and \fBeoValueParam< unsigned long >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoEvalFuncCounter\fP (\fBeoEvalFunc\fP< \fBEOT\fP > &_func, std::string _name='Eval. ')"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBEOT\fP &_eo)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoEvalFunc\fP< \fBEOT\fP > & \fBfunc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoEvalFuncCounter< EOT >"
Counts the number of evaluations actually performed, thus checks first if it has to evaluate.. 

etc. 
.PP
Definition at line 37 of file eoEvalFuncCounter.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
