.TH "eoExternalEO" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoExternalEO \- Definition of an object that allows an external struct to be inserted in \fBEO\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoExternalEO.h>\fP
.PP
Inherits \fBEO< Fit >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoExternalEO\fP (const External &ext)"
.br
.RI "\fIInit externalEo with the struct itself and set fitness to zero. \fP"
.ti -1c
.RI "\fBeoExternalEO\fP (std::istream &is, const External &ext)"
.br
.ti -1c
.RI "virtual void \fBreadFrom\fP (std::istream &_is)"
.br
.RI "\fIRead object, the external struct needs to have an operator>> defined. \fP"
.ti -1c
.RI "virtual void \fBprintOn\fP (std::ostream &_os) const "
.br
.RI "\fIWrite object. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Fit, class External> class eoExternalEO< Fit, External >"
Definition of an object that allows an external struct to be inserted in \fBEO\fP. 

This struct or class can be of any form, the only thing this class does is attach a fitness value to it and makes it the appropriate type (derives it from \fBEO\fP). 
.PP
Definition at line 39 of file eoExternalEO.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class Fit, class External> virtual void \fBeoExternalEO\fP< Fit, External >::printOn (std::ostream & _os) const\fC [inline, virtual]\fP"
.PP
Write object. 
.PP
Called printOn since it prints the object _on_ a stream. 
.PP
\fBParameters:\fP
.RS 4
\fI_os\fP A std::ostream. 
.RE
.PP

.PP
Reimplemented from \fBEO< Fit >\fP.
.PP
Definition at line 69 of file eoExternalEO.h.
.PP
References EO< F >::printOn().

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
