.TH "eoExternalBinOp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoExternalBinOp \- Crossover of external struct, ctor expects a function of the following signature:.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoExternalOpFunctions.h>\fP
.PP
Inherits \fBeoBinOp< ExternalEO >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoExternalBinOp\fP (bool(*_binop)(External &, const External &))"
.br
.ti -1c
.RI "bool \fBoperator()\fP (ExternalEO &eo1, const ExternalEO &eo2)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool(* \fBbinop\fP )(External &, const External &)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class F, class External, class ExternalEO = eoExternalEO<F, External>> class eoExternalBinOp< F, External, ExternalEO >"
Crossover of external struct, ctor expects a function of the following signature:. 

bool func(External&, const External&);
.PP
Where External is the user defined struct or class The function should return true when it changed something, false otherwise 
.PP
Definition at line 128 of file eoExternalOpFunctions.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
