.TH "eoF" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoF \- Basic Function.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoFunctor.h>\fP
.PP
Inherits \fBeoFunctorBase\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef R \fBresult_type\fP"
.br
.RI "\fIthe return type - probably useless .... \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~eoF\fP ()"
.br
.RI "\fIvirtual dtor here so there is no need to define it in derived classes \fP"
.ti -1c
.RI "virtual R \fBoperator()\fP ()=0"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoFunctorBase::procedure_tag\fP \fBfunctor_category\fP ()"
.br
.RI "\fItag to identify a procedure in compile time function selection functor_category \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class R> class eoF< R >"
Basic Function. 

Derive from this class when defining any procedure. It defines a result_type that can be used to determine the return type Argument and result types can be any type including void for result_type 
.PP
Definition at line 68 of file eoFunctor.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
