.TH "eoFDCStat" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoFDCStat \- The FDC computation - stores the values into eoValueParam<EOT,double> so they can be snapshot by some eoGnuplotSnapshot ...  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoFDCStat.h>\fP
.PP
Inherits \fBeoStat< EOT, double >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoFDCStat\fP (\fBeoDistance\fP< \fBEOT\fP > &_dist, std::string _description='FDC')"
.br
.RI "\fICtor without the optimum. \fP"
.ti -1c
.RI "\fBeoFDCStat\fP (\fBeoDistance\fP< \fBEOT\fP > &_dist, \fBEOT\fP &_theBest, std::string _description='FDC')"
.br
.RI "\fICtor with the optimum. \fP"
.ti -1c
.RI "virtual void \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fICompute the FDC - either from best in pop, or from absolute best if it was passed in the constructor. \fP"
.ti -1c
.RI "const \fBeoValueParam\fP< std::vector< double > > & \fBtheDist\fP ()"
.br
.RI "\fIaccessors to the private \fBeoValueParam\fP<std::vector<double> > \fP"
.ti -1c
.RI "const \fBeoValueParam\fP< std::vector< double > > & \fBtheFit\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoDistance\fP< \fBEOT\fP > & \fBdist\fP"
.br
.ti -1c
.RI "\fBEOT\fP \fBtheBest\fP"
.br
.ti -1c
.RI "bool \fBboolOpt\fP"
.br
.ti -1c
.RI "\fBeoValueParam\fP< std::vector< double > > \fBdistToBest\fP"
.br
.ti -1c
.RI "\fBeoValueParam\fP< std::vector< double > > \fBfitnesses\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoFDCStat< EOT >"
The FDC computation - stores the values into eoValueParam<EOT,double> so they can be snapshot by some eoGnuplotSnapshot ... 
.PP
Definition at line 39 of file eoFDCStat.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
