.TH "eoFitContinue" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoFitContinue \- Fitness continuation:.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoFitContinue.h>\fP
.PP
Inherits \fBeoContinue< EOT >< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::Fitness \fBFitnessType\fP"
.br
.RI "\fIDefine Fitness. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoFitContinue\fP (const \fBFitnessType\fP _maximum)"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "virtual bool \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIReturns false when a fitness criterium is reached. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP (void) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBFitnessType\fP \fBmaximum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoFitContinue< EOT >"
Fitness continuation:. 

Continues until the maximum fitness level is reached. 
.PP
Definition at line 36 of file eoFitContinue.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT> virtual bool \fBeoFitContinue\fP< \fBEOT\fP >::operator() (const \fBeoPop\fP< \fBEOT\fP > & _pop)\fC [inline, virtual]\fP"
.PP
Returns false when a fitness criterium is reached. 
.PP
Assumes pop is not sorted! 
.PP
Implements \fBeoUF< const eoPop< EOT > &, bool >\fP.
.PP
Definition at line 48 of file eoFitContinue.h.
.PP
References eoPop< EOT >::nth_element_fitness().

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
