.TH "eoFitnessStat" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoFitnessStat \- The fitnesses of a whole population, as a vector.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoMOFitnessStat.h>\fP
.PP
Inherits \fBeoSortedStat< EOT, std::vector< FitT > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoFitnessStat\fP (std::string _description='AllFitnesses')"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP (const std::vector< const \fBEOT\fP * > &_popPters)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class FitT = typename EOT::Fitness> class eoFitnessStat< EOT, FitT >"
The fitnesses of a whole population, as a vector. 
.PP
Definition at line 36 of file eoMOFitnessStat.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
