.TH "eoFlOrKMutation" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoFlOrKMutation \- Applies an atomic mutation to a fixed number of components (1 by default).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoFlOrMonOp.h>\fP
.PP
Inherits \fBeoMonOp< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::AtomType \fBAtomType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoFlOrKMutation\fP (\fBeoMonOp\fP< AtomType > &_atomMutation, unsigned _nb=1)"
.br
.RI "\fIdefault ctor: requires an Atom mutation \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBEOT\fP &_eo)"
.br
.RI "\fIapplies the atom mutation to K randomly selected components \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIinherited \fBclassName()\fP \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnb\fP"
.br
.ti -1c
.RI "\fBeoMonOp\fP< AtomType > & \fBatomMutation\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoFlOrKMutation< EOT >"
Applies an atomic mutation to a fixed number of components (1 by default). 
.PP
Definition at line 82 of file eoFlOrMonOp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
