.TH "eoFlOrAllMutation" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoFlOrAllMutation \- applies an atomic mutation to all the components with a given rate  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoFlOrMonOp.h>\fP
.PP
Inherits \fBeoMonOp< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::AtomType \fBAtomType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoFlOrAllMutation\fP (\fBeoMonOp\fP< AtomType > &_atomMutation, double _rate=1.0)"
.br
.RI "\fIdefault ctor: requires an Atom mutation and a rate \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBEOT\fP &_eo)"
.br
.RI "\fIapplies the atom mutation to all components with given rate \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIinherited \fBclassName()\fP \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoMonOp\fP< AtomType > & \fBatomMutation\fP"
.br
.ti -1c
.RI "double \fBrate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoFlOrAllMutation< EOT >"
applies an atomic mutation to all the components with a given rate 
.PP
Definition at line 45 of file eoFlOrMonOp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
