.TH "eoFlOrAllAtomBinOp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoFlOrAllAtomBinOp \- Bin Crossover using an Atom Crossover that is applied to a ALL components with given rate.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoFlOrBinOp.h>\fP
.PP
Inherits \fBeoBinOp< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::AtomType \fBAtomType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoFlOrAllAtomBinOp\fP (\fBeoBinOp\fP< AtomType > &_op, float _rate=1.0)"
.br
.RI "\fIdefault ctor: requires an Atom BinOp \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBEOT\fP &_eo1, const \fBEOT\fP &_eo2)"
.br
.RI "\fIapplies Atom crossover to ALL components with given rate \fP"
.ti -1c
.RI "virtual string \fBclassName\fP () const "
.br
.RI "\fIinherited \fBclassName()\fP \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBrate\fP"
.br
.ti -1c
.RI "\fBeoBinOp\fP< AtomType > & \fBop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoFlOrAllAtomBinOp< EOT >"
Bin Crossover using an Atom Crossover that is applied to a ALL components with given rate. 
.PP
Definition at line 49 of file eoFlOrBinOp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
