.TH "eoFlOr1ptQuadOp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoFlOr1ptQuadOp \- The 1pt crossover (just in case someone wants it some day!).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoFlOrQuadOp.h>\fP
.PP
Inherits \fBeoQuadOp< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::AtomType \fBAtomType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoVlUniformQuadOp\fP ()"
.br
.RI "\fIdefault ctor: no argument \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBEOT\fP &_eo1, \fBEOT\fP &_eo2)"
.br
.RI "\fIexchanges first and second parts of the vectors of Atoms \fP"
.ti -1c
.RI "virtual string \fBclassName\fP () const "
.br
.RI "\fIinherited \fBclassName()\fP \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoFlOr1ptQuadOp< EOT >"
The 1pt crossover (just in case someone wants it some day!). 
.PP
Definition at line 173 of file eoFlOrQuadOp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
