.TH "eoFunctorBase::binary_function_tag" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoFunctorBase::binary_function_tag \- tag to identify a binary function in compile time function selection functor_category  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoFunctor.h>\fP
.PP
.SH "Detailed Description"
.PP 
tag to identify a binary function in compile time function selection functor_category 
.PP
Definition at line 57 of file eoFunctor.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
