.TH "eoG3Replacement" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoG3Replacement \- eoG3Replacement is an \fBeoReplacement\fP: - no strong elitism (is suppposed to be within a steady-state engine) - choose N (2) parents RANDOMLY - remove them from the parent population - merge offspring and the N removed parents - select best N of this merged population - put them back into parent population  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoG3Replacement.h>\fP
.PP
Inherits \fBeoReplacement< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoG3Replacement\fP (\fBeoHowMany\fP _howManyEliminatedParents=\fBeoHowMany\fP(2, false))"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_parents, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoLinearTruncateSplit\fP< \fBEOT\fP > \fBsplit\fP"
.br
.ti -1c
.RI "\fBeoTruncateSplit\fP< \fBEOT\fP > \fBreduce\fP"
.br
.ti -1c
.RI "\fBeoPlus\fP< \fBEOT\fP > \fBplus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoG3Replacement< EOT >"
eoG3Replacement is an \fBeoReplacement\fP: - no strong elitism (is suppposed to be within a steady-state engine) - choose N (2) parents RANDOMLY - remove them from the parent population - merge offspring and the N removed parents - select best N of this merged population - put them back into parent population 
.PP
Definition at line 50 of file eoG3Replacement.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
