.TH "eoGenerationalReplacement" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoGenerationalReplacement \- generational replacement == swap populations  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoReplacement.h>\fP
.PP
Inherits \fBeoReplacement< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_parents, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIswap \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoGenerationalReplacement< EOT >"
generational replacement == swap populations 
.PP
Definition at line 84 of file eoReplacement.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
