.TH "eoGeneDelChooser" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoGeneDelChooser \- A helper class for choosing which site to delete.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoVariableLengthMutation.h>\fP
.PP
Inherits \fBeoUF< EOT &, unsigned int >\fP.
.PP
Inherited by \fBeoUniformGeneChooser< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual std::string \fBclassName\fP () const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoGeneDelChooser< EOT >"
A helper class for choosing which site to delete. 
.PP
Definition at line 85 of file eoVariableLengthMutation.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
