.TH "eoGnuplot1DSnapshot" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoGnuplot1DSnapshot \- Plot stats through gnuplot.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoGnuplot1DSnapshot.h>\fP
.PP
Inherits \fBeoFileSnapshot\fP, and \fBeoGnuplot\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoGnuplot1DSnapshot\fP (std::string _dirname, unsigned _frequency=1, std::string _filename='gen', std::string _delim=' ', unsigned _counter=0, bool _rmFiles=true)"
.br
.ti -1c
.RI "\fBeoGnuplot1DSnapshot\fP (std::string _dirname, \fBeoRealVectorBounds\fP &_bounds, unsigned _frequency=1, std::string _filename='gen', std::string _delim=' ', unsigned _counter=0, bool _rmFiles=true)"
.br
.ti -1c
.RI "\fBeoGnuplot1DSnapshot\fP (\fBeoFileSnapshot\fP &_fSnapshot)"
.br
.ti -1c
.RI "\fBeoGnuplot1DSnapshot\fP (\fBeoFileSnapshot\fP &_fSnapshot, \fBeoRealVectorBounds\fP &_bounds)"
.br
.ti -1c
.RI "virtual \fBeoMonitor\fP & \fBoperator()\fP ()"
.br
.RI "\fIThe operator(void): opens the std::ostream and calls the write method. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIClass name. \fP"
.ti -1c
.RI "virtual void \fBhandleBounds\fP (\fBeoRealVectorBounds\fP &_bounds)"
.br
.ti -1c
.RI "void \fBsetPointSize\fP (unsigned _pointSize)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBpointSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Plot stats through gnuplot. 

\fBAuthor:\fP
.RS 4
Marc Schoenauer 2000 
.RE
.PP
\fBVersion:\fP
.RS 4
0.0
.RE
.PP
This class plots through gnuplot the \fBeoStat\fP given as argument
.PP
Assumes that the same file is re-written every so and so, and plots it from scratch everytime it's called 
.PP
Definition at line 51 of file eoGnuplot1DSnapshot.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
