.TH "eoGnuplot1DMonitor" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoGnuplot1DMonitor \- Plot \fBeoStat\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoGnuplot1DMonitor.h>\fP
.PP
Inherits \fBeoFileMonitor\fP, and \fBeoGnuplot\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoGnuplot1DMonitor\fP (std::string _filename, bool _top=false)"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "virtual \fB~eoGnuplot1DMonitor\fP ()"
.br
.RI "\fIDestructor. \fP"
.ti -1c
.RI "virtual \fBeoMonitor\fP & \fBoperator()\fP ()"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.ti -1c
.RI "virtual void \fBFirstPlot\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIClass name. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Plot \fBeoStat\fP. 

\fBAuthor:\fP
.RS 4
Marc Schoenauer 
.RE
.PP
\fBVersion:\fP
.RS 4
0.0 (2000)
.RE
.PP
This class plots through gnuplot the \fBeoStat\fP given as argument
.PP
eoGnuplot1DMonitor plots stats through gnuplot
.PP
Assumes that the same file is appened every so and so, and replots it everytime 
.PP
Definition at line 47 of file eoGnuplot1DMonitor.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
