.TH "eoInitAdaptor" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoInitAdaptor \- eoInitAdaptor changes the place in the hierarchy from \fBeoInit\fP to \fBeoMonOp\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoInit.h>\fP
.PP
Inherits \fBeoMonOp< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoInitAdaptor\fP (\fBeoInit\fP< \fBEOT\fP > &_init)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (\fBEOT\fP &_eot)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoInit\fP< \fBEOT\fP > & \fBinit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoInitAdaptor< EOT >"
eoInitAdaptor changes the place in the hierarchy from \fBeoInit\fP to \fBeoMonOp\fP. 

This is mainly a type conversion, nothing else 
.PP
\fBSee also:\fP
.RS 4
\fBeoInit\fP, \fBeoMonOp\fP 
.RE
.PP

.PP
Definition at line 157 of file eoInit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
