.TH "eoInnerExchangeQuadOp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoInnerExchangeQuadOp \- Crossover using an AtomCrossover.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoVariableLengthCrossover.h>\fP
.PP
Inherits \fBeoQuadOp< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::AtomType \fBAtomType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoInnerExchangeQuadOp\fP (\fBeoQuadOp\fP< AtomType > &_op, float _rate=0.5)"
.br
.RI "\fIdefault ctor: requires bounds on number of genes + a rate \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBEOT\fP &_eo1, \fBEOT\fP &_eo2)"
.br
.RI "\fIperforms the Atom crossover \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBrate\fP"
.br
.ti -1c
.RI "\fBeoQuadOp\fP< AtomType > & \fBop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoInnerExchangeQuadOp< EOT >"
Crossover using an AtomCrossover. 

Probably irrelevant in Variable Length - see \fBeoFlOrBinOp.h\fP and \fBeoFlOrQuadOp.h\fP for the similar Fixed Length operators 
.PP
Definition at line 172 of file eoVariableLengthCrossover.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
