.TH "eoInitGenerator" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoInitGenerator \- turning an \fBeoInit\fP into a generator probably we should only use genrators - and suppress \fBeoInit\fP ??? MS - July 2001  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoInit.h>\fP
.PP
Inherits \fBeoF< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoInitGenerator\fP (\fBeoInit\fP< \fBEOT\fP > &_init)"
.br
.RI "\fICtor from a plain \fBeoInit\fP. \fP"
.ti -1c
.RI "virtual \fBEOT\fP \fBoperator()\fP ()"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoInit\fP< \fBEOT\fP > & \fBinit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoInitGenerator< EOT >"
turning an \fBeoInit\fP into a generator probably we should only use genrators - and suppress \fBeoInit\fP ??? MS - July 2001 
.PP
Definition at line 60 of file eoInit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
