.TH "eoIntAboveBound" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoIntAboveBound \- An eoIntBound bounded from above only.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoIntBounds.h>\fP
.PP
Inherits \fBeoIntBounds\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoIntAboveBound\fP (long int _max=0)"
.br
.RI "\fISimple bounds = minimum. \fP"
.ti -1c
.RI "virtual long int \fBmaximum\fP () const "
.br
.RI "\fIget maximum value ::exception if does not exist \fP"
.ti -1c
.RI "virtual long int \fBminimum\fP () const "
.br
.RI "\fIget minimum value ::exception if does not exist \fP"
.ti -1c
.RI "virtual long int \fBrange\fP () const "
.br
.RI "\fIget range ::exception if unbounded \fP"
.ti -1c
.RI "virtual double \fBuniform\fP (\fBeoRng\fP &_rng=eo::rng) const "
.br
.RI "\fIrandom generator of uniform numbers in bounds uses same naming convention than eo::rng ::exception if unbounded \fP"
.ti -1c
.RI "virtual long int \fBrandom\fP (\fBeoRng\fP &_rng=eo::rng) const "
.br
.ti -1c
.RI "virtual bool \fBisBounded\fP (void) const "
.br
.RI "\fISelf-Test: true if ***both*** a min and a max. \fP"
.ti -1c
.RI "virtual bool \fBhasNoBoundAtAll\fP (void) const "
.br
.RI "\fISelf-Test: true if no min ***and*** no max hence no further need to test/truncate/fold anything. \fP"
.ti -1c
.RI "virtual bool \fBisMinBounded\fP (void) const "
.br
.RI "\fISelf-Test: bounded from below??? \fP"
.ti -1c
.RI "virtual bool \fBisMaxBounded\fP (void) const "
.br
.RI "\fISelf-Test: bounded from above??? \fP"
.ti -1c
.RI "virtual bool \fBisInBounds\fP (double _r) const "
.br
.RI "\fITest on a value: is it in bounds? \fP"
.ti -1c
.RI "virtual void \fBfoldsInBounds\fP (double &_r) const "
.br
.RI "\fIPut value back into bounds - by folding back and forth. \fP"
.ti -1c
.RI "virtual void \fBtruncate\fP (double &_r) const "
.br
.RI "\fIPut value back into bounds - by truncating to a boundary value. \fP"
.ti -1c
.RI "virtual void \fBreadFrom\fP (std::istream &_is)"
.br
.RI "\fIRead object. \fP"
.ti -1c
.RI "virtual void \fBprintOn\fP (std::ostream &_os) const "
.br
.RI "\fIWrite object. \fP"
.ti -1c
.RI "virtual \fBeoIntBounds\fP * \fBdup\fP () const "
.br
.RI "\fIfor memory managements - ugly \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "long int \fBrepMaximum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An eoIntBound bounded from above only. 
.PP
Definition at line 441 of file eoIntBounds.h.
.SH "Member Function Documentation"
.PP 
.SS "virtual void eoIntAboveBound::readFrom (std::istream & _is)\fC [inline, virtual]\fP"
.PP
Read object. 
.PP
\fBParameters:\fP
.RS 4
\fI_is\fP A std::istream. but reading should not be done here, because of bound problems see eoIntVectorBounds 
.RE
.PP

.PP
Implements \fBeoPersistent\fP.
.PP
Definition at line 512 of file eoIntBounds.h.
.SS "virtual void eoIntAboveBound::printOn (std::ostream & _os) const\fC [inline, virtual]\fP"
.PP
Write object. 
.PP
It's called printOn since it prints the object on a stream. 
.PP
\fBParameters:\fP
.RS 4
\fI_os\fP A std::ostream. 
.RE
.PP

.PP
Implements \fBeoPrintable\fP.
.PP
Definition at line 521 of file eoIntBounds.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
