.TH "eoInitVariableLength" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoInitVariableLength \- Initializer for variable length representations with a single type.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoInit.h>\fP
.PP
Inherits \fBeoInit< EOT >< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::AtomType \fBAtomType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoInitVariableLength\fP (unsigned _minSize, unsigned _maxSize, \fBeoInit\fP< AtomType > &_init)"
.br
.RI "\fICtor from an \fBeoInit\fP. \fP"
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBEOT\fP &_chrom)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.ti -1c
.RI "\fBeoInit\fP< AtomType > & \fBatomInit\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBoffset\fP"
.br
.ti -1c
.RI "unsigned \fBextent\fP"
.br
.ti -1c
.RI "\fBeoInit\fP< AtomType > & \fBinit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoInitVariableLength< EOT >"
Initializer for variable length representations with a single type. 
.PP
Definition at line 107 of file eoInit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
