.TH "eoMergeReduce" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoMergeReduce \- eoMergeReduce: abstract replacement strategy that is just an application of an embedded merge, followed by an embedded reduce  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoMergeReduce.h>\fP
.PP
Inherits \fBeoReplacement< EOT >< EOT >\fP.
.PP
Inherited by \fBeoCommaReplacement< EOT >\fP, \fBeoEPReplacement< EOT >\fP, and \fBeoPlusReplacement< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoMergeReduce\fP (\fBeoMerge\fP< \fBEOT\fP > &_merge, \fBeoReduce\fP< \fBEOT\fP > &_reduce)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_parents, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoMerge\fP< \fBEOT\fP > & \fBmerge\fP"
.br
.ti -1c
.RI "\fBeoReduce\fP< \fBEOT\fP > & \fBreduce\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoMergeReduce< EOT >"
eoMergeReduce: abstract replacement strategy that is just an application of an embedded merge, followed by an embedded reduce 
.PP
Definition at line 50 of file eoMergeReduce.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
