.TH "eoMerge" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoMerge \- eoMerge: Base class for elitist replacement algorithms.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoMerge.h>\fP
.PP
Inherits \fBeoBF< const eoPop< Chrom > &, eoPop< Chrom > &, void >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class Chrom> class eoMerge< Chrom >"
eoMerge: Base class for elitist replacement algorithms. 

Merges the old population (first argument), with the new generation
.PP
Its signature is exactly that of the selection base \fBeoSelect\fP, but its purpose is to merge the two populations into one (the second argument). Note that the algorithms assume that the second argument denotes the next generation. 
.PP
Definition at line 48 of file eoMerge.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
