.TH "eoNDPlusReplacement" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoNDPlusReplacement \- An elitist non-dominated sorted replacement scheme.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBeoReplacement< EOT >< EOT >\fP, and \fBeoReplacement< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoNDPlusReplacement\fP (\fBeoPerf2Worth\fP< \fBEOT\fP, WorthT > &_perf2worth)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_parents, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.ti -1c
.RI "\fBeoNDPlusReplacement\fP (\fBeoPerf2Worth\fP< \fBEOT\fP, WorthT > &_perf2worth)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_parents, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoPerf2Worth\fP< \fBEOT\fP, WorthT > & \fBperf2worth\fP"
.br
.ti -1c
.RI "\fBeoPerf2Worth\fP< \fBEOT\fP, WorthT > & \fBperf2worth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class WorthT = double> class eoNDPlusReplacement< EOT, WorthT >"
An elitist non-dominated sorted replacement scheme. 

Trying out an elitist non-dominated sorted replacement scheme. 
.PP
Definition at line 45 of file make_algo_pareto.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
