.TH "eoNDSorting::DummyEO" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoNDSorting::DummyEO \- used in fast nondominated sorting \fBDummyEO\fP is just a storage place for fitnesses and to store the original index  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBEO< EOT::Fitness >\fP.
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoNDSorting< EOT >::DummyEO"
used in fast nondominated sorting \fBDummyEO\fP is just a storage place for fitnesses and to store the original index 
.PP
Definition at line 94 of file eoNDSorting.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
