.TH "eoNoPerf2Worth" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoNoPerf2Worth \- A dummy perf2worth, just in case you need it.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoPerf2Worth.h>\fP
.PP
Inherits \fBeoPerf2Worth< EOT, EOT::Fitness >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoNoPerf2Worth< EOT >"
A dummy perf2worth, just in case you need it. 
.PP
Definition at line 230 of file eoPerf2Worth.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
