.TH "eoNoElitism" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoNoElitism \- No elite.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoMerge.h>\fP
.PP
Inherits \fBeoElitism< EOT >< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoNoElitism< EOT >"
No elite. 
.PP
Definition at line 107 of file eoMerge.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
