.TH "eoNPtsBitXover" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoNPtsBitXover \- eoNPtsBitXover --> n-point crossover  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ga/eoBitOp.h>\fP
.PP
Inherits \fBeoQuadOp< Chrom >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoNPtsBitXover\fP (const unsigned &_num_points=2)"
.br
.RI "\fI(Default) Constructor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIThe class name. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (Chrom &chrom1, Chrom &chrom2)"
.br
.RI "\fIn-point crossover for binary chromosomes. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnum_points\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Chrom> class eoNPtsBitXover< Chrom >"
eoNPtsBitXover --> n-point crossover 
.PP
Definition at line 319 of file eoBitOp.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class Chrom> bool \fBeoNPtsBitXover\fP< Chrom >::operator() (Chrom & chrom1, Chrom & chrom2)\fC [inline, virtual]\fP"
.PP
n-point crossover for binary chromosomes. 
.PP
\fBParameters:\fP
.RS 4
\fIchrom1\fP The first chromosome. 
.br
\fIchrom2\fP The first chromosome. 
.RE
.PP

.PP
Implements \fBeoBF< Chrom &, Chrom &, bool >\fP.
.PP
Definition at line 337 of file eoBitOp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
