.TH "eoNthElementFitnessStat" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoNthElementFitnessStat \- The n_th element fitness in the population (see \fBeoBestFitnessStat\fP).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoStat.h>\fP
.PP
Inherits \fBeoSortedStat< EOT, EOT::Fitness >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::Fitness \fBFitness\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoNthElementFitnessStat\fP (unsigned _whichElement, std::string _description='nth element fitness')"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP (const std::vector< const \fBEOT\fP * > &_pop)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP (void) const "
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<class T> void \fBdoit\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop, \fBeoParetoFitness\fP< T >)"
.br
.ti -1c
.RI "template<class T> void \fBdoit\fP (const std::vector< const \fBEOT\fP * > &_pop, T)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBwhichElement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoNthElementFitnessStat< EOT >"
The n_th element fitness in the population (see \fBeoBestFitnessStat\fP). 
.PP
Definition at line 211 of file eoStat.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
