.TH "eoOneMaxQuadCrossover" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoOneMaxQuadCrossover \- Always write a comment in this format before class definition if you want the class to be documented by Doxygen.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoOneMaxQuadCrossover.h>\fP
.PP
Inherits \fBeoQuadOp< GenotypeT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoOneMaxQuadCrossover\fP ()"
.br
.RI "\fICtor - no requirement. \fP"
.ti -1c
.RI "string \fBclassName\fP () const "
.br
.RI "\fIThe class name. Used to display statistics. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (GenotypeT &_genotype1, GenotypeT &_genotype2)"
.br
.RI "\fIeoQuad crossover - modifies both parents \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class GenotypeT> class eoOneMaxQuadCrossover< GenotypeT >"
Always write a comment in this format before class definition if you want the class to be documented by Doxygen. 

THere is NO ASSUMPTION on the class GenoypeT. In particular, it does not need to derive from \fBEO\fP 
.PP
Definition at line 26 of file eoOneMaxQuadCrossover.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class GenotypeT> bool \fBeoOneMaxQuadCrossover\fP< GenotypeT >::operator() (GenotypeT & _genotype1, GenotypeT & _genotype2)\fC [inline, virtual]\fP"
.PP
eoQuad crossover - modifies both parents 
.PP
\fBParameters:\fP
.RS 4
\fI_genotype1\fP The first parent 
.br
\fI_genotype2\fP The second parent
.RE
.PP
.PP
Requirement if (at least one genotype has been modified) // no way to distinguish oneAtLeastIsModified = true; else oneAtLeastIsModified = false; 
.PP
Implements \fBeoBF< GenotypeT &, GenotypeT &, bool >\fP.
.PP
Definition at line 49 of file eoOneMaxQuadCrossover.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
