.TH "eoOneMaxInit" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoOneMaxInit \- Always write a comment in this format before class definition if you want the class to be documented by Doxygen.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoOneMaxInit.h>\fP
.PP
Inherits \fBeoInit< GenotypeT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoOneMaxInit\fP (unsigned _vecSize)"
.br
.RI "\fICtor - no requirement. \fP"
.ti -1c
.RI "void \fBoperator()\fP (GenotypeT &_genotype)"
.br
.RI "\fIinitialize a genotype \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBvecSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class GenotypeT> class eoOneMaxInit< GenotypeT >"
Always write a comment in this format before class definition if you want the class to be documented by Doxygen. 

There is NO ASSUMPTION on the class GenoypeT. In particular, it does not need to derive from \fBEO\fP (e.g. to initialize atoms of an \fBeoVector\fP you will need an \fBeoInit<AtomType>\fP) 
.PP
Definition at line 26 of file eoOneMaxInit.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class GenotypeT> void \fBeoOneMaxInit\fP< GenotypeT >::operator() (GenotypeT & _genotype)\fC [inline, virtual]\fP"
.PP
initialize a genotype 
.PP
\fBParameters:\fP
.RS 4
\fI_genotype\fP generally a genotype that has been default-constructed whatever it contains will be lost 
.RE
.PP

.PP
Implements \fBeoUF< GenotypeT &, void >\fP.
.PP
Definition at line 44 of file eoOneMaxInit.h.
.PP
References eoRng::flip().

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
