.TH "eoParetoFitnessTraits" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoParetoFitnessTraits \- eoFitnessTraits: a traits class to specify the number of objectives and which one are maximizing or not See test/t-eoParetoFitness for its use.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoParetoFitness.h>\fP
.PP
Inherited by \fBeoVariableParetoTraits\fP, MinimizingFitnessTraits, MinimizingFitnessTraits, and \fBMinimizingTraits\fP.
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "unsigned \fBnObjectives\fP ()"
.br
.ti -1c
.RI "double \fBtol\fP ()"
.br
.ti -1c
.RI "bool \fBmaximizing\fP (int which)"
.br
.in -1c
.SH "Detailed Description"
.PP 
eoFitnessTraits: a traits class to specify the number of objectives and which one are maximizing or not See test/t-eoParetoFitness for its use. 

If you define your own, make sure you make the functions static! 
.PP
Definition at line 42 of file eoParetoFitness.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
