.TH "eoParamParamType" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoParamParamType \- Another helper class for parsing parameters like Keyword(arg1, arg2, ...).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoParam.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoParamParamType\fP (std::string _value)"
.br
.ti -1c
.RI "std::ostream & \fBprintOn\fP (std::ostream &_os) const "
.br
.ti -1c
.RI "std::istream & \fBreadFrom\fP (std::istream &_is)"
.br
.ti -1c
.RI "void \fBreadFrom\fP (std::string &_value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Another helper class for parsing parameters like Keyword(arg1, arg2, ...). 

It is basically a std::pair<std::string,std::vector<std::string> > first std::string is keyword the std::vector<std::string> contains all arguments (as std::strings) See make_algo.h 
.PP
Definition at line 373 of file eoParam.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
