.TH "eoParseTreeDepthInit" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoParseTreeDepthInit \- eoParseTreeDepthInit : the initializer class for \fBeoParseTree\fP  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <gp/eoParseTreeDepthInit.h>\fP
.PP
Inherits \fBeoInit< eoParseTree< FType, Node > >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBeoParseTree\fP< FType, Node > \fBEoType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoParseTreeDepthInit\fP (unsigned _max_depth, const std::vector< Node > &_initializor, bool _grow=true, bool _ramped_half_and_half=false)"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIMy class name. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBEoType\fP &_tree)"
.br
.RI "\fIinitialize a tree \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBgenerate\fP (std::list< Node > &sequence, int the_max, int last_terminal=-1)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBmax_depth\fP"
.br
.ti -1c
.RI "std::vector< Node > \fBinitializor\fP"
.br
.ti -1c
.RI "bool \fBgrow\fP"
.br
.ti -1c
.RI "bool \fBramped_half_and_half\fP"
.br
.ti -1c
.RI "unsigned \fBcurrent_depth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class FType, class Node> class eoParseTreeDepthInit< FType, Node >"
eoParseTreeDepthInit : the initializer class for \fBeoParseTree\fP 
.PP
Definition at line 48 of file eoParseTreeDepthInit.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class FType, class Node> \fBeoParseTreeDepthInit\fP< FType, Node >::\fBeoParseTreeDepthInit\fP (unsigned _max_depth, const std::vector< Node > & _initializor, bool _grow = \fCtrue\fP, bool _ramped_half_and_half = \fCfalse\fP)\fC [inline]\fP"
.PP
Constructor. 
.PP
_max_depth The maximum depth of a tree 
.PP
\fBParameters:\fP
.RS 4
\fI_initializor\fP A std::vector containing the possible nodes 
.br
\fI_grow\fP False results in a full tree, True result is a randomly grown tree 
.br
\fI_ramped_half_and_half\fP True results in Ramped Half and Half Initialization 
.RE
.PP

.PP
Definition at line 69 of file eoParseTreeDepthInit.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class FType, class Node> void \fBeoParseTreeDepthInit\fP< FType, Node >::operator() (\fBEoType\fP & _tree)\fC [inline]\fP"
.PP
initialize a tree 
.PP
\fBParameters:\fP
.RS 4
\fI_tree\fP : the tree to be initialized 
.RE
.PP

.PP
Definition at line 96 of file eoParseTreeDepthInit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
