.TH "eoPBILOrg" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoPBILOrg \- Distribution Class for PBIL algorithm (Population-Based Incremental Learning, Baluja and Caruana 95).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoPBILOrg.h>\fP
.PP
Inherits \fBeoDistribUpdater< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoPBILOrg\fP (double _LR, double _tolerance=0.0)"
.br
.RI "\fICtor with size of genomes, and update parameters. \fP"
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBeoDistribution\fP< \fBEOT\fP > &_distrib, \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIUpdate the distribution from the current population. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBLR\fP"
.br
.ti -1c
.RI "double \fBmaxBound\fP"
.br
.ti -1c
.RI "double \fBminBound\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoPBILOrg< EOT >"
Distribution Class for PBIL algorithm (Population-Based Incremental Learning, Baluja and Caruana 95). 

This class implements the update rule from the original paper:
.PP
p(i)(t+1) = (1-LR)*p(i)(t) + LR*best(i) 
.PP
Definition at line 42 of file eoPBILOrg.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
