.TH "eoPBILDistrib" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoPBILDistrib \- Distribution Class for PBIL algorithm (Population-Based Incremental Learning, Baluja and Caruana 96).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoPBILDistrib.h>\fP
.PP
Inherits \fBeoDistribution< EOT >< EOT >\fP, and \fBeoValueParam< std::vector< double > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoPBILDistrib\fP (unsigned _genomeSize)"
.br
.RI "\fICtor with size of genomes, and update parameters. \fP"
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBEOT\fP &_eo)"
.br
.RI "\fIthe randomizer of indis \fP"
.ti -1c
.RI "unsigned \fBSize\fP ()"
.br
.RI "\fIAccessor to the genome size. \fP"
.ti -1c
.RI "virtual void \fBprintOn\fP (std::ostream &os) const "
.br
.RI "\fIprinting... \fP"
.ti -1c
.RI "virtual void \fBreadFrom\fP (std::istream &is)"
.br
.RI "\fIreading... \fP"
.ti -1c
.RI "unsigned int \fBsize\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIclassName: Mandatory because of \fBeoCombinedInit\fP. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBgenomeSize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoPBILDistrib< EOT >"
Distribution Class for PBIL algorithm (Population-Based Incremental Learning, Baluja and Caruana 96). 

It encodes a univariate distribution on the space of bitstrings, i.e. one probability for each bit to be one
.PP
It is an \fBeoValueParam\fP<std::vector<double> > : the std::vector<double> stores the probabilities that each bit is 1
.PP
It is still pure virtual, as the update method needs to be specified 
.PP
Definition at line 44 of file eoPBILDistrib.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT> virtual std::string \fBeoPBILDistrib\fP< \fBEOT\fP >::className (void) const\fC [inline, virtual]\fP"
.PP
className: Mandatory because of \fBeoCombinedInit\fP. 
.PP
SHould be pure virtual, but then we should go over the whole code to write the method for all derived classes ... MS 16/7/04 
.PP
Reimplemented from \fBeoInit< EOT >\fP.
.PP
Definition at line 94 of file eoPBILDistrib.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
