.TH "eoPerf2Worth" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoPerf2Worth \- Base class to transform raw fitnesses into fitness for selection.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoPerf2Worth.h>\fP
.PP
Inherits \fBeoUF< const eoPop< EOT > &, void >\fP, and \fBeoValueParam< std::vector< WorthT > >\fP.
.PP
Inherited by \fBeoPerf2WorthCached< EOT, WorthT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoPerf2Worth\fP (std::string _description='Worths')"
.br
.RI "\fIdefault constructor \fP"
.ti -1c
.RI "virtual void \fBsort_pop\fP (\fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fISort population according to worth, will keep the worths and fitness_cache in sync with the population. \fP"
.ti -1c
.RI "virtual void \fBresize\fP (\fBeoPop\fP< \fBEOT\fP > &_pop, unsigned sz)"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class WorthT = double> class eoPerf2Worth< EOT, WorthT >"
Base class to transform raw fitnesses into fitness for selection. 

\fBSee also:\fP
.RS 4
\fBeoSelectFromWorth\fP 
.RE
.PP

.PP
Definition at line 43 of file eoPerf2Worth.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
