.TH "eoPlus" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoPlus \- Very elitist class, copies entire population into next gen.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoMerge.h>\fP
.PP
Inherits \fBeoMerge< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoPlus< EOT >"
Very elitist class, copies entire population into next gen. 
.PP
Definition at line 116 of file eoMerge.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
