.TH "eoPlusReplacement" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoPlusReplacement \- ES type of replacement strategy: first add parents to population, then truncate.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoMergeReduce.h>\fP
.PP
Inherits \fBeoMergeReduce< EOT >< EOT >\fP.
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoPlus\fP< \fBEOT\fP > \fBplus\fP"
.br
.ti -1c
.RI "\fBeoTruncate\fP< \fBEOT\fP > \fBtruncate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoPlusReplacement< EOT >"
ES type of replacement strategy: first add parents to population, then truncate. 
.PP
Definition at line 73 of file eoMergeReduce.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
