.TH "eoPop::Cmp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoPop::Cmp \- helper struct for comparing on pointers  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoPop.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBEOT\fP *a, const \fBEOT\fP *b) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> struct eoPop< EOT >::Cmp"
helper struct for comparing on pointers 
.PP
Definition at line 124 of file eoPop.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
