.TH "eoPointMutation" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoPointMutation \- eoPointMutation --> replace a Node with a Node of the same arity  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <gp/eoParseTreeOp.h>\fP
.PP
Inherits \fBeoMonOp< eoParseTree< FType, Node > >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBeoParseTree\fP< FType, Node > \fBEoType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoPointMutation\fP (std::vector< Node > &_initializor)"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIthe class name \fP"
.ti -1c
.RI "virtual \fB~eoPointMutation\fP ()"
.br
.RI "\fIDtor. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBEoType\fP &_eo1)"
.br
.RI "\fIMutate an individual. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< Node > & \fBinitializor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class FType, class Node> class eoPointMutation< FType, Node >"
eoPointMutation --> replace a Node with a Node of the same arity 
.PP
Definition at line 147 of file eoParseTreeOp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class FType, class Node> \fBeoPointMutation\fP< FType, Node >::\fBeoPointMutation\fP (std::vector< Node > & _initializor)\fC [inline]\fP"
.PP
Constructor. 
.PP
\fBParameters:\fP
.RS 4
\fI_initializor\fP The std::vector of Nodes given to the eoGpDepthInitializer 
.RE
.PP

.PP
Definition at line 157 of file eoParseTreeOp.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class FType, class Node> bool \fBeoPointMutation\fP< FType, Node >::operator() (\fBEoType\fP & _eo1)\fC [inline]\fP"
.PP
Mutate an individual. 
.PP
\fBParameters:\fP
.RS 4
\fI_eo1\fP The individual that is to be changed 
.RE
.PP

.PP
Definition at line 171 of file eoParseTreeOp.h.
.PP
References eoRng::random().

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
