.TH "eoProportionalOp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoProportionalOp \- The proportional versions: easy!  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoOpContainer.h>\fP
.PP
Inherits \fBeoOpContainer< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBapply\fP (\fBeoPopulator\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIthe function that will do the work \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoProportionalOp< EOT >"
The proportional versions: easy! 
.PP
Definition at line 135 of file eoOpContainer.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
