.TH "eoPropCombinedBinOp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoPropCombinedBinOp \- COmbined Binary genetic operator: operator() has two operands, only the first one can be modified.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoProportionalCombinedOp.h>\fP
.PP
Inherits \fBeoBinOp< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoPropCombinedBinOp\fP (\fBeoBinOp\fP< \fBEOT\fP > &_first, const double _rate)"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.ti -1c
.RI "virtual void \fBadd\fP (\fBeoBinOp\fP< \fBEOT\fP > &_op, const double _rate, bool _verbose=false)"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBEOT\fP &_indi1, const \fBEOT\fP &_indi2)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBeoBinOp\fP< \fBEOT\fP > * > \fBops\fP"
.br
.ti -1c
.RI "std::vector< double > \fBrates\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoPropCombinedBinOp< EOT >"
COmbined Binary genetic operator: operator() has two operands, only the first one can be modified. 
.PP
Definition at line 109 of file eoProportionalCombinedOp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
