.TH "eoPropGAGenOp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoPropGAGenOp \- *************************************************************************** eoPropGAGenOp (for Simple GA, but Proportional) choice between Crossover, mutation or cloining with respect to given relatve weights  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoPropGAGenOp.h>\fP
.PP
Inherits \fBeoGenOp< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoPropGAGenOp\fP (double _wClone, \fBeoQuadOp\fP< \fBEOT\fP > &_cross, double _wCross, \fBeoMonOp\fP< \fBEOT\fP > &_mut, double _wMut)"
.br
.RI "\fICtor from * weight of clone * crossover (with weight) * mutation (with weight). \fP"
.ti -1c
.RI "virtual void \fBapply\fP (\fBeoPopulator\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIdo the job: delegate to op \fP"
.ti -1c
.RI "virtual unsigned \fBmax_production\fP (void)"
.br
.RI "\fIinherited from \fBeoGenOp\fP \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBwClone\fP"
.br
.ti -1c
.RI "\fBeoQuadOp\fP< \fBEOT\fP > & \fBcross\fP"
.br
.ti -1c
.RI "double \fBwCross\fP"
.br
.ti -1c
.RI "\fBeoMonOp\fP< \fBEOT\fP > & \fBmut\fP"
.br
.ti -1c
.RI "double \fBwMut\fP"
.br
.ti -1c
.RI "\fBeoProportionalOp\fP< \fBEOT\fP > \fBpropOp\fP"
.br
.ti -1c
.RI "\fBeoMonCloneOp\fP< \fBEOT\fP > \fBmonClone\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoPropGAGenOp< EOT >"
*************************************************************************** eoPropGAGenOp (for Simple GA, but Proportional) choice between Crossover, mutation or cloining with respect to given relatve weights 
.PP
Definition at line 42 of file eoPropGAGenOp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
