.TH "eoQuadCloneOp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoQuadCloneOp \- Quad clone: two operands, both could be modified - but are not!  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoCloneOps.h>\fP
.PP
Inherits \fBeoQuadOp< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoQuadCloneOp\fP ()"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.ti -1c
.RI "virtual bool \fBoperator()\fP (\fBEOT\fP &, \fBEOT\fP &)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoQuadCloneOp< EOT >"
Quad clone: two operands, both could be modified - but are not! 
.PP
Definition at line 69 of file eoCloneOps.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
