.TH "eoQuadDistance" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoQuadDistance \- This is a generic class for Euclidain distance (L2 norm) computation: assumes the 2 things are std::vectors of something that is double-castable.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoDistance.h>\fP
.PP
Inherits \fBeoDistance< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBoperator()\fP (const \fBEOT\fP &_v1, const \fBEOT\fP &_v2)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoQuadDistance< EOT >"
This is a generic class for Euclidain distance (L2 norm) computation: assumes the 2 things are std::vectors of something that is double-castable. 
.PP
Definition at line 44 of file eoDistance.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
