.TH "eoRankingSelect" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoRankingSelect \- eoRankingSelect: select an individual by roulette wheel on its rank is an \fBeoRouletteWorthSelect\fP, i.e.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoRankingSelect.h>\fP
.PP
Inherits \fBeoRouletteWorthSelect< EOT, double >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoRankingSelect\fP (double _p=2.0, double _e=1.0)"
.br
.RI "\fICtor:. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoRanking\fP< \fBEOT\fP > \fBranking\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoRankingSelect< EOT >"
eoRankingSelect: select an individual by roulette wheel on its rank is an \fBeoRouletteWorthSelect\fP, i.e. 

a selector using a std::vector of worthes rather than the raw fitness (see \fBeoSelectFromWorth.h\fP) uses an internal \fBeoRanking\fP object which is an \fBeoPerf2Worth<EOT, double>\fP 
.PP
Definition at line 41 of file eoRankingSelect.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class EOT> \fBeoRankingSelect\fP< \fBEOT\fP >::\fBeoRankingSelect\fP (double _p = \fC2.0\fP, double _e = \fC1.0\fP)\fC [inline]\fP"
.PP
Ctor:. 
.PP
\fBParameters:\fP
.RS 4
\fI_p\fP the selective pressure, should be in [1,2] (2 is the default) 
.br
\fI_e\fP exponent (1 == linear) 
.RE
.PP

.PP
Definition at line 48 of file eoRankingSelect.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
