.TH "eoReduce" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoReduce \- eoReduce: .reduce the new generation to the specified size At the moment, limited to truncation - with 2 different methods, one that sorts the whole population, and one that repeatidely kills the worst.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoReduce.h>\fP
.PP
Inherits \fBeoBF< eoPop< EOT > &, unsigned, void >\fP.
.PP
Inherited by \fBeoDetTournamentTruncate< EOT >\fP, \fBeoEPReduce< EOT >\fP, \fBeoLinearTruncate< EOT >\fP, \fBeoRandomReduce< EOT >\fP, \fBeoStochTournamentTruncate< EOT >\fP, \fBeoStochTournamentTruncateSplit< EOT >\fP, and \fBeoTruncate< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoReduce< EOT >"
eoReduce: .reduce the new generation to the specified size At the moment, limited to truncation - with 2 different methods, one that sorts the whole population, and one that repeatidely kills the worst. 

Ideally, we should be able to choose at run-time!!! 
.PP
Definition at line 45 of file eoReduce.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
