.TH "eoReduceSplit" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoReduceSplit \- eoReduceSplit: reduce the pop to the specified size AND eventually returns the eliminated guys  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoReduceSplit.h>\fP
.PP
Inherits \fBeoBF< eoPop< EOT > &, eoPop< EOT > &, void >\fP.
.PP
Inherited by \fBeoDetTournamentTruncateSplit< EOT >\fP, \fBeoLinearRandomSplit< EOT >\fP, \fBeoLinearTruncateSplit< EOT >\fP, \fBeoRandomSplit< EOT >\fP, and \fBeoTruncateSplit< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoReduceSplit< EOT >"
eoReduceSplit: reduce the pop to the specified size AND eventually returns the eliminated guys 
.PP
Definition at line 42 of file eoReduceSplit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
