.TH "eoReduceMerge" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoReduceMerge \- eoReduceMerge: Replacement strategies that start by reducing the parents, then merge with the offspring  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoReduceMerge.h>\fP
.PP
Inherits \fBeoReplacement< EOT >< EOT >\fP.
.PP
Inherited by \fBeoSSGADetTournamentReplacement< EOT >\fP, \fBeoSSGAStochTournamentReplacement< EOT >\fP, and \fBeoSSGAWorseReplacement< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoReduceMerge\fP (\fBeoReduce\fP< \fBEOT\fP > &_reduce, \fBeoMerge\fP< \fBEOT\fP > &_merge)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_parents, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoReduce\fP< \fBEOT\fP > & \fBreduce\fP"
.br
.ti -1c
.RI "\fBeoMerge\fP< \fBEOT\fP > & \fBmerge\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoReduceMerge< EOT >"
eoReduceMerge: Replacement strategies that start by reducing the parents, then merge with the offspring 

This is the way to do SSGA: the offspring gets inserted in the population even if it is worse than anybody else.
.PP
: eoReduceMerge, \fBeoSSGAWorseReplacement\fP, \fBeoSSGADetTournamentReplacement\fP, \fBeoSSGAStochTournamentReplacement\fP 
.PP
Definition at line 53 of file eoReduceMerge.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
