.TH "eoReal" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoReal \- eoReal: implementation of simple real-valued chromosome.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoReal.h>\fP
.PP
Inherits \fBeoVector< FitT, double >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoReal\fP (unsigned size=0, double value=0.0)"
.br
.RI "\fI(Default) Constructor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIMy class name. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class FitT> class eoReal< FitT >"
eoReal: implementation of simple real-valued chromosome. 

based on \fBeoVector\fP class 
.PP
Definition at line 37 of file eoReal.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class FitT> \fBeoReal\fP< \fBFitT\fP >::\fBeoReal\fP (unsigned size = \fC0\fP, double value = \fC0.0\fP)\fC [inline]\fP"
.PP
(Default) Constructor. 
.PP
\fBParameters:\fP
.RS 4
\fIsize\fP Size of the std::vector 
.RE
.PP

.PP
Definition at line 45 of file eoReal.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
