.TH "eoRealInitBounded" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoRealInitBounded \- Simple initialization for any EOT that derives from std::vector<double> uniformly in some bounds.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoRealInitBounded.h>\fP
.PP
Inherits \fBeoInit< EOT >< EOT >\fP.
.PP
Inherited by \fBeoEsChromInit< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoRealInitBounded\fP (\fBeoRealVectorBounds\fP &_bounds)"
.br
.RI "\fICtor - from \fBeoRealVectorBounds\fP. \fP"
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBEOT\fP &_eo)"
.br
.RI "\fIsimply passes the argument to the uniform method of the bounds \fP"
.ti -1c
.RI "virtual \fBeoRealVectorBounds\fP & \fBtheBounds\fP ()"
.br
.RI "\fIaccessor to the bounds \fP"
.ti -1c
.RI "virtual unsigned \fBsize\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoRealVectorBounds\fP & \fBbounds\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoRealInitBounded< EOT >"
Simple initialization for any EOT that derives from std::vector<double> uniformly in some bounds. 
.PP
Definition at line 40 of file eoRealInitBounded.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
