.TH "eoReplacement" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoReplacement \- 
.SH SYNOPSIS
.br
.PP
\fC#include <eoReplacement.h>\fP
.PP
Inherits \fBeoBF< eoPop< EOT > &, eoPop< EOT > &, void >\fP.
.PP
Inherited by \fBeoDeterministicSaDReplacement< EOT >\fP, \fBeoG3Replacement< EOT >\fP, \fBeoGenerationalReplacement< EOT >\fP, \fBeoMergeReduce< EOT >\fP, \fBeoMGGReplacement< EOT >\fP, \fBeoNDPlusReplacement< EOT, WorthT >\fP, \fBeoNDPlusReplacement< EOT, WorthT >\fP, \fBeoReduceMerge< EOT >\fP, \fBeoReduceMergeReduce< EOT >\fP, and \fBeoWeakElitistReplacement< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoReplacement< EOT >"
NOTE: 2 \fBeoPop\fP as arguments the resulting population should be in the first argument (replace parents by offspring)! The second argument can contain any rubbish
.PP
--- The \fBeoMergeReduce\fP, combination of \fBeoMerge\fP and \fBeoReduce\fP, can be found in file \fBeoMergeReduce.h\fP
.PP
The \fBeoReduceMergeReduce\fP that reduces the parents and the offspring, merges the 2 reduced populations, and eventually reduces that final population, can be found in \fBeoReduceMergeReduce.h\fP
.PP
LOG --- Removed the const before first argument: though it makes too many classes with the same interface, it allows to minimize the number of actual copies by choosing the right destination I also removed the enforced 'swap' in the eoEasyAlgo and hence the generational replacement gets a class of its own that only does the swap (instead of the eoNoReplacement that did nothing, relying on the algo to swap popualtions). MS 12/12/2000
.PP
\fBSee also:\fP
.RS 4
\fBeoMerge\fP, \fBeoReduce\fP, \fBeoMergeReduce\fP, \fBeoReduceMerge\fP
.RE
.PP
eoReplacement, base (pure abstract) class \fBeoGenerationalReplacement\fP, as it says ... \fBeoWeakElitistReplacement\fP a wrapper to add elitism 
.PP
Definition at line 77 of file eoReplacement.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
