.TH "eoScalarFitness" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoScalarFitness \- eoScalarFitness<ScalarType, Compare = less<ScalarType> >: Wraps a scalar fitness values such as a double or int, with the option of maximizing (using less<ScalarType>) or minimizing (using greater<ScalarType>)  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoScalarFitness.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoScalarFitness\fP (const \fBeoScalarFitness\fP &other)"
.br
.ti -1c
.RI "\fBeoScalarFitness\fP (const ScalarType &v)"
.br
.ti -1c
.RI "\fBeoScalarFitness\fP & \fBoperator=\fP (const \fBeoScalarFitness\fP &other)"
.br
.ti -1c
.RI "\fBeoScalarFitness\fP & \fBoperator=\fP (const ScalarType &v)"
.br
.ti -1c
.RI "\fBoperator ScalarType\fP (void) const "
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBeoScalarFitness\fP &other) const "
.br
.RI "\fIComparison, using less by default. \fP"
.ti -1c
.RI "bool \fBoperator>\fP (const \fBeoScalarFitness\fP< ScalarType, Compare > &y) const "
.br
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBeoScalarFitness\fP< ScalarType, Compare > &y) const "
.br
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBeoScalarFitness\fP< ScalarType, Compare > &y) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "ScalarType \fBvalue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ScalarType, class Compare> class eoScalarFitness< ScalarType, Compare >"
eoScalarFitness<ScalarType, Compare = less<ScalarType> >: Wraps a scalar fitness values such as a double or int, with the option of maximizing (using less<ScalarType>) or minimizing (using greater<ScalarType>) 

It overrides \fBoperator<()\fP to use the Compare template argument
.PP
Suitable constructors and assignments and casts are defined to work with this quantity as if it were a ScalarType. 
.PP
Definition at line 43 of file eoScalarFitness.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
