.TH "eoScalarFitnessStat" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoScalarFitnessStat \- The fitnesses of a whole population, as a std::vector.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoScalarFitnessStat.h>\fP
.PP
Inherits \fBeoSortedStat< EOT, std::vector< double > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoScalarFitnessStat\fP (std::string _description='FitnessES', eoRealVectorBounds &_bounds=eoDummyVectorNoBounds)"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP (const std::vector< const \fBEOT\fP * > &_popPters)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoRealBounds\fP & \fBrange\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class FitT = typename EOT::Fitness> class eoScalarFitnessStat< EOT, FitT >"
The fitnesses of a whole population, as a std::vector. 
.PP
Definition at line 37 of file eoScalarFitnessStat.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
