.TH "eoSelectFactory" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSelectFactory \- \fBEO\fP Factory.An instance of the factory class to create selectors, that is, \fBeoSelect\fP objects.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSelectFactory.h>\fP
.PP
Inherits \fBeoFactory< eoSelect< EOT > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBeoSelect\fP< \fBEOT\fP > * \fBmake\fP (std::istream &_is)"
.br
.RI "\fIAnother factory methods: creates an object from an std::istream, reading from it whatever is needed to create the object. \fP"
.in -1c
.PP
.RI "\fBctors and dtors\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBeoSelectFactory\fP ()"
.br
.RI "\fIconstructor \fP"
.ti -1c
.RI "virtual \fB~eoSelectFactory\fP ()"
.br
.RI "\fIdestructor \fP"
.in -1c
.in -1c
.PP
.RI "\fBeoObject methods\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "void \fBprintOn\fP (std::ostream &_os) const "
.br
.ti -1c
.RI "void \fBreadFrom\fP (std::istream &_is)"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoSelectFactory< EOT >"
\fBEO\fP Factory.An instance of the factory class to create selectors, that is, \fBeoSelect\fP objects. 

\fBSee also:\fP
.RS 4
\fBeoSelect\fP 
.RE
.PP

.PP
Definition at line 39 of file eoSelectFactory.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT> virtual \fBeoSelect\fP<\fBEOT\fP>* \fBeoSelectFactory\fP< \fBEOT\fP >::make (std::istream & _is)\fC [inline, virtual]\fP"
.PP
Another factory methods: creates an object from an std::istream, reading from it whatever is needed to create the object. 
.PP
Usually, the format for the std::istream will be\\ objectType parameter1 parameter2 ... parametern\\
.PP
Implements \fBeoFactory< eoSelect< EOT > >\fP.
.PP
Definition at line 56 of file eoSelectFactory.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
