.TH "eoSequentialSelect" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSequentialSelect \- All Individuals in order.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSequentialSelect.h>\fP
.PP
Inherits \fBeoSelectOne< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoSequentialSelect\fP (bool _ordered=true)"
.br
.RI "\fICtor: sets the current pter to numeric_limits<unsigned>::max() so init will take place first time not very elegant, maybe ... \fP"
.ti -1c
.RI "void \fBsetup\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIvirtual function to setup some population stats (for instance eoProportional can benefit greatly from this) \fP"
.ti -1c
.RI "virtual const \fBEOT\fP & \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBordered\fP"
.br
.ti -1c
.RI "unsigned \fBcurrent\fP"
.br
.ti -1c
.RI "std::vector< const \fBEOT\fP * > \fBeoPters\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoSequentialSelect< EOT >"
All Individuals in order. 

Looping back to the beginning when exhausted, can be from best to worse, or in random order.
.PP
It is the \fBeoSelectOne\fP equivalent of \fBeoDetSelect\fP - though \fBeoDetSelect\fP always returns individuals from best to worst 
.PP
Definition at line 52 of file eoSequentialSelect.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
