.TH "eoSelectTransform" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSelectTransform \- Embedded select, followed by an embedded transform.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoBreed.h>\fP
.PP
Inherits \fBeoBreed< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoSelectTransform\fP (\fBeoSelect\fP< \fBEOT\fP > &_select, \fBeoTransform\fP< \fBEOT\fP > &_transform)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_parents, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoSelect\fP< \fBEOT\fP > & \fBselect\fP"
.br
.ti -1c
.RI "\fBeoTransform\fP< \fBEOT\fP > & \fBtransform\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoSelectTransform< EOT >"
Embedded select, followed by an embedded transform. 

Special breeder that is just an application of an embedded select, followed by an embedded transform 
.PP
Definition at line 57 of file eoBreed.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
