.TH "eoSelectFromWorth" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSelectFromWorth \- selects one element from a population (is an \fBeoSelectOne\fP) but the selection is based on a std::vector of Worth that is different from the fitnesses (e.g.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSelectFromWorth.h>\fP
.PP
Inherits \fBeoSelectOne< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoSelectFromWorth\fP (\fBeoPerf2Worth\fP< \fBEOT\fP, WorthType > &_perf2Worth)"
.br
.ti -1c
.RI "virtual void \fBsetup\fP (const \fBeoPop\fP< \fBEOT\fP > &pop)"
.br
.RI "\fIvirtual function to setup some population stats (for instance eoProportional can benefit greatly from this) \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBcheck_sync\fP (unsigned index, const \fBEOT\fP &_eo)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBeoPerf2Worth\fP< \fBEOT\fP, WorthType > & \fBperf2Worth\fP"
.br
.ti -1c
.RI "std::vector< typename EOT::Fitness > \fBfitness\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class WorthType = double> class eoSelectFromWorth< EOT, WorthType >"
selects one element from a population (is an \fBeoSelectOne\fP) but the selection is based on a std::vector of Worth that is different from the fitnesses (e.g. 

\fBEO\fP fitness is what Koza terms 'raw fitness', Worth is what the selection is based upon).
.PP
see class \fBeoPerf2Worth\fP: an \fBeoStat\fP that transforms fitnesses into Worthes
.PP
Note: Worthes will not always be doubles - see some multi-objective techniques where it is a std::pair of doubles ...
.PP
It has to have a < operator it you want to call an existing selector (see selector.h) - but of course you can write the whole thing ... 
.PP
Definition at line 51 of file eoSelectFromWorth.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
