.TH "eoSelect" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSelect \- eoSelect selects a number of individuals from the first argument and puts it in the second.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSelect.h>\fP
.PP
Inherits \fBeoBF< const eoPop< EOT > &, eoPop< EOT > &, void >\fP.
.PP
Inherited by \fBeoDetSelect< EOT >\fP, eoEasyEA< EOT >::eoDummySelect, \fBeoSelectMany< EOT >\fP, \fBeoSelectNumber< EOT >\fP, \fBeoSelectPerc< EOT >\fP, \fBeoTruncatedSelectMany< EOT >\fP, and \fBeoTruncSelect< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoSelect< EOT >"
eoSelect selects a number of individuals from the first argument and puts it in the second. 

To emphasize that it should not try to enlarge the population, the second argument is an eoPopRange, a simple struct that holds a begin and end iterator to the population 
.PP
Definition at line 40 of file eoSelect.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
