.TH "eoSGAGenOp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSGAGenOp \- *************************************************************************** eoSGAGenOp (for Simple GA) mimicks the usual crossover with proba pCross + mutation with proba pMut inside an eoGeneralOp It does it exactly as class \fBeoSGATransform\fP, i.e.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSGAGenOp.h>\fP
.PP
Inherits \fBeoGenOp< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoSGAGenOp\fP (\fBeoQuadOp\fP< \fBEOT\fP > &_cross, double _pCross, \fBeoMonOp\fP< \fBEOT\fP > &_mut, double _pMut)"
.br
.RI "\fICtor from crossover (with proba) and mutation (with proba) Builds the sequential op that first applies a proportional choice between the crossover and nothing (cloning), then the mutation. \fP"
.ti -1c
.RI "virtual void \fBapply\fP (\fBeoPopulator\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIdo the job: delegate to op \fP"
.ti -1c
.RI "virtual unsigned \fBmax_production\fP (void)"
.br
.RI "\fIinherited from \fBeoGenOp\fP \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoQuadOp\fP< \fBEOT\fP > & \fBcross\fP"
.br
.ti -1c
.RI "double \fBpCross\fP"
.br
.ti -1c
.RI "\fBeoMonOp\fP< \fBEOT\fP > & \fBmut\fP"
.br
.ti -1c
.RI "double \fBpMut\fP"
.br
.ti -1c
.RI "\fBeoProportionalOp\fP< \fBEOT\fP > \fBpropOp\fP"
.br
.ti -1c
.RI "\fBeoQuadCloneOp\fP< \fBEOT\fP > \fBquadClone\fP"
.br
.ti -1c
.RI "\fBeoSequentialOp\fP< \fBEOT\fP > \fBop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoSGAGenOp< EOT >"
*************************************************************************** eoSGAGenOp (for Simple GA) mimicks the usual crossover with proba pCross + mutation with proba pMut inside an eoGeneralOp It does it exactly as class \fBeoSGATransform\fP, i.e. 

only accepts quadratic crossover and unary mutation It was introduced for didactic reasons, but seems to be popular :-) 
.PP
Definition at line 44 of file eoSGAGenOp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
