.TH "eoSGATransform" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSGATransform \- eoSGATransform: transforms a population using genetic operators.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSGATransform.h>\fP
.PP
Inherits \fBeoTransform< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoSGATransform\fP (\fBeoQuadOp\fP< \fBEOT\fP > &_cross, double _cProba, \fBeoMonOp\fP< \fBEOT\fP > &_mutate, double _mProba)"
.br
.RI "\fIDefault constructor. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fITransforms a population. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoInvalidateQuadOp\fP< \fBEOT\fP > \fBcross\fP"
.br
.ti -1c
.RI "double \fBcrossoverProba\fP"
.br
.ti -1c
.RI "\fBeoInvalidateMonOp\fP< \fBEOT\fP > \fBmutate\fP"
.br
.ti -1c
.RI "double \fBmutationProba\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoSGATransform< EOT >"
eoSGATransform: transforms a population using genetic operators. 

It does it exactly as class \fBeoSGA\fP, i.e. only accepts quadratic crossover and unary mutation It is here mainly for tutorial reasons 
.PP
Definition at line 45 of file eoSGATransform.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT> void \fBeoSGATransform\fP< \fBEOT\fP >::operator() (\fBeoPop\fP< \fBEOT\fP > & _pop)\fC [inline, virtual]\fP"
.PP
Transforms a population. 
.PP
\fBParameters:\fP
.RS 4
\fIpop\fP The population to be transformed. 
.RE
.PP

.PP
Implements \fBeoUF< eoPop< EOT > &, void >\fP.
.PP
Definition at line 62 of file eoSGATransform.h.
.PP
References eoRng::flip().

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
