.TH "eoSharing" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSharing \- Sharing is a perf2worth class that implements Goldberg and Richardson's basic sharing see \fBeoSharingSelect\fP for how to use it and test/t-eoSharing.cpp for a sample use of both.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSharing.h>\fP
.PP
Inherits \fBeoPerf2Worth< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoSharing\fP (double _nicheSize, \fBeoDistance\fP< \fBEOT\fP > &_dist)"
.br
.ti -1c
.RI "void \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIComputes shared fitnesses. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBnicheSize\fP"
.br
.ti -1c
.RI "\fBeoDistance\fP< \fBEOT\fP > & \fBdist\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoSharing< EOT >"
Sharing is a perf2worth class that implements Goldberg and Richardson's basic sharing see \fBeoSharingSelect\fP for how to use it and test/t-eoSharing.cpp for a sample use of both. 
.PP
Definition at line 79 of file eoSharing.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
