.TH "eoSimpleEDA" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSimpleEDA \- eoSimpleEDA: a very simple Estimation of Distribution Algorithm  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSimpleEDA.h>\fP
.PP
Inherits \fBeoEDA< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoSimpleEDA\fP (\fBeoDistribUpdater\fP< \fBEOT\fP > &_update, \fBeoEvalFunc\fP< \fBEOT\fP > &_eval, unsigned _popSize, \fBeoContinue\fP< \fBEOT\fP > &_continuator)"
.br
.RI "\fICtor from an \fBeoDistribUpdater\fP ... \fP"
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBeoDistribution\fP< \fBEOT\fP > &_distrib)"
.br
.RI "\fIThe algorithm: generate pop from distrib, evaluate pop, update distrib. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoDistribUpdater\fP< \fBEOT\fP > & \fBupdate\fP"
.br
.ti -1c
.RI "\fBeoEvalFunc\fP< \fBEOT\fP > & \fBeval\fP"
.br
.ti -1c
.RI "unsigned \fBpopSize\fP"
.br
.ti -1c
.RI "\fBeoContinue\fP< \fBEOT\fP > & \fBcontinuator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoSimpleEDA< EOT >"
eoSimpleEDA: a very simple Estimation of Distribution Algorithm 

The algorithm that evolves a probability distribution on the spaces of populations with the loop generate a population from the current distribution evaluate that population update the distribution 
.PP
Definition at line 46 of file eoSimpleEDA.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class EOT> \fBeoSimpleEDA\fP< \fBEOT\fP >::\fBeoSimpleEDA\fP (\fBeoDistribUpdater\fP< \fBEOT\fP > & _update, \fBeoEvalFunc\fP< \fBEOT\fP > & _eval, unsigned _popSize, \fBeoContinue\fP< \fBEOT\fP > & _continuator)\fC [inline]\fP"
.PP
Ctor from an \fBeoDistribUpdater\fP ... 
.PP
plus an eoEval and \fBeoContinue\fP of course 
.PP
Definition at line 53 of file eoSimpleEDA.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
