.TH "eoSortedStatBase" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSortedStatBase \- Base class for statistics calculated over a sorted snapshot of the population.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoStat.h>\fP
.PP
Inherits \fBeoUF< const std::vector< const EOT * > &, void >\fP.
.PP
Inherited by \fBeoSortedStat< EOT, ParamType >\fP, \fBeoSortedStat< EOT, EOT::Fitness >\fP, \fBeoSortedStat< EOT, std::string >\fP, \fBeoSortedStat< EOT, std::vector< double > >\fP, \fBeoSortedStat< EOT, std::vector< FitT > >\fP, and \fBeoSortedStat< EOT, std::vector< PartFitT > >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBlastCall\fP (const std::vector< const \fBEOT\fP * > &)"
.br
.ti -1c
.RI "virtual std::string \fBclassName\fP (void) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoSortedStatBase< EOT >"
Base class for statistics calculated over a sorted snapshot of the population. 
.PP
Definition at line 76 of file eoStat.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
