.TH "eoSSGAWorseReplacement" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSSGAWorseReplacement \- SSGA replace worst.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoReduceMerge.h>\fP
.PP
Inherits \fBeoReduceMerge< EOT >< EOT >\fP.
.PP
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoLinearTruncate\fP< \fBEOT\fP > \fBtruncate\fP"
.br
.ti -1c
.RI "\fBeoPlus\fP< \fBEOT\fP > \fBplus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoSSGAWorseReplacement< EOT >"
SSGA replace worst. 

Is an \fBeoReduceMerge\fP. 
.PP
Definition at line 77 of file eoReduceMerge.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
