.TH "eoState::loading_error" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoState::loading_error \- Loading error thrown when nothing seems to work.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoState.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBloading_error\fP (std::string huh='Error while loading')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Loading error thrown when nothing seems to work. 
.PP
Definition at line 83 of file eoState.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
