.TH "eoStochasticUniversalSelect" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoStochasticUniversalSelect \- eoStochasticUniversalSelect: select an individual proportional to her stored fitness value, but in contrast with eoStochasticUniversalSelect, get rid of most finite sampling effects by doing all selections in one go, using a single random number.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoStochasticUniversalSelect.h>\fP
.PP
Inherits \fBeoSelectOne< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoStochasticUniversalSelect\fP (const \fBeoPop\fP< \fBEOT\fP > &pop=\fBeoPop\fP< \fBEOT\fP >())"
.br
.RI "\fISanity check. \fP"
.ti -1c
.RI "void \fBsetup\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIvirtual function to setup some population stats (for instance eoProportional can benefit greatly from this) \fP"
.ti -1c
.RI "const \fBEOT\fP & \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIdo the selection, \fP"
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef std::vector< unsigned > \fBIndexVec\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "IndexVec \fBindices\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoStochasticUniversalSelect< EOT >"
eoStochasticUniversalSelect: select an individual proportional to her stored fitness value, but in contrast with eoStochasticUniversalSelect, get rid of most finite sampling effects by doing all selections in one go, using a single random number. 
.PP
Definition at line 44 of file eoStochasticUniversalSelect.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
