.TH "eoStochTournamentTruncateSplit" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoStochTournamentTruncateSplit \- a ReduceSplit class based on a repeated deterministic (reverse!) tournament To be used in SSGA-like replacements (e.g.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoReduceSplit.h>\fP
.PP
Inherits \fBeoReduce< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoStochTournamentTruncateSplit\fP (double _t_rate, \fBeoHowMany\fP _howMany, bool _returnEliminated=false)"
.br
.RI "\fICtor: must provide amount of reduction, and whether or not you need to return the eliminated guys. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_newgen, \fBeoPop\fP< \fBEOT\fP > &_eliminated)"
.br
.RI "\fIPerforms repeated inverse_stochastic_tournament on the pop. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBt_rate\fP"
.br
.ti -1c
.RI "\fBeoHowMany\fP \fBhowMany\fP"
.br
.ti -1c
.RI "bool \fBreturnEliminated\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoStochTournamentTruncateSplit< EOT >"
a ReduceSplit class based on a repeated deterministic (reverse!) tournament To be used in SSGA-like replacements (e.g. 

see \fBeoSSGAStochTournamentReplacement\fP) 
.PP
Definition at line 256 of file eoReduceSplit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
