.TH "eoStat" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoStat \- The actual class that will be used as base for all statistics that need to be calculated over the (unsorted) population It is an \fBeoStatBase\fP AND an \fBeoValueParam\fP so it can be used in Monitors.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoStat.h>\fP
.PP
Inherits \fBeoValueParam< T >\fP, and \fBeoStatBase< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoStat\fP (T _value, std::string _description)"
.br
.ti -1c
.RI "virtual std::string \fBclassName\fP (void) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class T> class eoStat< EOT, T >"
The actual class that will be used as base for all statistics that need to be calculated over the (unsorted) population It is an \fBeoStatBase\fP AND an \fBeoValueParam\fP so it can be used in Monitors. 
.PP
Definition at line 58 of file eoStat.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
