.TH "eoStdoutMonitor" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoStdoutMonitor \- Prints statistics to stdout.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoStdoutMonitor.h>\fP
.PP
Inherits \fBeoMonitor\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoStdoutMonitor\fP (bool _verbose=true, std::string _delim='\\t')"
.br
.ti -1c
.RI "\fBeoMonitor\fP & \fBoperator()\fP (void)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP (void) const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBverbose\fP"
.br
.ti -1c
.RI "std::string \fBdelim\fP"
.br
.ti -1c
.RI "bool \fBfirsttime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Prints statistics to stdout. 
.PP
Definition at line 38 of file eoStdoutMonitor.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
