.TH "eoStatBase" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoStatBase \- Base class for all statistics that need to be calculated over the (unsorted) population (I guess it is not really necessary? MS.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoStat.h>\fP
.PP
Inherits \fBeoUF< const eoPop< EOT > &, void >\fP.
.PP
Inherited by \fBeoStat< EOT, T >\fP, \fBeoStat< EOT, double >\fP, \fBeoStat< EOT, EOT::Fitness >\fP, \fBeoStat< EOT, std::pair< double, double > >\fP, and \fBeoStat< EOT, std::string >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBlastCall\fP (const \fBeoPop\fP< \fBEOT\fP > &)"
.br
.ti -1c
.RI "virtual std::string \fBclassName\fP (void) const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoStatBase< EOT >"
Base class for all statistics that need to be calculated over the (unsorted) population (I guess it is not really necessary? MS. 

Depstd::ends, there might be reasons to have a stat that is not an \fBeoValueParam\fP, but maybe I'm just kidding myself, MK) 
.PP
Definition at line 45 of file eoStat.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
