.TH "eoSTLUF" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSTLUF \- Generic set of classes that wrap an \fBeoF\fP, \fBeoUF\fP or \fBeoBF\fP so that they have the copy semantics the STL functions usually require (i.e.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSTLFunctor.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoSTLUF\fP (\fBeoUF\fP< A1, R > &_f)"
.br
.ti -1c
.RI "R \fBoperator()\fP (A1 a)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoUF\fP< A1, R > & \fBf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class A1, class R> class eoSTLUF< A1, R >"
Generic set of classes that wrap an \fBeoF\fP, \fBeoUF\fP or \fBeoBF\fP so that they have the copy semantics the STL functions usually require (i.e. 

they can be passed by value, rather than the \fBEO\fP standard pass by reference).
.PP
The family consists of \fBeoSTLF\fP, eoSTLUF, \fBeoSTLBF\fP that modify \fBeoF\fP, \fBeoUF\fP and \fBeoBF\fP respectively 
.PP
Definition at line 78 of file eoSTLFunctor.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
