.TH "eoSurviveAndDie" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSurviveAndDie \- eoSurviveAndDie A pure abstract class, to store the howmany's  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSurviveAndDie.h>\fP
.PP
Inherits \fBeoBF< eoPop< EOT > &, eoPop< EOT > &, void >\fP.
.PP
Inherited by \fBeoDeterministicSurviveAndDie< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoSurviveAndDie\fP (double _survive, double _die, bool _interpret_as_rate=true)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBeoHowMany\fP \fBhowmanySurvive\fP"
.br
.ti -1c
.RI "\fBeoHowMany\fP \fBhowmanyDie\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoSurviveAndDie< EOT >"
eoSurviveAndDie A pure abstract class, to store the howmany's 
.PP
Definition at line 53 of file eoSurviveAndDie.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
