.TH "eoSubtreeXOver" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSubtreeXOver \- eoSubtreeXOver --> subtree xover  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <gp/eoParseTreeOp.h>\fP
.PP
Inherits \fBeoQuadOp< eoParseTree< FType, Node > >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBeoParseTree\fP< FType, Node > \fBEoType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoSubtreeXOver\fP (unsigned _max_length)"
.br
.RI "\fIConstructor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIthe ckassname \fP"
.ti -1c
.RI "virtual \fB~eoSubtreeXOver\fP ()"
.br
.RI "\fIDtor. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBEoType\fP &_eo1, \fBEoType\fP &_eo2)"
.br
.RI "\fIPerform crossover on two individuals param _eo1 The first parent individual param _eo2 The second parent individual. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBmax_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class FType, class Node> class eoSubtreeXOver< FType, Node >"
eoSubtreeXOver --> subtree xover 
.PP
Definition at line 42 of file eoParseTreeOp.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class FType, class Node> \fBeoSubtreeXOver\fP< FType, Node >::\fBeoSubtreeXOver\fP (unsigned _max_length)\fC [inline]\fP"
.PP
Constructor. 
.PP
\fBParameters:\fP
.RS 4
\fI_max_length\fP the maximum size of an individual 
.RE
.PP

.PP
Definition at line 50 of file eoParseTreeOp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
