.TH "eoSymInit" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoSymInit \- Default initializer, Koza style.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoSymInit.h>\fP
.PP
Inherits \fBeoInit< EoType >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoSymInit\fP (TreeBuilder &_builder)"
.br
.RI "\fIBy default build ramped half and half with max depth 6. \fP"
.ti -1c
.RI "\fBeoSymInit\fP (TreeBuilder &_builder, double &_grow_prob, unsigned &_max_depth)"
.br
.RI "\fIControl the grow_prob and max_depth externally. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBEoType\fP &tree)"
.br
.RI "\fIbuild the tree \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "TreeBuilder & \fBbuilder\fP"
.br
.ti -1c
.RI "double \fBown_grow_prob\fP"
.br
.ti -1c
.RI "unsigned \fBown_max_depth\fP"
.br
.ti -1c
.RI "double & \fBgrow_prob\fP"
.br
.ti -1c
.RI "unsigned & \fBmax_depth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EoType> class eoSymInit< EoType >"
Default initializer, Koza style. 
.PP
Definition at line 26 of file eoSymInit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
