.TH "eoTimeCounter" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoTimeCounter \- An \fBeoStat\fP that simply gives the user time since first generation It has to be tempatized by EOT because it must be an \fBeoStat\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoTimeCounter.h>\fP
.PP
Inherits \fBeoUpdater\fP, and \fBeoValueParam< double >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBoperator()\fP ()"
.br
.RI "\fIsimply stores the time spent in process in its \fBvalue()\fP \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "clock_t \fButime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An \fBeoStat\fP that simply gives the user time since first generation It has to be tempatized by EOT because it must be an \fBeoStat\fP. 
.PP
Definition at line 38 of file eoTimeCounter.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
