.TH "eoTimeVaryingLoopEval" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoTimeVaryingLoopEval \- \fBeoPopLoopEval\fP: an instance of \fBeoPopEvalFunc\fP that simply applies a private \fBeoEvalFunc\fP to all offspring AND ALL PARENTS as the fitness is supposed here to vary  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoPopEvalFunc.h>\fP
.PP
Inherits \fBeoPopEvalFunc< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoTimeVaryingLoopEval\fP (\fBeoEvalFunc\fP< \fBEOT\fP > &_eval)"
.br
.RI "\fICtor: set value of embedded \fBeoEvalFunc\fP. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_parents, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIDo the job: simple loop over the offspring. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoEvalFunc\fP< \fBEOT\fP > & \fBeval\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoTimeVaryingLoopEval< EOT >"
\fBeoPopLoopEval\fP: an instance of \fBeoPopEvalFunc\fP that simply applies a private \fBeoEvalFunc\fP to all offspring AND ALL PARENTS as the fitness is supposed here to vary 
.PP
Definition at line 84 of file eoPopEvalFunc.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
