.TH "eoTruncatedSelectOne" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoTruncatedSelectOne \- eoTruncatedSelectOne selects one individual using \fBeoSelectOne\fP as it's mechanism.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoTruncatedSelectOne.h>\fP
.PP
Inherits \fBeoSelectOne< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoTruncatedSelectOne\fP (\fBeoSelectOne\fP< \fBEOT\fP > &_select, double _rateFertile, bool _interpret_as_rateF=true)"
.br
.RI "\fICtor from rate and bool. \fP"
.ti -1c
.RI "\fBeoTruncatedSelectOne\fP (\fBeoSelectOne\fP< \fBEOT\fP > &_select, \fBeoHowMany\fP _howManyFertile)"
.br
.RI "\fICtor with \fBeoHowMany\fP. \fP"
.ti -1c
.RI "void \fBsetup\fP (const \fBeoPop\fP< \fBEOT\fP > &_source)"
.br
.RI "\fIsetup procedures: fills the temporary population with the fertile guys \fP"
.ti -1c
.RI "const \fBEOT\fP & \fBoperator()\fP (const \fBeoPop\fP< \fBEOT\fP > &_pop)"
.br
.RI "\fIThe implementation selects an individual from the fertile pop. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoSelectOne\fP< \fBEOT\fP > & \fBselect\fP"
.br
.ti -1c
.RI "\fBeoHowMany\fP \fBhowManyFertile\fP"
.br
.ti -1c
.RI "\fBeoPop\fP< \fBEOT\fP > \fBtmpPop\fP"
.br
.ti -1c
.RI "\fBeoPop\fP< \fBEOT\fP > & \fBactualPop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoTruncatedSelectOne< EOT >"
eoTruncatedSelectOne selects one individual using \fBeoSelectOne\fP as it's mechanism. 

Therefore eoTruncatedSelectOne needs an \fBeoSelectOne\fP in its ctor
.PP
It will perform selection only from the top guys in the population. 
.PP
Definition at line 45 of file eoTruncatedSelectOne.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT> const \fBEOT\fP& \fBeoTruncatedSelectOne\fP< \fBEOT\fP >::operator() (const \fBeoPop\fP< \fBEOT\fP > & _pop)\fC [inline, virtual]\fP"
.PP
The implementation selects an individual from the fertile pop. 
.PP
\fBParameters:\fP
.RS 4
\fI_source\fP the source population 
.br
\fI_dest\fP the selected guy 
.RE
.PP

.PP
Implements \fBeoUF< const eoPop< EOT > &, const EOT & >\fP.
.PP
Definition at line 98 of file eoTruncatedSelectOne.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
