.TH "eoTransform" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoTransform \- eoTransform transforms a population by applying genetic operators on it.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoTransform.h>\fP
.PP
Inherits \fBeoUF< eoPop< EOT > &, void >\fP.
.PP
Inherited by \fBeoDynSGATransform< EOT >\fP, eoEasyEA< EOT >::eoDummyTransform, and \fBeoSGATransform< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoTransform< EOT >"
eoTransform transforms a population by applying genetic operators on it. 
.PP
Definition at line 38 of file eoTransform.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
