.TH "eoTruncate" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoTruncate \- truncation method using sort  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoReduce.h>\fP
.PP
Inherits \fBeoReduce< EOT >< EOT >\fP.
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_newgen, unsigned _newsize)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoTruncate< EOT >"
truncation method using sort 
.PP
Definition at line 49 of file eoReduce.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
