.TH "eoUBitXover" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoUBitXover \- eoUBitXover --> classic Uniform crossover  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <ga/eoBitOp.h>\fP
.PP
Inherits \fBeoQuadOp< Chrom >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoUBitXover\fP (const float &_preference=0.5)"
.br
.RI "\fI(Default) Constructor. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIThe class name. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (Chrom &chrom1, Chrom &chrom2)"
.br
.RI "\fIUniform crossover for binary chromosomes. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBpreference\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class Chrom> class eoUBitXover< Chrom >"
eoUBitXover --> classic Uniform crossover 
.PP
Definition at line 274 of file eoBitOp.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class Chrom> bool \fBeoUBitXover\fP< Chrom >::operator() (Chrom & chrom1, Chrom & chrom2)\fC [inline, virtual]\fP"
.PP
Uniform crossover for binary chromosomes. 
.PP
\fBParameters:\fP
.RS 4
\fIchrom1\fP The first chromosome. 
.br
\fIchrom2\fP The first chromosome. ::runtime_error if sizes don't match 
.RE
.PP

.PP
Implements \fBeoBF< Chrom &, Chrom &, bool >\fP.
.PP
Definition at line 292 of file eoBitOp.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
