.TH "eoUniformGenerator" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoUniformGenerator \- The class eoUniform can be used in the STL generate function to easily generate random floats and doubles.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoRndGenerators.h>\fP
.PP
Inherits \fBeoRndGenerator< T >< T >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoUniformGenerator\fP (T _max=T(1.0), \fBeoRng\fP &_rng=rng)"
.br
.ti -1c
.RI "\fBeoUniformGenerator\fP (T _min, T _max, \fBeoRng\fP &_rng=rng)"
.br
.ti -1c
.RI "T \fBoperator()\fP (void)"
.br
.RI "\fIGenerates the number, uses a static_cast to get the right behaviour for ints and unsigneds. \fP"
.ti -1c
.RI "template<> bool \fBoperator()\fP (void)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "T \fBminim\fP"
.br
.ti -1c
.RI "T \fBrange\fP"
.br
.ti -1c
.RI "\fBeoRng\fP & \fBuniform\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T = double> class eoUniformGenerator< T >"
The class eoUniform can be used in the STL generate function to easily generate random floats and doubles. 

It can also be used for ints and unsigneds by virtue of the static_cast in the generator function.
.PP
Also present is a specialization for boolean, that will ignore the minima and maxima that are possibly set and will return an unbiased flip of a coin. For a biased flip, use the eoBoolean
.PP
either in [0, _max) if only 1 value (_max) is given (or none, as _max defaults to 1.0) or in [_min,_max) if 2 values are given (_min, _max) 
.PP
Definition at line 66 of file eoRndGenerators.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
