.TH "eoUniformGeneChooser" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoUniformGeneChooser \- Uniform choice of gene to delete.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoVariableLengthMutation.h>\fP
.PP
Inherits \fBeoGeneDelChooser< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "unsigned \fBoperator()\fP (\fBEOT\fP &_eo)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoUniformGeneChooser< EOT >"
Uniform choice of gene to delete. 
.PP
Definition at line 94 of file eoVariableLengthMutation.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
