.TH "eoUpdater" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoUpdater \- eoUpdater is a generic procudere for updating whatever you want.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoUpdater.h>\fP
.PP
Inherits \fBeoF< void >\fP.
.PP
Inherited by \fBeoCountedStateSaver\fP, \fBeoDynUpdater\fP, \fBeoIncrementor< T >\fP, \fBeoIncrementorParam< T >\fP, \fBeoTimeCounter\fP, and \fBeoTimedStateSaver\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBlastCall\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBclassName\fP (void) const "
.br
.in -1c
.SH "Detailed Description"
.PP 
eoUpdater is a generic procudere for updating whatever you want. 

Yet again an empty name 
.PP
Definition at line 39 of file eoUpdater.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
