.TH "eoVariableParetoTraits" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoVariableParetoTraits \- eoVariableParetoTraits : an \fBeoParetoFitnessTraits\fP whose characteristics can be set at run-time (nb objectives and min/max's) Why bother? For didactical purposes (and EASEA implementation :-)  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoParetoFitness.h>\fP
.PP
Inherits \fBeoParetoFitnessTraits\fP.
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetUp\fP (unsigned _n, std::vector< bool > &_b)"
.br
.RI "\fIsetting the static stuff \fP"
.ti -1c
.RI "unsigned \fBnObjectives\fP ()"
.br
.RI "\fIthe accessors \fP"
.ti -1c
.RI "bool \fBmaximizing\fP (unsigned _i)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnObj\fP"
.br
.ti -1c
.RI "std::vector< bool > \fBbObj\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
eoVariableParetoTraits : an \fBeoParetoFitnessTraits\fP whose characteristics can be set at run-time (nb objectives and min/max's) Why bother? For didactical purposes (and EASEA implementation :-) 
.PP
Definition at line 56 of file eoParetoFitness.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
