.TH "eoVlAddMutation" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoVlAddMutation \- Addition of a gene Is inserted at a random position - so can be applied to both order-dependent and order-independent.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoVariableLengthMutation.h>\fP
.PP
Inherits \fBeoMonOp< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::AtomType \fBAtomType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoVlAddMutation\fP (unsigned _nMax, \fBeoInit\fP< AtomType > &_atomInit)"
.br
.RI "\fIdefault ctor \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBEOT\fP &_eo)"
.br
.RI "\fIoperator: actually adds an Atom \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.RI "\fIinherited className \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnMax\fP"
.br
.ti -1c
.RI "\fBeoInit\fP< AtomType > & \fBatomInit\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoVlAddMutation< EOT >"
Addition of a gene Is inserted at a random position - so can be applied to both order-dependent and order-independent. 
.PP
Definition at line 48 of file eoVariableLengthMutation.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class EOT> \fBeoVlAddMutation\fP< \fBEOT\fP >::\fBeoVlAddMutation\fP (unsigned _nMax, \fBeoInit\fP< AtomType > & _atomInit)\fC [inline]\fP"
.PP
default ctor 
.PP
\fBParameters:\fP
.RS 4
\fInMax\fP max number of atoms 
.br
\fI_atomInit\fP an Atom initializer 
.RE
.PP

.PP
Definition at line 59 of file eoVariableLengthMutation.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
