.TH "eoVlUniformBinOp" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoVlUniformBinOp \- Direct Uniform Exchange of genes for Variable Length, BINARY version.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoVariableLengthCrossover.h>\fP
.PP
Inherits \fBeoBinOp< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::AtomType \fBAtomType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoVlUniformBinOp\fP (unsigned _Min, unsigned _Max, double _rate=0.5)"
.br
.ti -1c
.RI "bool \fBoperator()\fP (\fBEOT\fP &_eo1, const \fBEOT\fP &_eo2)"
.br
.RI "\fIThe pure virtual function that needs to be implemented by the subclass. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBMin\fP"
.br
.ti -1c
.RI "unsigned \fBMax\fP"
.br
.ti -1c
.RI "double \fBrate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoVlUniformBinOp< EOT >"
Direct Uniform Exchange of genes for Variable Length, BINARY version. 

A very primitive version, that does no verification at all!!! NEEDS to be improved - but no time now :-((( Especially, if both guys have maximal size, it will take some time to generate even 1 offspring that is not oversized!!! Also, we should first check for identical atoms, and copy them to the offspring, and only after that exchange the other ones (Radcliffe's RRR). 
.PP
Definition at line 280 of file eoVariableLengthCrossover.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
