.TH "eoVlDelMutation" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoVlDelMutation \- Deletion of a gene By default at a random position, but a 'chooser' can be specified can of course be applied to both order-dependent and order-independent.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoVariableLengthMutation.h>\fP
.PP
Inherits \fBeoMonOp< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::AtomType \fBAtomType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoVlDelMutation\fP (unsigned _nMin, \fBeoGeneDelChooser\fP< \fBEOT\fP > &_chooser)"
.br
.RI "\fIctor with an external gene chooser \fP"
.ti -1c
.RI "\fBeoVlDelMutation\fP (unsigned _nMin)"
.br
.RI "\fIctor with uniform gene chooser - the default \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBEOT\fP &_eo)"
.br
.RI "\fIDo the job (delete one gene). \fP"
.ti -1c
.RI "virtual std::string \fBclassName\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBnMin\fP"
.br
.ti -1c
.RI "\fBeoUniformGeneChooser\fP< \fBEOT\fP > \fBuChooser\fP"
.br
.ti -1c
.RI "\fBeoGeneDelChooser\fP< \fBEOT\fP > & \fBchooser\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoVlDelMutation< EOT >"
Deletion of a gene By default at a random position, but a 'chooser' can be specified can of course be applied to both order-dependent and order-independent. 
.PP
Definition at line 110 of file eoVariableLengthMutation.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class EOT> \fBeoVlDelMutation\fP< \fBEOT\fP >::\fBeoVlDelMutation\fP (unsigned _nMin, \fBeoGeneDelChooser\fP< \fBEOT\fP > & _chooser)\fC [inline]\fP"
.PP
ctor with an external gene chooser 
.PP
\fBParameters:\fP
.RS 4
\fInMin\fP min number of atoms to leave in the individual 
.br
\fI_geneChooser\fP an eoGeneCHooser to choose which one to delete 
.RE
.PP

.PP
Definition at line 121 of file eoVariableLengthMutation.h.
.SS "template<class EOT> \fBeoVlDelMutation\fP< \fBEOT\fP >::\fBeoVlDelMutation\fP (unsigned _nMin)\fC [inline]\fP"
.PP
ctor with uniform gene chooser - the default 
.PP
\fBParameters:\fP
.RS 4
\fInMin\fP min number of atoms to leave in the individual 
.RE
.PP

.PP
Definition at line 128 of file eoVariableLengthMutation.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT> bool \fBeoVlDelMutation\fP< \fBEOT\fP >::operator() (\fBEOT\fP & _eo)\fC [inline, virtual]\fP"
.PP
Do the job (delete one gene). 
.PP
\fBParameters:\fP
.RS 4
\fI_eo\fP the \fBEO\fP to mutate 
.RE
.PP

.PP
Implements \fBeoUF< EOT &, bool >\fP.
.PP
Definition at line 134 of file eoVariableLengthMutation.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
