.TH "eoWeakElitistReplacement" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoWeakElitistReplacement \- eoWeakElitistReplacement: a wrapper for other replacement procedures.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoReplacement.h>\fP
.PP
Inherits \fBeoReplacement< EOT >< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::Fitness \fBFitness\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoWeakElitistReplacement\fP (\fBeoReplacement\fP< \fBEOT\fP > &_replace)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< \fBEOT\fP > &_pop, \fBeoPop\fP< \fBEOT\fP > &_offspring)"
.br
.RI "\fIdo replacement \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoReplacement\fP< \fBEOT\fP > & \fBreplace\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class eoWeakElitistReplacement< EOT >"
eoWeakElitistReplacement: a wrapper for other replacement procedures. 

Copies in the new pop the best individual from the old pop, AFTER normal replacement, if the best of the new pop is worse than the best of the old pop. Removes the worse individual from the new pop. This could be changed by adding a selector there... 
.PP
Definition at line 102 of file eoReplacement.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
