.TH "EvolutionStrategies" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EvolutionStrategies \- 
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBeoEsChromInit< EOT >\fP"
.br
.RI "\fIRandom Es-chromosome initializer (therefore derived from \fBeoInit\fP). \fP"
.ti -1c
.RI "class \fBeoEsFull< Fit >\fP"
.br
.RI "\fIThe most complex evolutionary strategy representation. \fP"
.ti -1c
.RI "class \fBeoEsMutate< EOT >\fP"
.br
.RI "\fIES-style mutation in the large. \fP"
.ti -1c
.RI "class \fBeoEsMutationInit\fP"
.br
.RI "\fIInitialize Mutation operator. \fP"
.ti -1c
.RI "class \fBeoEsSimple< Fit >\fP"
.br
.RI "\fISimple Evolution Strategy. \fP"
.ti -1c
.RI "class \fBeoEsStdev< Fit >\fP"
.br
.RI "\fIEvolutionary Strategy with a standard deviation per parameter. \fP"
.ti -1c
.RI "class \fBeoIntBounds\fP"
.br
.RI "\fIDefines bound classes for real numbers. \fP"
.ti -1c
.RI "class \fBeoRealBounds\fP"
.br
.RI "\fIDefines bound classes for real numbers. \fP"
.in -1c
