.TH "gp_parse_tree::MemPool" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gp_parse_tree::MemPool \- Pool allocator for the subtree and parse tree classes (homebrew and not compliant to ANSI allocator requirements) (c) copyright Maarten Keijzer 1999, 2000.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <parse_tree.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemPool\fP (unsigned int sz)"
.br
.ti -1c
.RI "void * \fBallocate\fP ()"
.br
.ti -1c
.RI "void \fBdeallocate\fP (void *b)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBgrow\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Chunk * \fBchunks\fP"
.br
.ti -1c
.RI "const unsigned int \fBesize\fP"
.br
.ti -1c
.RI "Link * \fBhead\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pool allocator for the subtree and parse tree classes (homebrew and not compliant to ANSI allocator requirements) (c) copyright Maarten Keijzer 1999, 2000. 

Permission to copy, use, modify, sell and distribute this software is granted provided this copyright notice appears in all copies. This software is provided 'as is' without express or implied warranty, and with no claim as to its suitability for any purpose.
.PP
Permission to modify the code and to distribute modified code is granted, provided the above notices are retained, and a notice that the code was modified is included with the above copyright notice. 
.PP
Definition at line 185 of file parse_tree.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
