.TH "NodeSelector" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeSelector \- Base class for selecting nodes.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <NodeSelector.h>\fP
.PP
Inherited by \fBBiasedNodeSelector\fP, and \fBRandomNodeSelector\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual NodeSelection \fBselect_node\fP (Sym sym) const =0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for selecting nodes. 
.PP
Definition at line 24 of file NodeSelector.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
