.TH "normal_generator" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
normal_generator \- The class normal_generator can be used in the STL generate function to easily generate gaussian distributed floats and doubles.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <rnd_generators.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnormal_generator\fP (T _stdev=T(1.0), \fBeoRng\fP &_rng=rng)"
.br
.ti -1c
.RI "T \fBoperator()\fP (void)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "T \fBstdev\fP"
.br
.ti -1c
.RI "\fBeoRng\fP & \fBnormal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T = double> class normal_generator< T >"
The class normal_generator can be used in the STL generate function to easily generate gaussian distributed floats and doubles. 

The user can supply a standard deviation which defaults to 1. 
.PP
Definition at line 139 of file rnd_generators.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
