.TH "ParseTree" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseTree \- Various functions for tree-based Genetic Programming.  

.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBeoParseTree< FType, Node >\fP"
.br
.RI "\fIImplementation of parse-tree for genetic programming. \fP"
.ti -1c
.RI "class \fBeoParseTreeDepthInit< FType, Node >\fP"
.br
.RI "\fIeoParseTreeDepthInit : the initializer class for \fBeoParseTree\fP \fP"
.ti -1c
.RI "class \fBeoSubtreeXOver< FType, Node >\fP"
.br
.RI "\fIeoSubtreeXOver --> subtree xover \fP"
.ti -1c
.RI "class \fBeoBranchMutation< FType, Node >\fP"
.br
.RI "\fIeoBranchMutation --> replace a subtree with a randomly created subtree \fP"
.ti -1c
.RI "class \fBeoPointMutation< FType, Node >\fP"
.br
.RI "\fIeoPointMutation --> replace a Node with a Node of the same arity \fP"
.ti -1c
.RI "class \fBeoExpansionMutation< FType, Node >\fP"
.br
.RI "\fIeoExpansionMutation --> replace a terminal with a randomly created subtree \fP"
.ti -1c
.RI "class \fBeoCollapseSubtreeMutation< FType, Node >\fP"
.br
.RI "\fIeoCollapseSubtree --> replace a subtree with a randomly chosen terminal \fP"
.ti -1c
.RI "class \fBeoHoistMutation< FType, Node >\fP"
.br
.RI "\fIeoHoistMutation --> replace the individual with one of its subtree's \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class FType, class Node> void \fBeoInitRampedHalfAndHalf\fP (\fBeoPop\fP< \fBeoParseTree\fP< FType, Node > > &pop, unsigned int population_size, unsigned int init_max_depth, std::vector< Node > &initializor)"
.br
.RI "\fIA template function for ramped half and half initialization of an \fBeoParseTree\fP population. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Various functions for tree-based Genetic Programming. 
.PP
.SH "Function Documentation"
.PP 
.SS "template<class FType, class Node> void eoInitRampedHalfAndHalf (\fBeoPop\fP< \fBeoParseTree\fP< FType, Node > > & pop, unsigned int population_size, unsigned int init_max_depth, std::vector< Node > & initializor)"
.PP
A template function for ramped half and half initialization of an \fBeoParseTree\fP population. 
.PP
\fBParameters:\fP
.RS 4
\fIpop\fP the population to be created 
.br
\fIpopulation_size\fP the size of the population to be created 
.br
\fIinit_max_depth\fP the initial maximum tree depth 
.br
\fIinitializor\fP A std::vector containing the possible nodes 
.RE
.PP

.PP
Definition at line 179 of file eoParseTreeDepthInit.h.
