.TH "todo" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBClass \fBeoDominanceMap< EoType >\fP \fP" 1c
make it an \fBeoStat\fP? 
.PP
.PP
 
.IP "\fBMember \fBeoEsChromInit::create_self_adapt\fP(eoEsStdev< FitT > &result) \fP" 1c
Should we scale sigmas to the corresponding object variable range? 
.PP

