.TH "UF_random_generator" 3 "19 Oct 2006" "Version 0.9.4-cvs" "EO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UF_random_generator \- Another class \fBrandom_generator\fP that can be used in the STL random_shuffle function (see \fBeoPop::shuffle\fP): its operator() takes an unsigned argument m and must return an unsigned uniformly distributed in [0,m}.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <rnd_generators.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUF_random_generator\fP (\fBeoRng\fP &_rng=rng)"
.br
.ti -1c
.RI "T \fBoperator()\fP (T _t)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoRng\fP & \fBrandom\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T = uint32_t> class UF_random_generator< T >"
Another class \fBrandom_generator\fP that can be used in the STL random_shuffle function (see \fBeoPop::shuffle\fP): its operator() takes an unsigned argument m and must return an unsigned uniformly distributed in [0,m}. 
.PP
Definition at line 121 of file rnd_generators.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EO from the source code.
