.TH "peoSynchronousMultiStart::AbstractDataType" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-PEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoSynchronousMultiStart::AbstractDataType \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBpeoSynchronousMultiStart< EntityType >::DataType< Type >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~AbstractDataType\fP ()"
.br
.ti -1c
.RI "template<typename Type> \fBoperator Type &\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename EntityType> struct peoSynchronousMultiStart< EntityType >::AbstractDataType"

.PP
Definition at line 122 of file peoSynchronousMultiStart.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEOMovingObjects from the source code.
