.TH "Cooperative" 3 "4 Oct 2007" "Version 0.1" "ParadisEO-PEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cooperative \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBCommunicable\fP.
.PP
Inherited by \fBpeoAsyncIslandMig< EOT >\fP, and \fBpeoSyncIslandMig< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRunner\fP * \fBgetOwner\fP ()"
.br
.ti -1c
.RI "void \fBsetOwner\fP (\fBRunner\fP &__runner)"
.br
.ti -1c
.RI "void \fBsend\fP (\fBCooperative\fP *__coop)"
.br
.ti -1c
.RI "virtual void \fBnotifySending\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBRunner\fP * \fBowner\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file cooperative.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO from the source code.
