.TH "peoEvalFuncPSO" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-PEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoEvalFuncPSO \- \fBpeoEvalFuncPSO\fP: This class takes an existing function pointer and converts it into a evaluation function class.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <peoEvalFuncPSO.h>\fP
.PP
Inherits \fBeoEvalFunc< POT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpeoEvalFuncPSO\fP (FitT(*_eval)(FunctionArg))"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP (POT &_peo)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class POT, class FitT = typename POT::Fitness, class FunctionArg = const POT&> struct peoEvalFuncPSO< POT, FitT, FunctionArg >"
\fBpeoEvalFuncPSO\fP: This class takes an existing function pointer and converts it into a evaluation function class. 
.PP
Definition at line 24 of file peoEvalFuncPSO.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEOMovingObjects from the source code.
