.TH "peoPSO" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-PEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoPSO \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBRunner\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpeoPSO\fP (\fBeoContinue\fP< POT > &__cont, \fBpeoPopEval\fP< POT > &__pop_eval, \fBeoVelocity\fP< POT > &_velocity, \fBeoFlight\fP< POT > &_flight)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< POT > &__pop)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoContinue\fP< POT > & \fBcont\fP"
.br
.ti -1c
.RI "\fBpeoPopEval\fP< POT > & \fBpop_eval\fP"
.br
.ti -1c
.RI "\fBeoPop\fP< POT > * \fBpop\fP"
.br
.ti -1c
.RI "\fBeoVelocity\fP< POT > & \fBvelocity\fP"
.br
.ti -1c
.RI "\fBeoFlight\fP< POT > & \fBflight\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class POT> class peoPSO< POT >"

.PP
Definition at line 23 of file peoPSO.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEOMovingObjects from the source code.
