.TH "peoParallelAlgorithmWrapper::Algorithm< AlgorithmType, void >" 3 "11 Oct 2007" "Version 1.0" "ParadisEO-PEO:ParallelandDistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoParallelAlgorithmWrapper::Algorithm< AlgorithmType, void > \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBpeoParallelAlgorithmWrapper::AbstractAlgorithm\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlgorithm\fP (AlgorithmType &externalAlgorithm)"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AlgorithmType & \fBalgorithm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename AlgorithmType> struct peoParallelAlgorithmWrapper::Algorithm< AlgorithmType, void >"

.PP
Definition at line 95 of file peoParallelAlgorithmWrapper.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO:ParallelandDistributedEvolvingObjects from the source code.
