.TH "peoSynchronousMultiStart::AbstractAlgorithm" 3 "11 Oct 2007" "Version 1.0" "ParadisEO-PEO:ParallelandDistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoSynchronousMultiStart::AbstractAlgorithm \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBpeoSynchronousMultiStart< EntityType >::Algorithm< AlgorithmType >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~AbstractAlgorithm\fP ()"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP (\fBAbstractDataType\fP &dataTypeInstance)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename EntityType> struct peoSynchronousMultiStart< EntityType >::AbstractAlgorithm"

.PP
Definition at line 139 of file peoSynchronousMultiStart.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO:ParallelandDistributedEvolvingObjects from the source code.
