.TH "peoSynchronousMultiStart::Algorithm" 3 "11 Oct 2007" "Version 1.0" "ParadisEO-PEO:ParallelandDistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoSynchronousMultiStart::Algorithm \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBpeoSynchronousMultiStart< EntityType >::AbstractAlgorithm\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlgorithm\fP (AlgorithmType &externalAlgorithm)"
.br
.ti -1c
.RI "void \fBoperator()\fP (\fBAbstractDataType\fP &dataTypeInstance)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AlgorithmType & \fBalgorithm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename EntityType>template<typename AlgorithmType> struct peoSynchronousMultiStart< EntityType >::Algorithm< AlgorithmType >"

.PP
Definition at line 146 of file peoSynchronousMultiStart.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO:ParallelandDistributedEvolvingObjects from the source code.
