.TH "RingTopology" 3 "4 Oct 2007" "Version 0.1" "ParadisEO-PEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RingTopology \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBTopology\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetNeighbors\fP (\fBCooperative\fP *__mig, std::vector< \fBCooperative\fP * > &__from, std::vector< \fBCooperative\fP * > &__to)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file ring_topo.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO from the source code.
