.TH "SEND_REQUEST" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-PEOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SEND_REQUEST \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCommunicable\fP * \fBcomm\fP"
.br
.ti -1c
.RI "int \fBto\fP"
.br
.ti -1c
.RI "int \fBtag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file send.cpp.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEOMovingObjects from the source code.
