.TH "Topology" 3 "12 Oct 2007" "Version 1.0" "ParadisEO-PEO:ParallelandDistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Topology \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBRingTopology\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Topology\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (\fBCooperative\fP &__mig)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCooperative\fP * > \fBmig\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file topology.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO:ParallelandDistributedEvolvingObjects from the source code.
