.TH "moMoveIncrEval" 3 "20 Dec 2006" "Version 0.1" "PARADISEO-MO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moMoveIncrEval \- (generally) Efficient evaluation function based a move and a solution.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moMoveIncrEval.h>\fP
.PP
.SH "Detailed Description"
.PP 

.SS "template<class M> class moMoveIncrEval< M >"
(generally) Efficient evaluation function based a move and a solution. 

From a move and a solution, it computes a new fitness that could be associated to the solution if this one is updated. 
.PP
Definition at line 24 of file moMoveIncrEval.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for PARADISEO-MO from the source code.
