.TH "moMoveExpl" 3 "21 Dec 2006" "Version 0.1" "PARADISEO-MO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moMoveExpl \- Description of a move (\fBmoMove\fP) explorer.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moMoveExpl.h>\fP
.PP
Inherits \fBeoBF< const M::EOType &, M::EOType &, void >\fP.
.PP
Inherited by \fBmoMoveLoopExpl< M >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class M> class moMoveExpl< M >"
Description of a move (\fBmoMove\fP) explorer. 

Only a description...See \fBmoMoveLoopExpl\fP. 
.PP
Definition at line 21 of file moMoveExpl.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for PARADISEO-MO from the source code.
