.TH "moMoveInit" 3 "18 Apr 2007" "Version 0.1" "PARADISEO-MO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moMoveInit \- Move (\fBmoMove\fP) initializer.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moMoveInit.h>\fP
.PP
.SH "Detailed Description"
.PP 

.SS "template<class M> class moMoveInit< M >"
Move (\fBmoMove\fP) initializer. 

Class which allows to initiase a move. Only a description... An object that herits from this class needs to be designed to be used. 
.PP
Definition at line 22 of file moMoveInit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for PARADISEO-MO from the source code.
