.TH "moNoAspirCrit" 3 "18 Apr 2007" "Version 0.1" "PARADISEO-MO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moNoAspirCrit \- One of the possible aspiration criterion (\fBmoAspirCrit\fP).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moNoAspirCrit.h>\fP
.PP
Inherits \fBmoAspirCrit< M >< M >\fP.
.PP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const M &__move, const typename M::EOType::Fitness &__sol)"
.br
.RI "\fIFunction which describes the aspiration criterion behaviour. \fP"
.ti -1c
.RI "void \fBinit\fP ()"
.br
.RI "\fIProcedure which initialises all that needs a \fBmoNoAspirCrit\fP. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class M> class moNoAspirCrit< M >"
One of the possible aspiration criterion (\fBmoAspirCrit\fP). 

The simplest : never satisfied. 
.PP
Definition at line 21 of file moNoAspirCrit.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class M> bool \fBmoNoAspirCrit\fP< M >::operator() (const M & __move, const typename M::EOType::Fitness & __sol)\fC [inline, private]\fP"
.PP
Function which describes the aspiration criterion behaviour. 
.PP
Does nothing.
.PP
\fBParameters:\fP
.RS 4
\fI__move\fP a move. 
.br
\fI__sol\fP a fitness. 
.RE
.PP
\fBReturns:\fP
.RS 4
FALSE. 
.RE
.PP

.PP
Definition at line 32 of file moNoAspirCrit.h.
.SS "template<class M> void \fBmoNoAspirCrit\fP< M >::init ()\fC [inline, private, virtual]\fP"
.PP
Procedure which initialises all that needs a \fBmoNoAspirCrit\fP. 
.PP
Nothing... 
.PP
Implements \fBmoAspirCrit< M >\fP.
.PP
Definition at line 43 of file moNoAspirCrit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for PARADISEO-MO from the source code.
