.TH "moeoParetoSharing" 3 "15 Jan 2007" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoParetoSharing \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBeoPerf2Worth< EOT, worthT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoParetoSharing\fP (double _nicheSize)"
.br
.ti -1c
.RI "\fBmoeoParetoSharing\fP (double _nicheSize, \fBmoeoParetoPhenDist\fP< EOT, worthT > &_dist)"
.br
.ti -1c
.RI "void \fBoperator\fP ()(const \fBeoPop\fP< EOT > &_pop)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "double \fBsh\fP (double \fBdist\fP, double \fBDmax\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBnicheSize\fP"
.br
.ti -1c
.RI "\fBmoeoParetoPhenDist\fP< EOT, worthT > & \fBdist\fP"
.br
.ti -1c
.RI "\fBmoeoParetoEuclidDist\fP< EOT > \fBeuc_dist\fP"
.br
.ti -1c
.RI "double \fBDmax\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdMatrix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class worthT = double> class moeoParetoSharing< EOT, worthT >"

.PP
Definition at line 19 of file moeoParetoSharing.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
