.TH "moeoReplacement" 3 "16 Jan 2007" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoReplacement \- Replacement strategy for multi-objective optimization.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoReplacement.h>\fP
.PP
Inherits \fBeoReplacement< EOT >< EOT >\fP.
.PP
Inherited by \fBmoeoDisctinctElitistReplacement< EOT, WorthT >\fP, and \fBmoeoElitistReplacement< EOT, WorthT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class WorthT> class moeoReplacement< EOT, WorthT >"
Replacement strategy for multi-objective optimization. 
.PP
Definition at line 24 of file moeoReplacement.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
