.TH "eoVRPOnePointCrossover" 3 "7 Dec 2007" "Version 1.0" "CVRP-TW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoVRPOnePointCrossover \- Implementation of the simple One Point Crossover.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoVRPQuadCrossover.h>\fP
.PP
Inherits \fBeoQuadOp< eoVRP >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoVRPOnePointCrossover\fP ()"
.br
.RI "\fIDeafult constructor. \fP"
.ti -1c
.RI "std::string \fBclassName\fP () const "
.br
.RI "\fIReturns a string containing the name of the class. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (\fBeoVRP\fP &_genotype1, \fBeoVRP\fP &_genotype2)"
.br
.RI "\fIPerforms a one point crossover. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the simple One Point Crossover. 
.PP
Definition at line 159 of file eoVRPQuadCrossover.h.
.SH "Member Function Documentation"
.PP 
.SS "std::string eoVRPOnePointCrossover::className (void) const\fC [inline, virtual]\fP"
.PP
Returns a string containing the name of the class. 
.PP
Used to display statistics. 
.PP
\fBReturns:\fP
.RS 4
The string containing the name of the class. 
.RE
.PP

.PP
Reimplemented from \fBeoQuadOp< eoVRP >\fP.
.PP
Definition at line 177 of file eoVRPQuadCrossover.h.
.SS "bool eoVRPOnePointCrossover::operator() (\fBeoVRP\fP & _genotype1, \fBeoVRP\fP & _genotype2)\fC [inline, virtual]\fP"
.PP
Performs a one point crossover. 
.PP
Both parameters are the parents and the (future) children of the crossover. 
.PP
\fBParameters:\fP
.RS 4
\fI_genotype1\fP The first parent. 
.br
\fI_genotype2\fP The second parent. 
.RE
.PP
\fBReturns:\fP
.RS 4
True if any of the parents was modified. False otherwise. 
.RE
.PP

.PP
Implements \fBeoBF< eoVRP &, eoVRP &, bool >\fP.
.PP
Definition at line 191 of file eoVRPQuadCrossover.h.
.PP
References eoVRP::cleanRoutes(), and eoRng::random().

.SH "Author"
.PP 
Generated automatically by Doxygen for CVRP-TW from the source code.
