.TH "eoVRPEvalFunc" 3 "7 Dec 2007" "Version 1.0" "CVRP-TW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoVRPEvalFunc \- Evaluates an individual of type \fBeoVRP\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoVRPEvalFunc.h>\fP
.PP
Inherits \fBeoEvalFunc< eoVRP >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeoVRPEvalFunc\fP ()"
.br
.RI "\fIConstructor: nothing to do here. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBeoVRP\fP &_eo)"
.br
.RI "\fIComputes the (penalized) fitness. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Evaluates an individual of type \fBeoVRP\fP. 
.PP
Definition at line 54 of file eoVRPEvalFunc.h.
.SH "Member Function Documentation"
.PP 
.SS "void eoVRPEvalFunc::operator() (\fBeoVRP\fP & _eo)\fC [inline]\fP"
.PP
Computes the (penalized) fitness. 
.PP
\fBParameters:\fP
.RS 4
\fI_eo\fP The individual to be evaluated. 
.RE
.PP

.PP
Definition at line 72 of file eoVRPEvalFunc.h.
.PP
References eoVRP::decode(), eoVRP::decoded(), EO< F >::fitness(), EO< F >::invalid(), and eoVRP::length().

.SH "Author"
.PP 
Generated automatically by Doxygen for CVRP-TW from the source code.
