.TH "TwoOptNext" 3 "30 Dec 2006" "Version 0.1" "ParadisEO-PEO - Lessons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TwoOptNext \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (\fBTwoOpt\fP &__move, const Route &__route)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file two_opt_next.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO - Lessons from the source code.
