.TH "eoVRPUtils::ClientData" 3 "7 Dec 2007" "Version 1.0" "CVRP-TW" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoVRPUtils::ClientData \- Information regarding each client in the dataset.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoVRPUtils.h>\fP
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBid\fP"
.br
.RI "\fIClient ID number. \fP"
.ti -1c
.RI "double \fBx\fP"
.br
.RI "\fIClient's 'x' position in the map. \fP"
.ti -1c
.RI "double \fBy\fP"
.br
.RI "\fIClient's 'y' position in the map. \fP"
.ti -1c
.RI "double \fBdemand\fP"
.br
.RI "\fIClient's demand of delivered product. \fP"
.ti -1c
.RI "double \fBreadyTime\fP"
.br
.RI "\fIClient's beginning of the time window. \fP"
.ti -1c
.RI "double \fBdueTime\fP"
.br
.RI "\fIClient's end of the time window. \fP"
.ti -1c
.RI "double \fBserviceTime\fP"
.br
.RI "\fIClient's service time (time needed to serve the product). \fP"
.in -1c
.SH "Detailed Description"
.PP 
Information regarding each client in the dataset. 

This structure is intended to be used to store the information of each client read from the data file. 
.PP
Definition at line 86 of file eoVRPUtils.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for CVRP-TW from the source code.
