.TH "EmptySelection" 3 "20 Sep 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EmptySelection \- Special class that describes the case of no selection.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moMoveSelect.h>\fP
.PP
.SH "Detailed Description"
.PP 
Special class that describes the case of no selection. 

This class is used as an exception that can be thrown if a solution selector has completly failed. 
.PP
Definition at line 21 of file moMoveSelect.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
