.TH "moAlgo" 3 "15 Jan 2008" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moAlgo \- Description of an algorithm of the paradiseo-mo library.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moAlgo.h>\fP
.PP
Inherits \fBeoMonOp< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class moAlgo< EOT >"
Description of an algorithm of the paradiseo-mo library. 

\fBmoHC\fP, \fBmoTS\fP and \fBmoSA\fP are 3 examples of algorithm of the paradiseo-mo library. 
.PP
Definition at line 46 of file moAlgo.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
