.TH "moCoolingSchedule" 3 "3 Aug 2007" "Version 0.1" "PARADISEO-MO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moCoolingSchedule \- This class gives the description of a cooling schedule.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moCoolingSchedule.h>\fP
.PP
Inherits \fBeoUF< double &, bool >\fP.
.PP
Inherited by \fBmoExponentialCoolingSchedule\fP, and \fBmoLinearCoolingSchedule\fP.
.PP
.SH "Detailed Description"
.PP 
This class gives the description of a cooling schedule. 

It is only a description... An object that herits from this class is needed to be used in a \fBmoSA\fP. See \fBmoExponentialCoolingSchedule\fP or \fBmoLinearCoolingSchedule\fP for example. 
.PP
Definition at line 22 of file moCoolingSchedule.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for PARADISEO-MO from the source code.
