.TH "moComparator" 3 "15 Jan 2008" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moComparator \- Template for classes which need to compare two EOT and indicate if the first is 'better' than the second.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moComparator.h>\fP
.PP
Inherits \fBeoBF< A1, A2, R >< const const EOT &, EOT &, bool >\fP.
.PP
Inherited by \fBmoFitComparator< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class moComparator< EOT >"
Template for classes which need to compare two EOT and indicate if the first is 'better' than the second. 

The objects that extend this template describe how an EOT is 'better' than an other. 
.PP
Definition at line 45 of file moComparator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
