.TH "moExponentialCoolingSchedule" 3 "27 Jun 2007" "Version 0.1" "PARADISEO-MO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moExponentialCoolingSchedule \- One of the possible \fBmoCoolingSchedule\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moExponentialCoolingSchedule.h>\fP
.PP
Inherits \fBmoCoolingSchedule\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoExponentialCoolingSchedule\fP (double __threshold, double __ratio)"
.br
.RI "\fISimple constructor. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (double &__temp)"
.br
.RI "\fIFunction which proceeds to the cooling. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBthreshold\fP"
.br
.RI "\fIThe temperature threhold. \fP"
.ti -1c
.RI "double \fBratio\fP"
.br
.RI "\fIThe decreasing factor of the temperature. \fP"
.in -1c
.SH "Detailed Description"
.PP 
One of the possible \fBmoCoolingSchedule\fP. 

An other very simple cooling schedule, the temperature decrease according to a ratio while the temperature is greater than a given threshold. 
.PP
Definition at line 22 of file moExponentialCoolingSchedule.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "moExponentialCoolingSchedule::moExponentialCoolingSchedule (double __threshold, double __ratio)\fC [inline]\fP"
.PP
Simple constructor. 
.PP
\fBParameters:\fP
.RS 4
\fI__threshold\fP the threshold. 
.br
\fI__ratio\fP the ratio used to descrease the temperature. 
.RE
.PP

.PP
Definition at line 31 of file moExponentialCoolingSchedule.h.
.SH "Member Function Documentation"
.PP 
.SS "bool moExponentialCoolingSchedule::operator() (double & __temp)\fC [inline, virtual]\fP"
.PP
Function which proceeds to the cooling. 
.PP
It decreases the temperature and indicates if it is greater than the threshold.
.PP
\fBParameters:\fP
.RS 4
\fI__temp\fP the current temperature. 
.RE
.PP
\fBReturns:\fP
.RS 4
if the new temperature (current temperature * ratio) is greater than the threshold. 
.RE
.PP

.PP
Implements \fBeoUF< double &, bool >\fP.
.PP
Definition at line 41 of file moExponentialCoolingSchedule.h.
.PP
References ratio, and threshold.

.SH "Author"
.PP 
Generated automatically by Doxygen for PARADISEO-MO from the source code.
