.TH "moExponentialCoolingSchedule" 3 "15 Jan 2008" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moExponentialCoolingSchedule \- One of the possible \fBmoCoolingSchedule\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moExponentialCoolingSchedule.h>\fP
.PP
Inherits \fBmoCoolingSchedule\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoExponentialCoolingSchedule\fP (double _threshold, double _ratio)"
.br
.RI "\fISimple constructor. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (double &_temperature)"
.br
.RI "\fI\fBFunction\fP which proceeds to the cooling. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBthreshold\fP"
.br
.RI "\fIThe temperature threhold. \fP"
.ti -1c
.RI "double \fBratio\fP"
.br
.RI "\fIThe decreasing factor of the temperature. \fP"
.in -1c
.SH "Detailed Description"
.PP 
One of the possible \fBmoCoolingSchedule\fP. 

An other very simple cooling schedule, the temperature decrease according to a ratio while the temperature is greater than a given threshold. 
.PP
Definition at line 46 of file moExponentialCoolingSchedule.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "moExponentialCoolingSchedule::moExponentialCoolingSchedule (double _threshold, double _ratio)\fC [inline]\fP"
.PP
Simple constructor. 
.PP
\fBParameters:\fP
.RS 4
\fI_threshold\fP the threshold. 
.br
\fI_ratio\fP the ratio used to descrease the temperature. 
.RE
.PP

.PP
Definition at line 55 of file moExponentialCoolingSchedule.h.
.SH "Member Function Documentation"
.PP 
.SS "bool moExponentialCoolingSchedule::operator() (double & _temperature)\fC [inline, virtual]\fP"
.PP
\fBFunction\fP which proceeds to the cooling. 
.PP
It decreases the temperature and indicates if it is greater than the threshold.
.PP
\fBParameters:\fP
.RS 4
\fI_temperature\fP the current temperature. 
.RE
.PP
\fBReturns:\fP
.RS 4
if the new temperature (current temperature * ratio) is greater than the threshold. 
.RE
.PP

.PP
Implements \fBeoUF< double &, bool >\fP.
.PP
Definition at line 65 of file moExponentialCoolingSchedule.h.
.PP
References ratio, and threshold.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
