.TH "moFitComparator" 3 "15 Jan 2008" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moFitComparator \- Comparison according to the fitness.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moFitComparator.h>\fP
.PP
Inherits \fBmoComparator< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const EOT &_solution1, const EOT &_solution2)"
.br
.RI "\fI\fBFunction\fP which makes the comparison and gives the result. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class moFitComparator< EOT >"
Comparison according to the fitness. 

An EOT is better than an other if its fitness is better. 
.PP
Definition at line 46 of file moFitComparator.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT> bool \fBmoFitComparator\fP< EOT >::operator() (const EOT & _solution1, const EOT & _solution2)\fC [inline]\fP"
.PP
\fBFunction\fP which makes the comparison and gives the result. 
.PP
\fBParameters:\fP
.RS 4
\fI_solution1\fP The first solution. 
.br
\fI_solution2\fP The second solution. 
.RE
.PP
\fBReturns:\fP
.RS 4
true if the fitness of the first solution is better than the second solution, false else. 
.RE
.PP

.PP
Definition at line 56 of file moFitComparator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
