.TH "moGenSolContinue" 3 "31 Jul 2007" "Version 0.1" "PARADISEO-MO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moGenSolContinue \- One possible stopping criterion for a solution-based heuristic.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moGenSolContinue.h>\fP
.PP
Inherits \fBmoSolContinue< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoGenSolContinue\fP (unsigned int __maxNumGen)"
.br
.RI "\fIBasic constructor. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (const EOT &__sol)"
.br
.RI "\fIFunction that activates the stop criterion. \fP"
.ti -1c
.RI "void \fBinit\fP ()"
.br
.RI "\fIProcedure which allows to initialise all the stuff needed. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBmaxNumGen\fP"
.br
.RI "\fIIteration maximum number. \fP"
.ti -1c
.RI "unsigned int \fBnumGen\fP"
.br
.RI "\fIIteration current number. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class moGenSolContinue< EOT >"
One possible stopping criterion for a solution-based heuristic. 

The stopping criterion corresponds to a maximum number of iteration. 
.PP
Definition at line 21 of file moGenSolContinue.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class EOT> \fBmoGenSolContinue\fP< EOT >::\fBmoGenSolContinue\fP (unsigned int __maxNumGen)\fC [inline]\fP"
.PP
Basic constructor. 
.PP
\fBParameters:\fP
.RS 4
\fI__maxNumGen\fP the maximum number of generation. 
.RE
.PP

.PP
Definition at line 30 of file moGenSolContinue.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT> bool \fBmoGenSolContinue\fP< EOT >::operator() (const EOT & __sol)\fC [inline, virtual]\fP"
.PP
Function that activates the stop criterion. 
.PP
Increments the counter and returns true if the current number of iteration is lower than the given maximum number of iterations.
.PP
\fBParameters:\fP
.RS 4
\fI__sol\fP the current solution. 
.RE
.PP
\fBReturns:\fP
.RS 4
true or false according to the current generation number. 
.RE
.PP

.PP
Implements \fBeoUF< const EOT &, bool >\fP.
.PP
Definition at line 42 of file moGenSolContinue.h.
.PP
References moGenSolContinue< EOT >::maxNumGen, and moGenSolContinue< EOT >::numGen.

.SH "Author"
.PP 
Generated automatically by Doxygen for PARADISEO-MO from the source code.
