.TH "moMoveInit" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moMoveInit \- Move (\fBmoMove\fP) initializer.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moMoveInit.h>\fP
.PP
Inherits \fBeoBF< A1, A2, R >< const M &, M::EOType &, void >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class M> class moMoveInit< M >"
Move (\fBmoMove\fP) initializer. 

Class which allows to initiase a move. Only a description... An object that herits from this class needs to be designed to be used. 
.PP
Definition at line 47 of file moMoveInit.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
