.TH "moMoveIncrEval" 3 "8 Oct 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moMoveIncrEval \- (generally) Efficient evaluation function based a move and a solution.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moMoveIncrEval.h>\fP
.PP
Inherits \fBeoBF< A1, A2, R >< const const M &, M::EOType &, M::EOType::Fitness >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class M> class moMoveIncrEval< M >"
(generally) Efficient evaluation function based a move and a solution. 

From a move and a solution, it computes a new fitness that could be associated to the solution if this one is updated. 
.PP
Definition at line 49 of file moMoveIncrEval.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
