.TH "moMoveIncrEval" 3 "20 Sep 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moMoveIncrEval \- (generally) Efficient evaluation function based a move and a solution.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moMoveIncrEval.h>\fP
.PP
.SH "Detailed Description"
.PP 

.SS "template<class M> class moMoveIncrEval< M >"
(generally) Efficient evaluation function based a move and a solution. 

From a move and a solution, it computes a new fitness that could be associated to the solution if this one is updated. 
.PP
Definition at line 24 of file moMoveIncrEval.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
