.TH "moNextMove" 3 "2 Aug 2007" "Version 0.1" "PARADISEO-MO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moNextMove \- Class which allows to generate a new move (\fBmoMove\fP).  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moNextMove.h>\fP
.PP
Inherits \fBeoBF< M &, const M::EOType &, bool >\fP.
.PP
Inherited by \fBmoItRandNextMove< M >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class M> class moNextMove< M >"
Class which allows to generate a new move (\fBmoMove\fP). 

Useful for the explorer (for \fBmoTS\fP or \fBmoHC\fP). Does nothing... An object that herits from this class needs to be designed for being used. 
.PP
Definition at line 22 of file moNextMove.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for PARADISEO-MO from the source code.
