.TH "moRandMove" 3 "23 Oct 2007" "Version 1.0" "ParadisEO-MOMovingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moRandMove \- Random move generator.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moRandMove.h>\fP
.PP
Inherits \fBeoUF< M &, void >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class M> class moRandMove< M >"
Random move generator. 

Only a description... An object that herits from this class needs to be designed in order to use a \fBmoSA\fP. 
.PP
Definition at line 46 of file moRandMove.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOMovingObjects from the source code.
