.TH "Communicable" 3 "30 Dec 2006" "Version 0.1" "ParadisEO-PEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Communicable \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBCooperative\fP, \fBRunner\fP, \fBService\fP, and \fBWorker\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommunicable\fP ()"
.br
.ti -1c
.RI "virtual \fB~Communicable\fP ()"
.br
.ti -1c
.RI "COMM_ID \fBgetKey\fP ()"
.br
.ti -1c
.RI "void \fBlock\fP ()"
.br
.ti -1c
.RI "void \fBunlock\fP ()"
.br
.ti -1c
.RI "void \fBstop\fP ()"
.br
.ti -1c
.RI "void \fBresume\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "COMM_ID \fBkey\fP"
.br
.ti -1c
.RI "sem_t \fBsem_lock\fP"
.br
.ti -1c
.RI "sem_t \fBsem_stop\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static unsigned \fBnum_comm\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file communicable.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO from the source code.
