.TH "Thread" 3 "7 Jan 2007" "Version 0.1" "ParadisEO-PEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Thread \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBReactiveThread\fP, and \fBRunner\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBThread\fP ()"
.br
.ti -1c
.RI "virtual \fB~Thread\fP ()"
.br
.ti -1c
.RI "void \fBsetActive\fP ()"
.br
.ti -1c
.RI "void \fBsetPassive\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBact\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file thread.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO from the source code.
