.TH "Topology" 3 "20 Dec 2006" "ParadisEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Topology \- 
.SH SYNOPSIS
.br
.PP
Inherited by \fBRingTopology\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~Topology\fP ()"
.br
.ti -1c
.RI "void \fBadd\fP (\fBCooperative\fP &__mig)"
.br
.ti -1c
.RI "virtual void \fBsetNeighbors\fP (\fBCooperative\fP *__mig, std::vector< \fBCooperative\fP * > &__from, std::vector< \fBCooperative\fP * > &__to)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCooperative\fP * > \fBmig\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file topology.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO from the source code.
