.TH "peoAggEvalFunc" 3 "29 Feb 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoAggEvalFunc \- The \fBpeoAggEvalFunc\fP class offers only the interface for creating aggregate evaluation functions - there are no direct internal functions provided.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <peoAggEvalFunc.h>\fP
.PP
Inherits \fBeoBF< A1, A2, R >< const EOT &, EOT::Fitness &, void >\fP.
.PP
Inherited by \fBMergeRouteEval\fP, and \fBpeoNoAggEvalFunc< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class peoAggEvalFunc< EOT >"
The \fBpeoAggEvalFunc\fP class offers only the interface for creating aggregate evaluation functions - there are no direct internal functions provided. 

The class inherits \fBpublic eoBF< EOT&, const typename EOT :: Fitness&, void >\fP thus requiring, for the derived classes, the creation of a function having the following signature:
.PP
void operator()( EOT& __eot, const typename EOT :: Fitness& __partial_fittness );      
.PP
The aggregation object is called in an iterative manner for each of the results obtained by applying partial evaluation functions. 
.PP
Definition at line 53 of file peoAggEvalFunc.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
