.TH "ReactiveThread" 3 "29 Feb 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReactiveThread \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBThread\fP.
.PP
Inherited by \fBCommunicator\fP, and \fBWorker\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReactiveThread\fP ()"
.br
.ti -1c
.RI "void \fBsleep\fP ()"
.br
.ti -1c
.RI "void \fBwakeUp\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "sem_t \fBsem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 45 of file reac_thread.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
