.TH "Runner" 3 "29 Feb 2008" "Version 1.1" "ParadisEO-PEO-ParallelanddistributedEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Runner \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBCommunicable\fP, and \fBThread\fP.
.PP
Inherited by \fBpeoWrapper\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRunner\fP ()"
.br
.ti -1c
.RI "RUNNER_ID \fBgetDefinitionID\fP ()"
.br
.ti -1c
.RI "RUNNER_ID \fBgetExecutionID\fP ()"
.br
.ti -1c
.RI "void \fBsetExecutionID\fP (const RUNNER_ID &execution_id)"
.br
.ti -1c
.RI "bool \fBisAssignedLocally\fP ()"
.br
.ti -1c
.RI "void \fBwaitStarting\fP ()"
.br
.ti -1c
.RI "void \fBwaitContextInitialization\fP ()"
.br
.ti -1c
.RI "void \fBstart\fP ()"
.br
.ti -1c
.RI "void \fBterminate\fP ()"
.br
.ti -1c
.RI "void \fBnotifyContextInitialized\fP ()"
.br
.ti -1c
.RI "void \fBnotifySendingTermination\fP ()"
.br
.ti -1c
.RI "void \fBpackTermination\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "sem_t \fBsem_start\fP"
.br
.ti -1c
.RI "sem_t \fBsem_cntxt\fP"
.br
.ti -1c
.RI "unsigned \fBdef_id\fP"
.br
.ti -1c
.RI "unsigned \fBexec_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file runner.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO-ParallelanddistributedEvolvingObjects from the source code.
