peoSyncIslandMig< EOT > Class Template Reference
The peoSyncIslandMig(p.) class offers the elementary basis for implementating a synchronous island migration model - requires the specification of several basic parameters, i.e.
#include <peoSyncIslandMig.h>
Public Member Functions
peoSyncIslandMig (unsigned __frequency, eoSelect< EOT > &__select, eoReplacement< EOT > &__replace, Topology &__topology, eoPop< EOT > &__source, eoPop< EOT > &__destination)
Constructor for the peoSyncIslandMig(p.) class; the characteristics of the migration model are defined through the specified parameters - out of the box objects provided in EO, etc., or custom, derived objects may be passed as parameters.
void operator() ()
Function operator to be called as checkpoint for performing the migration step.
void pack ()
Auxiliary function dealing with sending the emigrant individuals. There is no need to explicitly call the function.
void unpack ()
Auxiliary function dealing with receiving immigrant individuals. There is no need to explicitly call the function.
void notifySending ()
Auxiliary function dealing with migration notifications. There is no need to explicitly call the function.
Private Member Functions
void emigrate ()
void immigrate ()
Private Attributes
eoPeriodicContinue< EOT > cont
eoSelect< EOT > & select
eoReplacement< EOT > & replace
Topology & topology
eoPop< EOT > & source
eoPop< EOT > & destination
std::queue< eoPop< EOT > > imm
std::queue< eoPop< EOT > > em
std::queue< Cooperative * > coop_em
sem_t sync
Detailed Description
template<class EOT> class peoSyncIslandMig< EOT >
The peoSyncIslandMig(p.) class offers the elementary basis for implementating a synchronous island migration model - requires the specification of several basic parameters, i.e.
frequency of the migrations, selection and replacement strategies, a topological model and the source and destination population for the migrating individuals. The main difference as opposed to the asynchronous migration model is the synchronization step performed after selecting and sending the emigrant individuals.
The migration operator is called at the end of each generation of an evolutionary algorithms as a checkpoint object - the following code exposes the structure of a classic evolutionary algorithm:
do {
         select(population, offsprings); // select the offsprings from the current population
         transform(offsprings); // crossover and mutation operators are applied on the selected offsprings
         evaluate(offsprings); // evaluation step of the resulting offspring
         replace(population, offsprings); // replace the individuals in the current population whith individuals from the offspring population, according to a specified replacement strategy
} while (eaCheckpointContinue(population)); // checkpoint operators are applied on the current population, including the migration operator, if any specified
Constructing a synchronous island migration model requires having defined (1) a topological migration model, (2) the control parameters of the migration process, (3) a checkpoint object associated with an evolutionary algorithm, and (4) an owner object must be set. The owner object must be derived from the Runner(p.) class (for example a peoEA(p.) object represents a possible owner). A simple example is offered bellow:
topological model to be followed when performing migrations:
RingTopology(p.) migTopology; // a simple ring topological model - each island communicates with two other islands
the continuation criterion, selection and replacement strategy etc. are defined:
eoPop< EOT > population(POP_SIZE, popInitializer); // population of individuals to be used for the evolutionary algorithm
eoRandomSelect< EOT > migSelectStrategy; // selection strategy - in this case a random selection is applied
eoSelectNumber< EOT > migSelect(migSelectStrategy, MIG_SIZE); // number of individuals to be selected using the specified strategy
eoPlusReplacement< EOT > migReplace; // immigration strategy - the worse individuals in the destination population are replaced by the immigrant individuals
peoSyncIslandMig< EOT > syncMigration(
          MIG_FREQ, migSelect, migReplace, migTopology,
          population, population
); // synchronous migration object - the emigrant individuals are selected from the same from population in which the immigrant individuals are being integrated
creation of a checkpoint object as part of the definition of an evolutionary algoritm (details of th EA not given as being out of scope):
...
eoGenContinue< EOT > eaCont(NUM_GEN); // the evolutionary algorithm will stop after NUM_GEN generations
eoCheckPoint< EOT > eaCheckpointContinue(eaCont); // number of individuals to be selected using the specified strategy
...
eaCheckpointContinue.add(syncMigration); // adding the migration operator as checkpoint element
...
definition of an owner evolutionary algorithm (an object inheriting the Runner(p.) class):
peoEA< EOT > eaAlg(eaCheckpointContinue, eaPopEval, eaSelect, eaTransform, eaReplace); // evolutionary algorithm having as checkpoint the eaCheckpointContinue object defined above
syncMigration.setOwner(eaAlg); // setting the evolutionary algorithm as owner of the migration object
eaAlg(population); // applying the evolutionary algorithm on a given population
The source and the destination population for the migration object were specified as being the same, in step no. 2, as we are usually interested in selecting the emigrants and integrating the immigrant individuals from and in, respectively, one unique population, iteratively evolved by an evolutionary algorithm. There is no restriction in having two distinct populations as source and destination for the emigrant and immigrant individuals respectively.
The above steps only create a synchronous migration object associated to an evolutionary algorithm. The creation of several islands requires the reiteration of the steps 2 through 4 for creating distinct algorithms, with distinct populations and the associated distinctly parametrized migration objects. The interconnecting element is the underlying topology, defined at step 1 (the same C++ migTopology object has to be passed as parameter for all the migration objects, in order to interconnect them).
Definition at line 129 of file peoSyncIslandMig.h.
Constructor & Destructor Documentation
template<class EOT> peoSyncIslandMig< EOT >::peoSyncIslandMig (unsigned __frequency, eoSelect< EOT > & __select, eoReplacement< EOT > & __replace, Topology & __topology, eoPop< EOT > & __source, eoPop< EOT > & __destination)
Constructor for the peoSyncIslandMig(p.) class; the characteristics of the migration model are defined through the specified parameters - out of the box objects provided in EO, etc., or custom, derived objects may be passed as parameters.
Parameters:
unsigned __frequency - frequency of the migrations - the migrations occur periodically;
eoSelect< EOT >& __select - selection strategy to be applied for constructing a list of emigrant individuals out of the source population;
eoReplacement< EOT >& __replace - replacement strategy used for integrating the immigrant individuals in the destination population;
Topology& __topology - topological model to be followed when performing migrations;
eoPop< EOT >& __source - source population from which the emigrant individuals are selected;
eoPop< EOT >& __destination - destination population in which the immigrant population are integrated.
Definition at line 193 of file peoSyncIslandMig.h.
References Topology::add(), and peoSyncIslandMig< EOT >::sync.
Member Function Documentation
template<class EOT> void peoSyncIslandMig< EOT >::operator() ()
Function operator to be called as checkpoint for performing the migration step.
The emigrant individuals are selected from the source population and sent to the next island (defined by the topology object) while the immigrant individuals are integrated in the destination population. There is no need to explicitly call the function - the wrapper checkpoint object (please refer to the above example) will perform the call when required.
Definition at line 267 of file peoSyncIslandMig.h.
References peoSyncIslandMig< EOT >::cont, peoSyncIslandMig< EOT >::emigrate(), Cooperative::getOwner(), peoSyncIslandMig< EOT >::immigrate(), Thread::setActive(), peoSyncIslandMig< EOT >::source, Communicable::stop(), and peoSyncIslandMig< EOT >::sync.
The documentation for this class was generated from the following file:
peoSyncIslandMig.h