.TH "FlowShop" 3 "29 Feb 2008" "Version 1.1" "ParadisEO-MOEO-MultiObjectiveEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlowShop \- Structure of the genotype for the flow-shop scheduling problem: a vector of unsigned int int.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <FlowShop.h>\fP
.PP
Inherits \fBmoeoVector< MOEOObjectiveVector, MOEOFitness, MOEODiversity, GeneType >< moeoRealObjectiveVector< FlowShopObjectiveVectorTraits >, double, double, unsigned int >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBclassName\fP () const "
.br
.RI "\fIclass name \fP"
.in -1c
.SH "Detailed Description"
.PP 
Structure of the genotype for the flow-shop scheduling problem: a vector of unsigned int int. 
.PP
Definition at line 47 of file FlowShop.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO-MultiObjectiveEvolvingObjects from the source code.
