.TH "moeoIBMOLS::OneObjectiveComparator" 3 "29 Feb 2008" "Version 1.1" "ParadisEO-MOEO-MultiObjectiveEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoIBMOLS::OneObjectiveComparator \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBmoeoComparator< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOneObjectiveComparator\fP (unsigned int _obj)"
.br
.ti -1c
.RI "const bool \fBoperator()\fP (const MOEOT &_moeo1, const MOEOT &_moeo2)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned int \fBobj\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT, class Move> class moeoIBMOLS< MOEOT, Move >::OneObjectiveComparator"

.PP
Definition at line 488 of file moeoIBMOLS.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO-MultiObjectiveEvolvingObjects from the source code.
