.TH "moeoReferencePointIndicatorBasedFitnessAssignment" 3 "29 Feb 2008" "Version 1.1" "ParadisEO-MOEO-MultiObjectiveEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoReferencePointIndicatorBasedFitnessAssignment \- Fitness assignment sheme based a Reference Point and a Quality Indicator.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoReferencePointIndicatorBasedFitnessAssignment.h>\fP
.PP
Inherits \fBmoeoFitnessAssignment< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef MOEOT::ObjectiveVector \fBObjectiveVector\fP"
.br
.RI "\fIThe type of objective vector. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoReferencePointIndicatorBasedFitnessAssignment\fP (\fBObjectiveVector\fP &_refPoint, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > &_metric)"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "void \fBoperator()\fP (\fBeoPop\fP< MOEOT > &_pop)"
.br
.RI "\fISets the fitness values for every solution contained in the population _pop. \fP"
.ti -1c
.RI "void \fBupdateByDeleting\fP (\fBeoPop\fP< MOEOT > &_pop, \fBObjectiveVector\fP &_objVec)"
.br
.RI "\fIUpdates the fitness values of the whole population _pop by taking the deletion of the objective vector _objVec into account. \fP"
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetup\fP (const \fBeoPop\fP< MOEOT > &_pop)"
.br
.RI "\fISets the bounds for every objective using the min and the max value for every objective vector of _pop (and the reference point). \fP"
.ti -1c
.RI "void \fBsetFitnesses\fP (\fBeoPop\fP< MOEOT > &_pop)"
.br
.RI "\fISets the fitness of every individual contained in the population _pop. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBObjectiveVector\fP & \fBrefPoint\fP"
.br
.RI "\fIthe reference point \fP"
.ti -1c
.RI "\fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > & \fBmetric\fP"
.br
.RI "\fIthe quality indicator \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoReferencePointIndicatorBasedFitnessAssignment< MOEOT >"
Fitness assignment sheme based a Reference Point and a Quality Indicator. 
.PP
Definition at line 50 of file moeoReferencePointIndicatorBasedFitnessAssignment.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class MOEOT> \fBmoeoReferencePointIndicatorBasedFitnessAssignment\fP< MOEOT >::\fBmoeoReferencePointIndicatorBasedFitnessAssignment\fP (\fBObjectiveVector\fP & _refPoint, \fBmoeoNormalizedSolutionVsSolutionBinaryMetric\fP< \fBObjectiveVector\fP, double > & _metric)\fC [inline]\fP"
.PP
Ctor. 
.PP
\fBParameters:\fP
.RS 4
\fI_refPoint\fP the reference point 
.br
\fI_metric\fP the quality indicator 
.RE
.PP

.PP
Definition at line 62 of file moeoReferencePointIndicatorBasedFitnessAssignment.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class MOEOT> void \fBmoeoReferencePointIndicatorBasedFitnessAssignment\fP< MOEOT >::operator() (\fBeoPop\fP< MOEOT > & _pop)\fC [inline, virtual]\fP"
.PP
Sets the fitness values for every solution contained in the population _pop. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.RE
.PP

.PP
Implements \fBeoUF< eoPop< MOEOT > &, void >\fP.
.PP
Definition at line 71 of file moeoReferencePointIndicatorBasedFitnessAssignment.h.
.PP
References moeoReferencePointIndicatorBasedFitnessAssignment< MOEOT >::setFitnesses(), and moeoReferencePointIndicatorBasedFitnessAssignment< MOEOT >::setup().
.SS "template<class MOEOT> void \fBmoeoReferencePointIndicatorBasedFitnessAssignment\fP< MOEOT >::updateByDeleting (\fBeoPop\fP< MOEOT > & _pop, \fBObjectiveVector\fP & _objVec)\fC [inline, virtual]\fP"
.PP
Updates the fitness values of the whole population _pop by taking the deletion of the objective vector _objVec into account. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.br
\fI_objVec\fP the objective vector 
.RE
.PP

.PP
Implements \fBmoeoFitnessAssignment< MOEOT >\fP.
.PP
Definition at line 85 of file moeoReferencePointIndicatorBasedFitnessAssignment.h.
.SS "template<class MOEOT> void \fBmoeoReferencePointIndicatorBasedFitnessAssignment\fP< MOEOT >::setup (const \fBeoPop\fP< MOEOT > & _pop)\fC [inline, protected]\fP"
.PP
Sets the bounds for every objective using the min and the max value for every objective vector of _pop (and the reference point). 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.RE
.PP

.PP
Definition at line 103 of file moeoReferencePointIndicatorBasedFitnessAssignment.h.
.PP
References moeoReferencePointIndicatorBasedFitnessAssignment< MOEOT >::metric, moeoReferencePointIndicatorBasedFitnessAssignment< MOEOT >::refPoint, and moeoNormalizedSolutionVsSolutionBinaryMetric< ObjectiveVector, R >::setup().
.PP
Referenced by moeoReferencePointIndicatorBasedFitnessAssignment< MOEOT >::operator()().
.SS "template<class MOEOT> void \fBmoeoReferencePointIndicatorBasedFitnessAssignment\fP< MOEOT >::setFitnesses (\fBeoPop\fP< MOEOT > & _pop)\fC [inline, protected]\fP"
.PP
Sets the fitness of every individual contained in the population _pop. 
.PP
\fBParameters:\fP
.RS 4
\fI_pop\fP the population 
.RE
.PP

.PP
Definition at line 124 of file moeoReferencePointIndicatorBasedFitnessAssignment.h.
.PP
References moeoReferencePointIndicatorBasedFitnessAssignment< MOEOT >::metric, and moeoReferencePointIndicatorBasedFitnessAssignment< MOEOT >::refPoint.
.PP
Referenced by moeoReferencePointIndicatorBasedFitnessAssignment< MOEOT >::operator()().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO-MultiObjectiveEvolvingObjects from the source code.
