# sample makefile for building an EA evolving a new genotype

.cpp: ; c++  -DPACKAGE=\"eo\" -DVERSION=\"0.9.1\" -I. -I../../src -Wall -g  -o $@  $*.cpp ../../src/libeo.a ../../src/utils/libeoutils.a

.cpp.o: ; c++ -DPACKAGE=\"eo\" -DVERSION=\"0.9.1\" -DF2C -I. -I../../src -I../Points -I./Sol -I./util -Wall -g -c $*.cpp


# START eventually modify the name of EO dir
DIR_EO = ../../src
# END eventually modify the name of EO dir

LIB_EO = $(DIR_EO)/utils/libeoutils.a $(DIR_EO)/libeo.a

ALL = eoMyStructEA

eoMyStructEA : eoMyStructEA.o
	c++ -g -o $@ eoMyStructEA.o ../../src/utils/libeoutils.a ../../src/libeo.a -lm 

tar : ; tar czvf climat.tgz *.h *.cpp Makefile

all : $(ALL)

clean : ; /bin/rm  *.o $(ALL)


