.TH "moeoSolutionVsSolutionBinaryMetric" 3 "26 Jun 2007" "Version 1.0" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoSolutionVsSolutionBinaryMetric \- Base class for binary metrics dedicated to the performance comparison between two solutions's objective vectors.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoMetric.h>\fP
.PP
Inherits \fBmoeoBinaryMetric< A1, A2, R >< const const ObjectiveVector &, ObjectiveVector &, R >\fP.
.PP
Inherited by \fBmoeoNormalizedSolutionVsSolutionBinaryMetric< ObjectiveVector, R >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class ObjectiveVector, class R> class moeoSolutionVsSolutionBinaryMetric< ObjectiveVector, R >"
Base class for binary metrics dedicated to the performance comparison between two solutions's objective vectors. 
.PP
Definition at line 57 of file moeoMetric.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
