.TH "eoBinaryQualityIndicator::Range" 3 "22 Dec 2006" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eoBinaryQualityIndicator::Range \- Private class to represent the bounds.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <eoBinaryQualityIndicator.h>\fP
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRange\fP ()"
.br
.ti -1c
.RI "\fBRange\fP (const double _min, const double _max)"
.br
.ti -1c
.RI "double \fBminimum\fP ()"
.br
.ti -1c
.RI "double \fBmaximum\fP ()"
.br
.ti -1c
.RI "double \fBrange\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "double \fBmin\fP"
.br
.ti -1c
.RI "double \fBmax\fP"
.br
.ti -1c
.RI "double \fBr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOFitness> class eoBinaryQualityIndicator< EOFitness >::Range"
Private class to represent the bounds. 
.PP
Definition at line 73 of file eoBinaryQualityIndicator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
