.TH "moeoRouletteSelect" 3 "17 Apr 2007" "Version 1.0.alpha" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoRouletteSelect \- Selection strategy that selects ONE individual by using roulette wheel process.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoRouletteSelect.h>\fP
.PP
Inherits \fBmoeoSelectOne< MOEOT >< MOEOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoRouletteSelect\fP (\fBmoeoComparator\fP< MOEOT > &_comparator, unsigned _tSize=2)"
.br
.RI "\fIFull Ctor. \fP"
.ti -1c
.RI "\fBmoeoRouletteSelect\fP (unsigned _tSize=2)"
.br
.RI "\fICtor without comparator. \fP"
.ti -1c
.RI "const MOEOT & \fBoperator()\fP (const \fBeoPop\fP< MOEOT > &_pop)"
.br
.RI "\fIApply the tournament to the given population. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBmoeoComparator\fP< MOEOT > & \fBcomparator\fP"
.br
.RI "\fIcomparator \fP"
.ti -1c
.RI "double & \fBtSize\fP"
.br
.RI "\fIsize \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoRouletteSelect< MOEOT >"
Selection strategy that selects ONE individual by using roulette wheel process. 
.PP
Definition at line 23 of file moeoRouletteSelect.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class MOEOT> \fBmoeoRouletteSelect\fP< MOEOT >::\fBmoeoRouletteSelect\fP (\fBmoeoComparator\fP< MOEOT > & _comparator, unsigned _tSize = \fC2\fP)\fC [inline]\fP"
.PP
Full Ctor. 
.PP
\fBParameters:\fP
.RS 4
\fI_comparator\fP the comparator (used to compare 2 individuals) 
.br
\fI_tSize\fP the number of individuals in the tournament (default: 2) 
.RE
.PP

.PP
Definition at line 33 of file moeoRouletteSelect.h.
.PP
References moeoRouletteSelect< MOEOT >::tSize.
.SS "template<class MOEOT> \fBmoeoRouletteSelect\fP< MOEOT >::\fBmoeoRouletteSelect\fP (unsigned _tSize = \fC2\fP)\fC [inline]\fP"
.PP
Ctor without comparator. 
.PP
A \fBmoeoFitnessThenDiversityComparator\fP is used as default. 
.PP
\fBParameters:\fP
.RS 4
\fI_tSize\fP the number of individuals in the tournament (default: 2) 
.RE
.PP

.PP
Definition at line 50 of file moeoRouletteSelect.h.
.PP
References moeoRouletteSelect< MOEOT >::tSize.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
