.TH "moeoSolutionUM" 3 "22 Dec 2006" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoSolutionUM \- Base class for unary metrics dedicated to the performance evaluation of a single solution's Pareto fitness.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoMetric.h>\fP
.PP
Inherits \fBmoeoUM< const EOFitness &, R >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT, class R, class EOFitness = typename EOT::Fitness> class moeoSolutionUM< EOT, R, EOFitness >"
Base class for unary metrics dedicated to the performance evaluation of a single solution's Pareto fitness. 
.PP
Definition at line 47 of file moeoMetric.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
