.TH "moeoAdditiveBinaryEpsilonIndicator" 3 "16 Jan 2007" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoAdditiveBinaryEpsilonIndicator \- Functor Additive binary epsilon indicator for \fBeoParetoFitness\fP.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoBinaryQualityIndicator.h>\fP
.PP
Inherits \fBmoeoBinaryQualityIndicator< EOFitness >< EOFitness >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoAdditiveBinaryEpsilonIndicator\fP ()"
.br
.RI "\fIconstructor \fP"
.ti -1c
.RI "double \fBoperator()\fP (const EOFitness &_fitness_eo1, const EOFitness &_fitness_eo2)"
.br
.RI "\fIcomputation of the maximum epsilon value by which individual _eo1 must be decreased in all objectives such that individual _eo2 is weakly dominated (do not forget to set the bounds before the call of this function) \fP"
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "typedef EOFitness::fitness_traits \fBtraits\fP"
.br
.RI "\fIfitness traits \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "double \fBepsilonValue\fP (const EOFitness &_fitness_eo1, const EOFitness &_fitness_eo2, const unsigned _iObj)"
.br
.RI "\fIcomputation of the epsilon value by which individual _eo1 must be decreased in the objective _iObj such that individual _eo2 is weakly dominated \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOFitness> class moeoAdditiveBinaryEpsilonIndicator< EOFitness >"
Functor Additive binary epsilon indicator for \fBeoParetoFitness\fP. 
.PP
Definition at line 115 of file moeoBinaryQualityIndicator.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOFitness> double \fBmoeoAdditiveBinaryEpsilonIndicator\fP< EOFitness >::operator() (const EOFitness & _fitness_eo1, const EOFitness & _fitness_eo2)\fC [inline]\fP"
.PP
computation of the maximum epsilon value by which individual _eo1 must be decreased in all objectives such that individual _eo2 is weakly dominated (do not forget to set the bounds before the call of this function) 
.PP
\fBParameters:\fP
.RS 4
\fIEOFitness\fP & _fitness_eo1 the fitness of the first individual 
.br
\fIEOFitness\fP & _fitness_eo2 the fitness of the second individual 
.RE
.PP

.PP
Definition at line 138 of file moeoBinaryQualityIndicator.h.
.PP
References moeoAdditiveBinaryEpsilonIndicator< EOFitness >::epsilonValue().
.SS "template<class EOFitness> double \fBmoeoAdditiveBinaryEpsilonIndicator\fP< EOFitness >::epsilonValue (const EOFitness & _fitness_eo1, const EOFitness & _fitness_eo2, const unsigned _iObj)\fC [inline, private]\fP"
.PP
computation of the epsilon value by which individual _eo1 must be decreased in the objective _iObj such that individual _eo2 is weakly dominated 
.PP
\fBParameters:\fP
.RS 4
\fIEOFitness\fP & _fitness_eo1 the fitness of the first individual 
.br
\fIEOFitness\fP & _fitness_eo2 the fitness of the second individual 
.br
\fIunsigned\fP _iObj the index of the objective 
.RE
.PP

.PP
Definition at line 170 of file moeoBinaryQualityIndicator.h.
.PP
References moeoBinaryQualityIndicator< EOFitness >::bounds.
.PP
Referenced by moeoAdditiveBinaryEpsilonIndicator< EOFitness >::operator()().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
