.TH "moeoNDSorting_II" 3 "22 Dec 2006" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoNDSorting_II \- Fast Elitist Non-Dominant Sorting Genetic Algorithm.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoNDSorting.h>\fP
.PP
Inherits \fBeoNDSorting< EOT >< EOT >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::pair< double, unsigned > \fBdouble_index_pair\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoNDSorting_II\fP (bool nasty_flag_=false)"
.br
.ti -1c
.RI "std::vector< double > \fBniche_penalty\fP (const std::vector< unsigned > &_cf, const \fBeoPop\fP< EOT > &_pop)"
.br
.RI "\fI_cf points into the elements that consist of the current front \fP"
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcompare_nodes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class moeoNDSorting_II< EOT >"
Fast Elitist Non-Dominant Sorting Genetic Algorithm. 

Note : This is a corrected version of the original \fBeoNDSorting_II\fP class
.PP
\fBSee also:\fP
.RS 4
\fBeoNDSorting_II\fP 
.RE
.PP

.PP
Definition at line 26 of file moeoNDSorting.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
