.TH "moeoScalarFitnessAssignment" 3 "17 Apr 2007" "Version 1.0.alpha" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoScalarFitnessAssignment \- \fBmoeoScalarFitnessAssignment\fP is a \fBmoeoFitnessAssignment\fP for scalar strategies.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoFitnessAssignment.h>\fP
.PP
Inherits \fBmoeoFitnessAssignment< MOEOT >< MOEOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoScalarFitnessAssignment< MOEOT >"
\fBmoeoScalarFitnessAssignment\fP is a \fBmoeoFitnessAssignment\fP for scalar strategies. 
.PP
Definition at line 98 of file moeoFitnessAssignment.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
