.TH "moeoGDominanceObjectiveVectorComparator" 3 "17 Apr 2007" "Version 1.0.alpha" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoGDominanceObjectiveVectorComparator \- This functor class allows to compare 2 objective vectors according to g-dominance.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoObjectiveVectorComparator.h>\fP
.PP
Inherits \fBmoeoObjectiveVectorComparator< ObjectiveVector >< ObjectiveVector >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoGDominanceObjectiveVectorComparator\fP (ObjectiveVector _ref)"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "bool \fBoperator()\fP (const ObjectiveVector &_objectiveVector1, const ObjectiveVector &_objectiveVector2)"
.br
.RI "\fIReturns true if _objectiveVector1 g-dominates _objectiveVector2. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "unsigned \fBflag\fP (const ObjectiveVector &_objectiveVector)"
.br
.RI "\fIReturns the flag of _objectiveVector according to the reference point. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "ObjectiveVector \fBref\fP"
.br
.RI "\fIthe reference point \fP"
.ti -1c
.RI "\fBmoeoParetoObjectiveVectorComparator\fP< ObjectiveVector > \fBparetoComparator\fP"
.br
.RI "\fIPareto comparator. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ObjectiveVector> class moeoGDominanceObjectiveVectorComparator< ObjectiveVector >"
This functor class allows to compare 2 objective vectors according to g-dominance. 

The concept of g-dominance as been introduced in: J. Molina, L. V. Santana, A. G. Hernandez-Diaz, C. A. Coello Coello, R. Caballero, 'g-dominance: Reference point based dominance' (2007) 
.PP
Definition at line 88 of file moeoObjectiveVectorComparator.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ObjectiveVector> \fBmoeoGDominanceObjectiveVectorComparator\fP< ObjectiveVector >::\fBmoeoGDominanceObjectiveVectorComparator\fP (ObjectiveVector _ref)\fC [inline]\fP"
.PP
Ctor. 
.PP
\fBParameters:\fP
.RS 4
\fI_ref\fP the reference point 
.RE
.PP

.PP
Definition at line 96 of file moeoObjectiveVectorComparator.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class ObjectiveVector> bool \fBmoeoGDominanceObjectiveVectorComparator\fP< ObjectiveVector >::operator() (const ObjectiveVector & _objectiveVector1, const ObjectiveVector & _objectiveVector2)\fC [inline]\fP"
.PP
Returns true if _objectiveVector1 g-dominates _objectiveVector2. 
.PP
\fBParameters:\fP
.RS 4
\fI_objectiveVector1\fP the first objective vector 
.br
\fI_objectiveVector2\fP the second objective vector 
.RE
.PP

.PP
Definition at line 105 of file moeoObjectiveVectorComparator.h.
.PP
References moeoGDominanceObjectiveVectorComparator< ObjectiveVector >::flag(), and moeoGDominanceObjectiveVectorComparator< ObjectiveVector >::paretoComparator.
.SS "template<class ObjectiveVector> unsigned \fBmoeoGDominanceObjectiveVectorComparator\fP< ObjectiveVector >::flag (const ObjectiveVector & _objectiveVector)\fC [inline, private]\fP"
.PP
Returns the flag of _objectiveVector according to the reference point. 
.PP
\fBParameters:\fP
.RS 4
\fI_objectiveVector\fP the first objective vector 
.RE
.PP

.PP
Definition at line 139 of file moeoObjectiveVectorComparator.h.
.PP
References moeoGDominanceObjectiveVectorComparator< ObjectiveVector >::ref.
.PP
Referenced by moeoGDominanceObjectiveVectorComparator< ObjectiveVector >::operator()().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
