.TH "moeoContributionMetric" 3 "22 Dec 2006" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoContributionMetric \- The contribution metric evaluates the proportion of non-dominated solutions given by a Pareto set relatively to another Pareto set.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoContributionMetric.h>\fP
.PP
Inherits \fBmoeoVectorVsVectorBM< EOT, double >\fP.
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef EOT::Fitness \fBEOFitness\fP"
.br
.RI "\fIThe fitness type of a solution. \fP"
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBoperator()\fP (const std::vector< \fBEOFitness\fP > &_set1, const std::vector< \fBEOFitness\fP > &_set2)"
.br
.RI "\fIReturns the contribution of the Pareto set '_set1' relatively to the Pareto set '_set2'. \fP"
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "unsigned \fBcard_C\fP (const std::vector< \fBEOFitness\fP > &_set1, const std::vector< \fBEOFitness\fP > &_set2)"
.br
.RI "\fIReturns the number of solutions both in '_set1' and '_set2'. \fP"
.ti -1c
.RI "unsigned \fBcard_W\fP (const std::vector< \fBEOFitness\fP > &_set1, const std::vector< \fBEOFitness\fP > &_set2)"
.br
.RI "\fIReturns the number of solutions in '_set1' dominating at least one solution of '_set2'. \fP"
.ti -1c
.RI "unsigned \fBcard_N\fP (const std::vector< \fBEOFitness\fP > &_set1, const std::vector< \fBEOFitness\fP > &_set2)"
.br
.RI "\fIReturns the number of solutions in '_set1' having no relation of dominance with those from '_set2'. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class moeoContributionMetric< EOT >"
The contribution metric evaluates the proportion of non-dominated solutions given by a Pareto set relatively to another Pareto set. 

(Meunier, Talbi, Reininger: 'A multiobjective genetic algorithm for radio network optimization', in Proc. of the 2000 Congress on Evolutionary Computation, IEEE Press, pp. 317-324) 
.PP
Definition at line 23 of file moeoContributionMetric.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class EOT> double \fBmoeoContributionMetric\fP< EOT >::operator() (const std::vector< \fBEOFitness\fP > & _set1, const std::vector< \fBEOFitness\fP > & _set2)\fC [inline]\fP"
.PP
Returns the contribution of the Pareto set '_set1' relatively to the Pareto set '_set2'. 
.PP
\fBParameters:\fP
.RS 4
\fI_set1\fP the first Pareto set 
.br
\fI_set2\fP the second Pareto set 
.RE
.PP

.PP
Definition at line 38 of file moeoContributionMetric.h.
.PP
References moeoContributionMetric< EOT >::card_C(), moeoContributionMetric< EOT >::card_N(), and moeoContributionMetric< EOT >::card_W().
.SS "template<class EOT> unsigned \fBmoeoContributionMetric\fP< EOT >::card_C (const std::vector< \fBEOFitness\fP > & _set1, const std::vector< \fBEOFitness\fP > & _set2)\fC [inline, private]\fP"
.PP
Returns the number of solutions both in '_set1' and '_set2'. 
.PP
\fBParameters:\fP
.RS 4
\fI_set1\fP the first Pareto set 
.br
\fI_set2\fP the second Pareto set 
.RE
.PP

.PP
Definition at line 57 of file moeoContributionMetric.h.
.PP
Referenced by moeoContributionMetric< EOT >::operator()().
.SS "template<class EOT> unsigned \fBmoeoContributionMetric\fP< EOT >::card_W (const std::vector< \fBEOFitness\fP > & _set1, const std::vector< \fBEOFitness\fP > & _set2)\fC [inline, private]\fP"
.PP
Returns the number of solutions in '_set1' dominating at least one solution of '_set2'. 
.PP
\fBParameters:\fP
.RS 4
\fI_set1\fP the first Pareto set 
.br
\fI_set2\fP the second Pareto set 
.RE
.PP

.PP
Definition at line 76 of file moeoContributionMetric.h.
.PP
Referenced by moeoContributionMetric< EOT >::operator()().
.SS "template<class EOT> unsigned \fBmoeoContributionMetric\fP< EOT >::card_N (const std::vector< \fBEOFitness\fP > & _set1, const std::vector< \fBEOFitness\fP > & _set2)\fC [inline, private]\fP"
.PP
Returns the number of solutions in '_set1' having no relation of dominance with those from '_set2'. 
.PP
\fBParameters:\fP
.RS 4
\fI_set1\fP the first Pareto set 
.br
\fI_set2\fP the second Pareto set 
.RE
.PP

.PP
Definition at line 95 of file moeoContributionMetric.h.
.PP
Referenced by moeoContributionMetric< EOT >::operator()().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
