.TH "moeoMOLS" 3 "16 Jan 2007" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoMOLS \- Abstract class for local searches applied to multi-objective optimization.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoMOLS.h>\fP
.PP
Inherits \fBeoBF< const EOT &, moeoArchive< EOT > &, void >\fP.
.PP
Inherited by \fBmoeoCombinedMOLS< EOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class moeoMOLS< EOT >"
Abstract class for local searches applied to multi-objective optimization. 

Starting from only one solution, it produces a set of new non-dominated solutions. 
.PP
Definition at line 23 of file moeoMOLS.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
