eoPrintable Class Reference
Base class for objects that can print themselves (printOn(p.)#).
#include <eoPrintable.h>
Public Member Functions
virtual ~eoPrintable ()
Virtual dtor. They are needed in virtual class hierarchies.
virtual void printOn (std::ostream &_os) const =0
Write object.
Detailed Description
Base class for objects that can print themselves (printOn(p.)#).
Besides, this file defines the standard output for all the objects; if the objects define printOn there's no need to define #operator <<#.\ This functionality was separated from eoObject(p.), since it makes no sense to print some objects (for instance, a eoFactory(p.)# or a random number generator.
Definition at line 43 of file eoPrintable.h.
Member Function Documentation
virtual void eoPrintable::printOn (std::ostream & _os) const [pure virtual]
Write object.
It's called printOn since it prints the object on a stream.
Parameters:
_os A std::ostream.
Implemented in EO< F > (p.), eoContinue< EOT > (p.), eoGenContinue< EOT > (p.), eoPop< EOT > (p.), eoVector< FitT, GeneType > (p.), eoEsFull< Fit > (p.), eoEsSimple< Fit > (p.), eoEsStdev< Fit > (p.), eoBit< FitT > (p.), eoPBILDistrib< EOT > (p.), eoParseTree< FType, Node > (p.), eoExternalEO< Fit, External > (p.), eoString< fitnessT > (p.), eoHowMany (p.), eoIntNoBounds (p.), eoIntInterval (p.), eoIntBelowBound (p.), eoIntAboveBound (p.), eoGeneralIntBounds (p.), eoParser (p.), eoRealNoBounds (p.), eoRealInterval (p.), eoRealBelowBound (p.), eoRealAboveBound (p.), eoGeneralRealBounds (p.), eoRealVectorBounds (p.), eoRng (p.), Dummy (p.), Dummy (p.), Dummy (p.), Dummy (p.), EO< double > (p.), EO< EOT::Fitness > (p.), EO< FitT > (p.), EO< phenotype > (p.), EO< fitnessT > (p.), EO< Fit > (p.), EO< FType > (p.), EO< fitness_type > (p.), EO< Fitness > (p.), EO< PyFitness > (p.), eoPop< PyEO > (p.), eoPop< Dummy > (p.), eoVector< Fit, double > (p.), eoVector< FitT, double > (p.), and eoVector< FitT, bool > (p.).
Referenced by eoRealVectorBounds::printOn(), eoGeneralRealBounds::printOn(), eoGeneralIntBounds::printOn(), and eoState::save().
The documentation for this class was generated from the following file:
eoPrintable.h