.TH "moeoRealObjectiveVector" 3 "6 Jul 2007" "Version 1.0-beta" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoRealObjectiveVector \- This class allows to represent a solution in the objective space (phenotypic representation) by a std::vector of real values, i.e.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoRealObjectiveVector.h>\fP
.PP
Inherits \fBmoeoObjectiveVector< ObjectiveVectorTraits, double >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoRealObjectiveVector\fP (double _value=0.0)"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "\fBmoeoRealObjectiveVector\fP (std::vector< double > &_v)"
.br
.RI "\fICtor from a vector of doubles. \fP"
.ti -1c
.RI "bool \fBdominates\fP (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > &_other) const "
.br
.RI "\fIReturns true if the current objective vector dominates _other according to the Pareto dominance relation (but it's better to use a \fBmoeoObjectiveVectorComparator\fP object to compare solutions). \fP"
.ti -1c
.RI "bool \fBoperator==\fP (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > &_other) const "
.br
.RI "\fIReturns true if the current objective vector is equal to _other (according to a tolerance value). \fP"
.ti -1c
.RI "bool \fBoperator!=\fP (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > &_other) const "
.br
.RI "\fIReturns true if the current objective vector is different than _other (according to a tolerance value). \fP"
.ti -1c
.RI "bool \fBoperator<\fP (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > &_other) const "
.br
.RI "\fIReturns true if the current objective vector is smaller than _other on the first objective, then on the second, and so on (can be usefull for sorting/printing). \fP"
.ti -1c
.RI "bool \fBoperator>\fP (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > &_other) const "
.br
.RI "\fIReturns true if the current objective vector is greater than _other on the first objective, then on the second, and so on (can be usefull for sorting/printing). \fP"
.ti -1c
.RI "bool \fBoperator<=\fP (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > &_other) const "
.br
.RI "\fIReturns true if the current objective vector is smaller than or equal to _other on the first objective, then on the second, and so on (can be usefull for sorting/printing). \fP"
.ti -1c
.RI "bool \fBoperator>=\fP (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > &_other) const "
.br
.RI "\fIReturns true if the current objective vector is greater than or equal to _other on the first objective, then on the second, and so on (can be usefull for sorting/printing). \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class ObjectiveVectorTraits> class moeoRealObjectiveVector< ObjectiveVectorTraits >"
This class allows to represent a solution in the objective space (phenotypic representation) by a std::vector of real values, i.e. 

that an objective value is represented using a double, and this for any objective. 
.PP
Definition at line 27 of file moeoRealObjectiveVector.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class ObjectiveVectorTraits> \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits >::\fBmoeoRealObjectiveVector\fP (std::vector< double > & _v)\fC [inline]\fP"
.PP
Ctor from a vector of doubles. 
.PP
\fBParameters:\fP
.RS 4
\fI_v\fP the std::vector < double > 
.RE
.PP

.PP
Definition at line 45 of file moeoRealObjectiveVector.h.
.SH "Member Function Documentation"
.PP 
.SS "template<class ObjectiveVectorTraits> bool \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits >::dominates (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > & _other) const\fC [inline]\fP"
.PP
Returns true if the current objective vector dominates _other according to the Pareto dominance relation (but it's better to use a \fBmoeoObjectiveVectorComparator\fP object to compare solutions). 
.PP
\fBParameters:\fP
.RS 4
\fI_other\fP the other \fBmoeoRealObjectiveVector\fP object to compare with 
.RE
.PP

.PP
Definition at line 54 of file moeoRealObjectiveVector.h.
.SS "template<class ObjectiveVectorTraits> bool \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits >::operator== (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > & _other) const\fC [inline]\fP"
.PP
Returns true if the current objective vector is equal to _other (according to a tolerance value). 
.PP
\fBParameters:\fP
.RS 4
\fI_other\fP the other \fBmoeoRealObjectiveVector\fP object to compare with 
.RE
.PP

.PP
Definition at line 65 of file moeoRealObjectiveVector.h.
.PP
Referenced by moeoRealObjectiveVector< ObjectiveVectorTraits >::operator!=(), and moeoRealObjectiveVector< ObjectiveVectorTraits >::operator>=().
.SS "template<class ObjectiveVectorTraits> bool \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits >::operator!= (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > & _other) const\fC [inline]\fP"
.PP
Returns true if the current objective vector is different than _other (according to a tolerance value). 
.PP
\fBParameters:\fP
.RS 4
\fI_other\fP the other \fBmoeoRealObjectiveVector\fP object to compare with 
.RE
.PP

.PP
Definition at line 82 of file moeoRealObjectiveVector.h.
.PP
References moeoRealObjectiveVector< ObjectiveVectorTraits >::operator==().
.SS "template<class ObjectiveVectorTraits> bool \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits >::operator< (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > & _other) const\fC [inline]\fP"
.PP
Returns true if the current objective vector is smaller than _other on the first objective, then on the second, and so on (can be usefull for sorting/printing). 
.PP
\fBParameters:\fP
.RS 4
\fI_other\fP the other \fBmoeoRealObjectiveVector\fP object to compare with 
.RE
.PP

.PP
Definition at line 93 of file moeoRealObjectiveVector.h.
.PP
Referenced by moeoRealObjectiveVector< ObjectiveVectorTraits >::operator<=().
.SS "template<class ObjectiveVectorTraits> bool \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits >::operator> (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > & _other) const\fC [inline]\fP"
.PP
Returns true if the current objective vector is greater than _other on the first objective, then on the second, and so on (can be usefull for sorting/printing). 
.PP
\fBParameters:\fP
.RS 4
\fI_other\fP the other \fBmoeoRealObjectiveVector\fP object to compare with 
.RE
.PP

.PP
Definition at line 105 of file moeoRealObjectiveVector.h.
.PP
Referenced by moeoRealObjectiveVector< ObjectiveVectorTraits >::operator>=().
.SS "template<class ObjectiveVectorTraits> bool \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits >::operator<= (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > & _other) const\fC [inline]\fP"
.PP
Returns true if the current objective vector is smaller than or equal to _other on the first objective, then on the second, and so on (can be usefull for sorting/printing). 
.PP
\fBParameters:\fP
.RS 4
\fI_other\fP the other \fBmoeoRealObjectiveVector\fP object to compare with 
.RE
.PP

.PP
Definition at line 116 of file moeoRealObjectiveVector.h.
.PP
References moeoRealObjectiveVector< ObjectiveVectorTraits >::operator<().
.SS "template<class ObjectiveVectorTraits> bool \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits >::operator>= (const \fBmoeoRealObjectiveVector\fP< ObjectiveVectorTraits > & _other) const\fC [inline]\fP"
.PP
Returns true if the current objective vector is greater than or equal to _other on the first objective, then on the second, and so on (can be usefull for sorting/printing). 
.PP
\fBParameters:\fP
.RS 4
\fI_other\fP the other \fBmoeoRealObjectiveVector\fP object to compare with 
.RE
.PP

.PP
Definition at line 127 of file moeoRealObjectiveVector.h.
.PP
References moeoRealObjectiveVector< ObjectiveVectorTraits >::operator==(), and moeoRealObjectiveVector< ObjectiveVectorTraits >::operator>().

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
