.TH "moeoHybridLS" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-MOEO-MultiObjectiveEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoHybridLS \- This class allows to apply a multi-objective local search to a number of selected individuals contained in the archive at every generation until a stopping criteria is verified.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoHybridLS.h>\fP
.PP
Inherits \fBeoUpdater\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoHybridLS\fP (\fBeoContinue\fP< MOEOT > &_term, \fBeoSelect\fP< MOEOT > &_select, \fBmoeoLS\fP< MOEOT, MOEOT > &_mols, \fBmoeoArchive\fP< MOEOT > &_arch)"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.RI "\fIApplies the multi-objective local search to selected individuals contained in the archive if the stopping criteria is not verified. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBeoContinue\fP< MOEOT > & \fBterm\fP"
.br
.RI "\fIstopping criteria \fP"
.ti -1c
.RI "\fBeoSelect\fP< MOEOT > & \fBselect\fP"
.br
.RI "\fIselector \fP"
.ti -1c
.RI "\fBmoeoLS\fP< MOEOT, MOEOT > & \fBmols\fP"
.br
.RI "\fImulti-objective local search \fP"
.ti -1c
.RI "\fBmoeoArchive\fP< MOEOT > & \fBarch\fP"
.br
.RI "\fIarchive \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoHybridLS< MOEOT >"
This class allows to apply a multi-objective local search to a number of selected individuals contained in the archive at every generation until a stopping criteria is verified. 
.PP
Definition at line 53 of file moeoHybridLS.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class MOEOT> \fBmoeoHybridLS\fP< MOEOT >::\fBmoeoHybridLS\fP (\fBeoContinue\fP< MOEOT > & _term, \fBeoSelect\fP< MOEOT > & _select, \fBmoeoLS\fP< MOEOT, MOEOT > & _mols, \fBmoeoArchive\fP< MOEOT > & _arch)\fC [inline]\fP"
.PP
Ctor. 
.PP
\fBParameters:\fP
.RS 4
\fI_term\fP stopping criteria 
.br
\fI_select\fP selector 
.br
\fI_mols\fP a multi-objective local search 
.br
\fI_arch\fP the archive 
.RE
.PP

.PP
Definition at line 64 of file moeoHybridLS.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO-MultiObjectiveEvolvingObjects from the source code.
