.TH "moeoCriterionBasedFitnessAssignment" 3 "13 Mar 2008" "Version 1.1" "ParadisEO-MOEO-MultiObjectiveEvolvingObjects" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoCriterionBasedFitnessAssignment \- \fBmoeoCriterionBasedFitnessAssignment\fP is a \fBmoeoFitnessAssignment\fP for criterion-based strategies.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoCriterionBasedFitnessAssignment.h>\fP
.PP
Inherits \fBmoeoFitnessAssignment< MOEOT >< MOEOT >\fP.
.PP
.SH "Detailed Description"
.PP 

.SS "template<class MOEOT> class moeoCriterionBasedFitnessAssignment< MOEOT >"
\fBmoeoCriterionBasedFitnessAssignment\fP is a \fBmoeoFitnessAssignment\fP for criterion-based strategies. 
.PP
Definition at line 47 of file moeoCriterionBasedFitnessAssignment.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO-MultiObjectiveEvolvingObjects from the source code.
