.TH "peoParaSGATransform" 3 "9 Jan 2007" "Version 0.1" "ParadisEO-PEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
peoParaSGATransform \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBpeoTransform< EOT >< EOT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpeoParaSGATransform\fP (eoQuadOp< EOT > &__cross, double __cross_rate, eoMonOp< EOT > &__mut, double __mut_rate)"
.br
.ti -1c
.RI "void \fBoperator()\fP (eoPop< EOT > &__pop)"
.br
.ti -1c
.RI "void \fBpackData\fP ()"
.br
.ti -1c
.RI "void \fBunpackData\fP ()"
.br
.ti -1c
.RI "void \fBexecute\fP ()"
.br
.ti -1c
.RI "void \fBpackResult\fP ()"
.br
.ti -1c
.RI "void \fBunpackResult\fP ()"
.br
.ti -1c
.RI "void \fBnotifySendingData\fP ()"
.br
.ti -1c
.RI "void \fBnotifySendingAllResourceRequests\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "eoQuadOp< EOT > & \fBcross\fP"
.br
.ti -1c
.RI "double \fBcross_rate\fP"
.br
.ti -1c
.RI "eoMonOp< EOT > & \fBmut\fP"
.br
.ti -1c
.RI "double \fBmut_rate\fP"
.br
.ti -1c
.RI "unsigned \fBidx\fP"
.br
.ti -1c
.RI "eoPop< EOT > * \fBpop\fP"
.br
.ti -1c
.RI "EOT \fBfather\fP"
.br
.ti -1c
.RI "EOT \fBmother\fP"
.br
.ti -1c
.RI "unsigned \fBnum_term\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class peoParaSGATransform< EOT >"

.PP
Definition at line 21 of file peoParaSGATransform.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO from the source code.
