.TH "TwoOptIncrEval" 3 "12 Oct 2007" "Version 1.0" "ParadisEO-PEO: Parallel and Distributed Evolving Objects - Lessons" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TwoOptIncrEval \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBmoMoveIncrEval< TwoOpt >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBoperator()\fP (const \fBTwoOpt\fP &__move, const \fBRoute\fP &__route)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 43 of file two_opt_incr_eval.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-PEO: Parallel and Distributed Evolving Objects - Lessons from the source code.
