.TH "moeoArchiveFitnessSavingUpdater" 3 "16 Jan 2007" "Version 0.1" "ParadisEO-MOEO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moeoArchiveFitnessSavingUpdater \- This class allows to save the fitnesses of solutions contained in an archive into a file at each generation.  

.PP
.SH SYNOPSIS
.br
.PP
\fC#include <moeoArchiveFitnessSavingUpdater.h>\fP
.PP
Inherits \fBeoUpdater\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmoeoArchiveFitnessSavingUpdater\fP (\fBmoeoArchive\fP< EOT > &_arch, const std::string &_filename='Res/Arch', int _id=-1)"
.br
.RI "\fICtor. \fP"
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.RI "\fISaves the fitness of the archive's members into the file. \fP"
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBmoeoArchive\fP< EOT > & \fBarch\fP"
.br
.RI "\fIlocal archive \fP"
.ti -1c
.RI "std::string \fBfilename\fP"
.br
.RI "\fItarget filename \fP"
.ti -1c
.RI "int \fBid\fP"
.br
.RI "\fIown ID \fP"
.ti -1c
.RI "unsigned \fBcounter\fP"
.br
.RI "\fIcounter \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class EOT> class moeoArchiveFitnessSavingUpdater< EOT >"
This class allows to save the fitnesses of solutions contained in an archive into a file at each generation. 
.PP
Definition at line 27 of file moeoArchiveFitnessSavingUpdater.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class EOT> \fBmoeoArchiveFitnessSavingUpdater\fP< EOT >::\fBmoeoArchiveFitnessSavingUpdater\fP (\fBmoeoArchive\fP< EOT > & _arch, const std::string & _filename = \fC'Res/Arch'\fP, int _id = \fC-1\fP)\fC [inline]\fP"
.PP
Ctor. 
.PP
\fBParameters:\fP
.RS 4
\fI_arch\fP local archive 
.br
\fI_filename\fP target filename 
.br
\fI_id\fP own ID 
.RE
.PP

.PP
Definition at line 37 of file moeoArchiveFitnessSavingUpdater.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for ParadisEO-MOEO from the source code.
